	.align 2
voicegroup191::
	voice_keysplit_all voicegroup001  				//DRUMS
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 249, 25, 76  	//NYLON STR GUITAR
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_keysplit voicegroup006, KeySplitTable2 //STRINGS
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_keysplit voicegroup009, KeySplitTable5 //FRENCH HORNS
