	.align 2
voicegroup193:: @ 86B429D
	voice_keysplit_all voicegroup001  @ 869C2F0 //Drum Kit 1
	voice_keysplit voicegroup005, KeySplitTable1  @ 869C2FC //Bright Piano
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 128, 204, 51, 242  @ 86A0FD0 //Steinway Piano
	voice_keysplit_all voicegroup177  @ 86AFEC8 //Drum Kit 2
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 128, 249, 0, 188  @ 8699884 //Electric Piano 1 (Low)
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 188, 103, 165  @ 8699890 //Electric Piano 1 (High)
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 128, 204, 51, 242  @ 86A0FD0 //Steinway Piano
	voice_keysplit voicegroup005, KeySplitTable1  @ 869C2FC //Bright Piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 235  @ 8675D70 //Glockenspiel
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 235  @ 8675D70 //Glockenspiel
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0  @ 86AC5B0 //Music Box
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0  @ 86AC5B0 //Music Box
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204  @ 8677BC4 //Xylophone
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204  @ 8677BC4 //Xylophone
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 216, 90, 242  @ 86771E0 //Tubular Bells
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 206, 242  @ 8695BA0 //Dulcimer
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127  @ 8675DD0 //Percussive Organ
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127  @ 8675DD0 //Percussive Organ
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127  @ 8675DD0 //Percussive Organ
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188  @ 8697754 //Church Organ (Low)
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 76, 154, 188  @ 8697760 //Church Organ (High)
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165  @ 8678AC4 //Accordion
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165  @ 8678AC4 //Accordion
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165  @ 8678AC4 //Accordion
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 149  @ 8677648 //Nylon String Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 149  @ 8677648 //Nylon String Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 149  @ 8677648 //Nylon String Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 149  @ 8677648 //Nylon String Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 0, 255, 127  @ 86A1EA0 //Distortion Guitar (Low)
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127  @ 86965CC //Overdriven Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 255, 127  @ 86965D8 //Distortion Guitar (High)
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 195  @ 86981C8 //Guitar Harmonics
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149  @ 8675E84 //Fretless Bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 250, 0, 149  @ 867CCE8 //Fingered Bass
	voice_directsound 60, 0, DirectSoundWaveData_unknown_18, 255, 0, 206, 204  @ 86A01C0 //Picked Bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149  @ 8675E84 //Fretless Bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 115  @ 8675EB4 //Slap Bass 1
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 180, 216  @ 869A004 //Slap Bass 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115  @ 8675ECC //Synth Bass 1
	voice_directsound 60, 0, DirectSoundWaveData_trinity_30303_mega_bass, 255, 178, 180, 165  @ 8677B40 //Synth Bass 2
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44 //String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44 //String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44 //String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44 //String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44 //String Ensemble
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165  @ 867919C //Pizzicato Strings
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 0, 204  @ 8677360 //Harp
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 204, 193, 239  @ 8675F38 //Timpani
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44 //String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44 //String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44 //String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44 //String Ensemble
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0  @ 867613C //Choir Aahs
	voice_directsound 60, 0, DirectSoundWaveData_unknown_female_voice, 128, 165, 128, 204  @ 86988D0 //Voice Oohs
	voice_directsound 60, 0, DirectSoundWaveData_unused_unknown_male_voice, 128, 165, 128, 188  @ 86988DC //Voice Aah
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 204, 193, 239  @ 8675F38 //Timpani
	voice_keysplit voicegroup007, KeySplitTable3  @ 8675FA4 //Trumpet
	voice_keysplit voicegroup007, KeySplitTable3  @ 8675FA4 //Trumpet
	voice_keysplit voicegroup008, KeySplitTable4  @ 86773F0 //Tuba
	voice_keysplit voicegroup007, KeySplitTable3  @ 8675FA4 //Trumpet
	voice_keysplit voicegroup009, KeySplitTable5  @ 8677408 //French Horn
	voice_keysplit voicegroup009, KeySplitTable5  @ 8677408 //French Horn
	voice_keysplit voicegroup009, KeySplitTable5  @ 8677408 //French Horn
	voice_keysplit voicegroup009, KeySplitTable5  @ 8677408 //French Horn
	voice_keysplit voicegroup007, KeySplitTable3  @ 8675FA4 //Trumpet
	voice_keysplit voicegroup007, KeySplitTable3  @ 8675FA4 //Trumpet
	voice_keysplit voicegroup007, KeySplitTable3  @ 8675FA4 //Trumpet
	voice_keysplit voicegroup007, KeySplitTable3  @ 8675FA4 //Trumpet
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 255, 165, 154, 127  @ 8676148 //Oboe
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 43, 165, 103, 165  @ 86A7120 //Oboe 2
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 255, 165, 154, 127  @ 8676148 //Oboe
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 255, 165, 154, 127  @ 8676148 //Oboe
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127  @ 8677894 //Flute
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127  @ 8677894 //Flute
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127  @ 8677894 //Flute
	voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 191, 97, 165  @ 86AC8BC //Shakuhachi
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 0, 255, 204  @ 8695F18 //Shakuhachi (Classical)
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 0, 255, 204  @ 8695F18 //Shakuhachi (Classical)
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 0, 255, 127  @ 86A1F60 //Whistle
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 0, 255, 127  @ 86A1F60 //Whistle
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 0, 255, 165  @ 869D190 //Square Wave
	voice_square_2 60, 0, 2, 0, 0, 9, 2  @ 8675D4C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675D40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675D40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675D40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675D40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675D40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675D40
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64 //Sweep Pad
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242  @ 8696080 //Koto
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242  @ 8696080 //Koto
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242  @ 8696080 //Koto
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242  @ 8696080 //Koto
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 0, 204  @ 8677360 //Harp
	voice_keysplit voicegroup007, KeySplitTable3  @ 8675FA4 //Trumpet
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44 //String Ensemble
	voice_keysplit voicegroup007, KeySplitTable3  @ 8675FA4 //Trumpet
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0  @ 86AC5B0 //Music Box
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0  @ 86AC5B0 //Music Box
	voice_directsound 60, 0, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 86A06D0 //Ambient Toms
	voice_directsound 60, 0, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 86A06D0 //Ambient Toms
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0  @ 86A06C4 //Taiko Drum
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 165  @ 869DA00 //Melodic Toms
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 165  @ 869DA00 //Melodic Toms
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216  @ 869C2E4 //Cymbal
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 195  @ 86981C8 //Guitar Harmonics
	voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 191, 97, 165  @ 86AC8BC //Shakuhachi
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 255, 0, 255, 127  @ 8684F5C //Seashore Bubbles
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 255, 0, 255, 127  @ 869D7FC //Wind
	voice_directsound 60, 0, DirectSoundWaveData_register_noise, 255, 0, 255, 76  @ 86A01B4 //Cash Register Noise
	voice_directsound 60, 0, DirectSoundWaveData_unknown_2, 255, 0, 255, 127  @ 869D76C //Truck Ride
	voice_directsound 60, 0, DirectSoundWaveData_unknown_10, 255, 255, 255, 127  @ 8694058 //Applause
	voice_directsound 60, 0, DirectSoundWaveData_unknown_1, 255, 0, 255, 165  @ 869D754 //Gunshot
