Tzhaar_Caves_1_MapScripts::
	.byte 0


BATTLE_TZHAAR_CAVES_1_TRAINER_1::
	trainerbattle_single TRAINER_TZHAAR_CAVES_1_TRAINER_1, BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_0, BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_1
	namebox BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_2
	msgbox BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_1
	hidenamebox
	release
	end


BATTLE_TZHAAR_CAVES_1_TRAINER_2::
	trainerbattle_single TRAINER_TZHAAR_CAVES_1_TRAINER_2, BATTLE_TZHAAR_CAVES_1_TRAINER_2_Text_0, BATTLE_TZHAAR_CAVES_1_TRAINER_2_Text_1
	namebox BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_2
	msgbox BATTLE_TZHAAR_CAVES_1_TRAINER_2_Text_1
	hidenamebox
	release
	end


BATTLE_TZHAAR_CAVES_1_TRAINER_3::
	trainerbattle_single TRAINER_TZHAAR_CAVES_1_TRAINER_3, BATTLE_TZHAAR_CAVES_1_TRAINER_3_Text_0, BATTLE_TZHAAR_CAVES_1_TRAINER_3_Text_1
	namebox BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_2
	msgbox BATTLE_TZHAAR_CAVES_1_TRAINER_3_Text_1
	hidenamebox
	release
	end


BATTLE_TZHAAR_CAVES_1_TRAINER_4::
	trainerbattle_single TRAINER_TZHAAR_CAVES_1_TRAINER_4, BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_0, BATTLE_TZHAAR_CAVES_1_TRAINER_4_Text_0
	namebox BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_2
	msgbox BATTLE_TZHAAR_CAVES_1_TRAINER_4_Text_0
	hidenamebox
	release
	end


BATTLE_TZHAAR_CAVES_1_TRAINER_5::
	trainerbattle_single TRAINER_TZHAAR_CAVES_1_TRAINER_5, BATTLE_TZHAAR_CAVES_1_TRAINER_5_Text_0, BATTLE_TZHAAR_CAVES_1_TRAINER_5_Text_1
	namebox BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_2
	msgbox BATTLE_TZHAAR_CAVES_1_TRAINER_5_Text_1
	hidenamebox
	release
	end


BATTLE_TZHAAR_CAVES_1_TRAINER_6::
	trainerbattle_single TRAINER_TZHAAR_CAVES_1_TRAINER_6, BATTLE_TZHAAR_CAVES_1_TRAINER_6_Text_0, BATTLE_TZHAAR_CAVES_1_TRAINER_6_Text_1
	namebox BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_2
	msgbox BATTLE_TZHAAR_CAVES_1_TRAINER_6_Text_1
	hidenamebox
	release
	end


BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_0:
	.string "You need help little JalYt?$"

BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_1:
	.string "Maybe not..$"

BATTLE_TZHAAR_CAVES_1_TRAINER_1_Text_2:
	.string "TZHAAR$"

BATTLE_TZHAAR_CAVES_1_TRAINER_2_Text_0:
	.string "Our obsidian bodies are harder than any\n"
	.string "JalYt.$"

BATTLE_TZHAAR_CAVES_1_TRAINER_2_Text_1:
	.string "You tougher than you look.$"

BATTLE_TZHAAR_CAVES_1_TRAINER_3_Text_0:
	.string "You are not trusted, this is secret\n"
	.string "area.$"

BATTLE_TZHAAR_CAVES_1_TRAINER_3_Text_1:
	.string "Less questions! Move on now JalYt.$"

BATTLE_TZHAAR_CAVES_1_TRAINER_4_Text_0:
	.string "You may beat me but you never beat\n"
	.string "TzTok-Jad!$"

BATTLE_TZHAAR_CAVES_1_TRAINER_5_Text_0:
	.string "Kot kl, zek e JalYt!$"

BATTLE_TZHAAR_CAVES_1_TRAINER_5_Text_1:
	.string "Very few JalYt ever make it this far.$"

BATTLE_TZHAAR_CAVES_1_TRAINER_6_Text_0:
	.string "Does this JalYt have what it takes to\n"
	.string "become a Kal-Xil?$"

BATTLE_TZHAAR_CAVES_1_TRAINER_6_Text_1:
	.string "One final test remains then we find out.$"
