#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define OBJ_EVENT_GFX_BRENDAN_NORMAL               0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE            1
#define OBJ_EVENT_GFX_BRENDAN_SURFING              2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE           3
#define OBJ_EVENT_GFX_LIGHT_SPRITE                 4
#define OBJ_EVENT_GFX_NINJA_BOY                    5
#define OBJ_EVENT_GFX_TWIN                         6
#define OBJ_EVENT_GFX_BOY_1                        7
#define OBJ_EVENT_GFX_GIRL_1                       8
#define OBJ_EVENT_GFX_BOY_2                        9
#define OBJ_EVENT_GFX_GIRL_2                      10
#define OBJ_EVENT_GFX_LITTLE_BOY                  11
#define OBJ_EVENT_GFX_LITTLE_GIRL                 12
#define OBJ_EVENT_GFX_BOY_3                       13
#define OBJ_EVENT_GFX_GIRL_3                      14
#define OBJ_EVENT_GFX_RICH_BOY                    15
#define OBJ_EVENT_GFX_CUPHOLDER1                  16
#define OBJ_EVENT_GFX_FAT_MAN                     17
#define OBJ_EVENT_GFX_POKEFAN_F                   18
#define OBJ_EVENT_GFX_CUPHOLDER2                  19
#define OBJ_EVENT_GFX_WOMAN_2                     20
#define OBJ_EVENT_GFX_EXPERT_M                    21
#define OBJ_EVENT_GFX_EXPERT_F                    22
#define OBJ_EVENT_GFX_MAN_2                       23
#define OBJ_EVENT_GFX_WOMAN_3                     24
#define OBJ_EVENT_GFX_POKEFAN_M                   25
#define OBJ_EVENT_GFX_WOMAN_4                     26
#define OBJ_EVENT_GFX_CUPHOLDER3                  27
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST           28
#define OBJ_EVENT_GFX_OLD_MAN                     29
#define OBJ_EVENT_GFX_OLD_WOMAN                   30
#define OBJ_EVENT_GFX_CAMPER                      31
#define OBJ_EVENT_GFX_PICNICKER                   32
#define OBJ_EVENT_GFX_MAN_3                       33
#define OBJ_EVENT_GFX_WOMAN_5                     34
#define OBJ_EVENT_GFX_YOUNGSTER                   35
#define OBJ_EVENT_GFX_BUG_CATCHER                 36
#define OBJ_EVENT_GFX_PSYCHIC_M                   37
#define OBJ_EVENT_GFX_SCHOOL_KID_M                38
#define OBJ_EVENT_GFX_MANIAC                      39
#define OBJ_EVENT_GFX_HEX_MANIAC                  40
#define OBJ_EVENT_GFX_RAYQUAZA_STILL              41
#define OBJ_EVENT_GFX_SWIMMER_M                   42
#define OBJ_EVENT_GFX_SWIMMER_F                   43
#define OBJ_EVENT_GFX_BLACK_BELT                  44
#define OBJ_EVENT_GFX_BEAUTY                      45
#define OBJ_EVENT_GFX_SCIENTIST_1                 46
#define OBJ_EVENT_GFX_LASS                        47
#define OBJ_EVENT_GFX_GENTLEMAN                   48
#define OBJ_EVENT_GFX_CUPHOLDER4                  49
#define OBJ_EVENT_GFX_CUPHOLDER5                  50
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M        51
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F        52
#define OBJ_EVENT_GFX_TUBER_F                     53
#define OBJ_EVENT_GFX_TUBER_M                     54
#define OBJ_EVENT_GFX_HIKER                       55
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M        56
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F        57
#define OBJ_EVENT_GFX_NURSE                       58
#define OBJ_EVENT_GFX_ITEM_BALL                   59
#define OBJ_EVENT_GFX_BERRY_TREE                  60
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     61
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      62
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE           63
#define OBJ_EVENT_GFX_PROF_BIRCH                  64
#define OBJ_EVENT_GFX_MAN_4                       65
#define OBJ_EVENT_GFX_MAN_5                       66
#define OBJ_EVENT_GFX_REPORTER_M                  67
#define OBJ_EVENT_GFX_REPORTER_F                  68
#define OBJ_EVENT_GFX_BARD                        69
#define OBJ_EVENT_GFX_ANABEL                      70
#define OBJ_EVENT_GFX_TUCKER                      71
#define OBJ_EVENT_GFX_GRETA                       72
#define OBJ_EVENT_GFX_SPENSER                     73
#define OBJ_EVENT_GFX_NOLAND                      74
#define OBJ_EVENT_GFX_LUCY                        75
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL            76
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL       77
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL        78
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL          79
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL         80
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL        81
#define OBJ_EVENT_GFX_CUTTABLE_TREE               82
#define OBJ_EVENT_GFX_MART_EMPLOYEE               83
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN          84
#define OBJ_EVENT_GFX_TEALA                       85
#define OBJ_EVENT_GFX_BREAKABLE_ROCK              86
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER            87
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT             88
#define OBJ_EVENT_GFX_MAY_NORMAL                  89
#define OBJ_EVENT_GFX_MAY_MACH_BIKE               90
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE               91
#define OBJ_EVENT_GFX_MAY_SURFING                 92
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE              93
#define OBJ_EVENT_GFX_TRUCK                       94
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX       95
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY        96
#define OBJ_EVENT_GFX_BIRCHS_BAG                  97
#define OBJ_EVENT_GFX_ZIGZAGOON_1                 98
#define OBJ_EVENT_GFX_ARTIST                      99
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       100
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    101
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    102
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      103
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   104
#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           105
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        106
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        107
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING          108
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       109
#define OBJ_EVENT_GFX_CAMERAMAN                  110
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER         111
#define OBJ_EVENT_GFX_MAY_UNDERWATER             112
#define OBJ_EVENT_GFX_MOVING_BOX                 113
#define OBJ_EVENT_GFX_CABLE_CAR                  114
#define OBJ_EVENT_GFX_SCIENTIST_2                115
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE             116
#define OBJ_EVENT_GFX_AQUA_MEMBER_M              117
#define OBJ_EVENT_GFX_AQUA_MEMBER_F              118
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M             119
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F             120
#define OBJ_EVENT_GFX_SIDNEY                     121
#define OBJ_EVENT_GFX_PHOEBE                     122
#define OBJ_EVENT_GFX_GLACIA                     123
#define OBJ_EVENT_GFX_DRAKE                      124
#define OBJ_EVENT_GFX_ROXANNE                    125
#define OBJ_EVENT_GFX_BRAWLY                     126
#define OBJ_EVENT_GFX_WATTSON                    127
#define OBJ_EVENT_GFX_FLANNERY                   128
#define OBJ_EVENT_GFX_NORMAN                     129
#define OBJ_EVENT_GFX_WINONA                     130
#define OBJ_EVENT_GFX_LIZA                       131
#define OBJ_EVENT_GFX_TATE                       132
#define OBJ_EVENT_GFX_WALLACE                    133
#define OBJ_EVENT_GFX_STEVEN                     134
#define OBJ_EVENT_GFX_WALLY                      135
#define OBJ_EVENT_GFX_LITTLE_BOY_3               136
#define OBJ_EVENT_GFX_BRENDAN_FISHING            137
#define OBJ_EVENT_GFX_MAY_FISHING                138
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      139
#define OBJ_EVENT_GFX_SS_TIDAL                   140
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           141
#define OBJ_EVENT_GFX_PICHU_DOLL                 142
#define OBJ_EVENT_GFX_PIKACHU_DOLL               143
#define OBJ_EVENT_GFX_MARILL_DOLL                144
#define OBJ_EVENT_GFX_TOGEPI_DOLL                145
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL             146
#define OBJ_EVENT_GFX_CHIKORITA_DOLL             147
#define OBJ_EVENT_GFX_TOTODILE_DOLL              148
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            149
#define OBJ_EVENT_GFX_MEOWTH_DOLL                150
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL              151
#define OBJ_EVENT_GFX_DITTO_DOLL                 152
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL              153
#define OBJ_EVENT_GFX_TREECKO_DOLL               154
#define OBJ_EVENT_GFX_TORCHIC_DOLL               155
#define OBJ_EVENT_GFX_MUDKIP_DOLL                156
#define OBJ_EVENT_GFX_DUSKULL_DOLL               157
#define OBJ_EVENT_GFX_WYNAUT_DOLL                158
#define OBJ_EVENT_GFX_BALTOY_DOLL                159
#define OBJ_EVENT_GFX_KECLEON_DOLL               160
#define OBJ_EVENT_GFX_AZURILL_DOLL               161
#define OBJ_EVENT_GFX_SKITTY_DOLL                162
#define OBJ_EVENT_GFX_SWABLU_DOLL                163
#define OBJ_EVENT_GFX_GULPIN_DOLL                164
#define OBJ_EVENT_GFX_LOTAD_DOLL                 165
#define OBJ_EVENT_GFX_SEEDOT_DOLL                166
#define OBJ_EVENT_GFX_PIKA_CUSHION               167
#define OBJ_EVENT_GFX_ROUND_CUSHION              168
#define OBJ_EVENT_GFX_KISS_CUSHION               169
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION             170
#define OBJ_EVENT_GFX_SPIN_CUSHION               171
#define OBJ_EVENT_GFX_DIAMOND_CUSHION            172
#define OBJ_EVENT_GFX_BALL_CUSHION               173
#define OBJ_EVENT_GFX_GRASS_CUSHION              174
#define OBJ_EVENT_GFX_FIRE_CUSHION               175
#define OBJ_EVENT_GFX_WATER_CUSHION              176
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL           177
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL            178
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            179
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL          180
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL         181
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL         182
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL           183
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL          184
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL            185
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL         186
#define OBJ_EVENT_GFX_LATIAS                     187
#define OBJ_EVENT_GFX_LATIOS                     188
#define OBJ_EVENT_GFX_GAMEBOY_KID                189
#define OBJ_EVENT_GFX_CONTEST_JUDGE              190
#define OBJ_EVENT_GFX_BRENDAN_WATERING           191
#define OBJ_EVENT_GFX_MAY_WATERING               192
#define OBJ_EVENT_GFX_BRENDAN_DECORATING         193
#define OBJ_EVENT_GFX_MAY_DECORATING             194
#define OBJ_EVENT_GFX_ARCHIE                     195
#define OBJ_EVENT_GFX_MAXIE                      196
#define OBJ_EVENT_GFX_KYOGRE_FRONT               197
#define OBJ_EVENT_GFX_GROUDON_FRONT              198
#define OBJ_EVENT_GFX_FOSSIL                     199
#define OBJ_EVENT_GFX_REGIROCK                   200
#define OBJ_EVENT_GFX_REGICE                     201
#define OBJ_EVENT_GFX_REGISTEEL                  202
#define OBJ_EVENT_GFX_SKITTY                     203
#define OBJ_EVENT_GFX_KECLEON                    204
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP              205
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             206
#define OBJ_EVENT_GFX_RAYQUAZA                   207
#define OBJ_EVENT_GFX_ZIGZAGOON_2                208
#define OBJ_EVENT_GFX_PIKACHU                    209
#define OBJ_EVENT_GFX_AZUMARILL                  210
#define OBJ_EVENT_GFX_WINGULL                    211
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW      212
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING           213
#define OBJ_EVENT_GFX_AZURILL                    214
#define OBJ_EVENT_GFX_MOM                        215
#define OBJ_EVENT_GFX_LINK_BRENDAN               216
#define OBJ_EVENT_GFX_LINK_MAY                   217
#define OBJ_EVENT_GFX_JUAN                       218
#define OBJ_EVENT_GFX_SCOTT                      219
#define OBJ_EVENT_GFX_POOCHYENA                  220
#define OBJ_EVENT_GFX_KYOGRE_SIDE                221
#define OBJ_EVENT_GFX_GROUDON_SIDE               222
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           223
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         224
#define OBJ_EVENT_GFX_KIRLIA                     225
#define OBJ_EVENT_GFX_DUSCLOPS                   226
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE           227
#define OBJ_EVENT_GFX_SUDOWOODO                  228
#define OBJ_EVENT_GFX_MEW                        229
#define OBJ_EVENT_GFX_RED                        230
#define OBJ_EVENT_GFX_LEAF                       231
#define OBJ_EVENT_GFX_DEOXYS                     232
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE            233
#define OBJ_EVENT_GFX_BRANDON                    234
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN            235
#define OBJ_EVENT_GFX_LINK_RS_MAY                236
#define OBJ_EVENT_GFX_LUGIA                      237
#define OBJ_EVENT_GFX_HOOH                       238
//POKESCAPE OVERWORLD NPCS
#define OBJ_EVENT_GFX_SKELETON_1				239
#define OBJ_EVENT_GFX_SKELETON_2				240
#define OBJ_EVENT_GFX_SKELETON_3				241
#define OBJ_EVENT_GFX_DWARF_1				    242
#define OBJ_EVENT_GFX_DWARF_2				    243
#define OBJ_EVENT_GFX_DWARF_3				    244
#define OBJ_EVENT_GFX_DWARF_4				    245
#define OBJ_EVENT_GFX_TRIBEMEN_1				246
#define OBJ_EVENT_GFX_TRIBEMEN_2				247
#define OBJ_EVENT_GFX_TRIBEMEN_3				248
#define OBJ_EVENT_GFX_MONK_1				    249
#define OBJ_EVENT_GFX_MONK_2				    250
#define OBJ_EVENT_GFX_DRUID_1				    251
#define OBJ_EVENT_GFX_DRUID_2				    252
#define OBJ_EVENT_GFX_DRUID_3				    253
#define OBJ_EVENT_GFX_MAGGIE				    254
#define OBJ_EVENT_GFX_WENDY				        255
#define OBJ_EVENT_GFX_HAM_JOHANHUS				256
#define OBJ_EVENT_GFX_HAM_SIGMUND_1		        257
#define OBJ_EVENT_GFX_HAM_SIGMUND_2		        258
#define OBJ_EVENT_GFX_HAM_PATTY				    259
#define OBJ_EVENT_GFX_HAM_DEACON				260
#define OBJ_EVENT_GFX_HAM_GRUNT_M				261
#define OBJ_EVENT_GFX_HAM_GRUNT_F				262
#define OBJ_EVENT_GFX_GOBLIN_1				    263
#define OBJ_EVENT_GFX_GOBLIN_2				    264
#define OBJ_EVENT_GFX_GOBLIN_GENERALBENTNOZE    265
#define OBJ_EVENT_GFX_GOBLIN_GENERALWARTFACE    266
#define OBJ_EVENT_GFX_GOEBIE_1				    267
#define OBJ_EVENT_GFX_GOEBIE_2				    268
#define OBJ_EVENT_GFX_GOEBIE_3				    269
#define OBJ_EVENT_GFX_GOEBIE_4				    270
#define OBJ_EVENT_GFX_GOEBIE_5				    271
#define OBJ_EVENT_GFX_GOEBIE_6				    272
#define OBJ_EVENT_GFX_PIRATE_1				    273
#define OBJ_EVENT_GFX_PIRATE_2				    274
#define OBJ_EVENT_GFX_PIRATE_3				    275
#define OBJ_EVENT_GFX_BARBARIAN_FEMALE_1	    276
#define OBJ_EVENT_GFX_BARBARIAN_FEMALE_2	    277
#define OBJ_EVENT_GFX_BARBARIAN_MALE_1		    278
#define OBJ_EVENT_GFX_BARBARIAN_MALE_2		    279
#define OBJ_EVENT_GFX_TZHAAR_GA_AL				280
#define OBJ_EVENT_GFX_TZHAAR_1				    281
#define OBJ_EVENT_GFX_TZHAAR_2				    282
#define OBJ_EVENT_GFX_TZHAAR_3				    283
#define OBJ_EVENT_GFX_TZHAAR_4				    284
#define OBJ_EVENT_GFX_WIZARD_DARK				285
#define OBJ_EVENT_GFX_WIZARD_GUTHIX				286
#define OBJ_EVENT_GFX_WIZARD_GUTHIX_DAGGER	    287
#define OBJ_EVENT_GFX_WIZARD_M				    288
#define OBJ_EVENT_GFX_WIZARD_F				    289
#define OBJ_EVENT_GFX_WIZARD_ARCHMAGE				290
#define OBJ_EVENT_GFX_KNIGHT_WHITE_F				291
#define OBJ_EVENT_GFX_KNIGHT_WHITE_M				292
#define OBJ_EVENT_GFX_KNIGHT_WHITE_SIRTIFFYCASHIN   293
#define OBJ_EVENT_GFX_KNIGHT_BLACK_F				294
#define OBJ_EVENT_GFX_KNIGHT_BLACK_M				295
#define OBJ_EVENT_GFX_KNIGHT_BLACK_DAQUARIUS	    296
#define OBJ_EVENT_GFX_BANKER_F				    297
#define OBJ_EVENT_GFX_BANKER_M				    298
#define OBJ_EVENT_GFX_GENERAL_STORE_CLERK	    299
#define OBJ_EVENT_GFX_GUARD_KHAZARD				300
#define OBJ_EVENT_GFX_GUARD_FALADOR				301
#define OBJ_EVENT_GFX_GUARD_ALKHAIRD		    302
#define OBJ_EVENT_GFX_GUARD_DRAYNOR				303
#define OBJ_EVENT_GFX_GUARD_VARROCK_1		    304
#define OBJ_EVENT_GFX_GUARD_VARROCK_2		    305
#define OBJ_EVENT_GFX_GUARD_VARROCK_3		    306
#define OBJ_EVENT_GFX_FAIRY_1				    307
#define OBJ_EVENT_GFX_FAIRY_2				    308
#define OBJ_EVENT_GFX_FAIRY_3				    309
#define OBJ_EVENT_GFX_IRONMAN				    310
#define OBJ_EVENT_GFX_MITHRILMAN				311
#define OBJ_EVENT_GFX_ADAMANTMAN				312
#define OBJ_EVENT_GFX_BARROWS_AHRIM				313
#define OBJ_EVENT_GFX_BARROWS_DHAROK		    314
#define OBJ_EVENT_GFX_BARROWS_KARIL				315
#define OBJ_EVENT_GFX_BARROWS_VERAC				316
#define OBJ_EVENT_GFX_BARROWS_TORAG				317
#define OBJ_EVENT_GFX_BARROWS_GUTHAN		    318
#define OBJ_EVENT_GFX_BARROWS_SILSKE		    319
#define OBJ_EVENT_GFX_MAN_1				        320
#define OBJ_EVENT_GFX_WOMAN_1				    321
//SKILLS
#define OBJ_EVENT_GFX_GRACEFUL				    322
#define OBJ_EVENT_GFX_CHEF				        323
#define OBJ_EVENT_GFX_FIREMAKER				    324
#define OBJ_EVENT_GFX_WOODCUTTER				325
#define OBJ_EVENT_GFX_SUMMONER				    326
#define OBJ_EVENT_GFX_MERCHER				    327
#define OBJ_EVENT_GFX_FISHERMAN				    328
#define OBJ_EVENT_GFX_HUNTER_M				    329
#define OBJ_EVENT_GFX_HUNTER_F				    330
#define OBJ_EVENT_GFX_FARMER_M				    331
#define OBJ_EVENT_GFX_FARMER_F				    332
//			    	333
#define OBJ_EVENT_GFX_NOOB				        334
#define OBJ_EVENT_GFX_QUESTER				    335
#define OBJ_EVENT_GFX_JMOD				        336
#define OBJ_EVENT_GFX_DND				        337
#define OBJ_EVENT_GFX_BOT_DRAGON				338
#define OBJ_EVENT_GFX_MUGGER				    339
#define OBJ_EVENT_GFX_THIEF				        340
#define OBJ_EVENT_GFX_BARMAID				    341
#define OBJ_EVENT_GFX_PKER				        342
#define OBJ_EVENT_GFX_PVMER				        343
#define OBJ_EVENT_GFX_SKILLER				    344
#define OBJ_EVENT_GFX_RSMVER_M				    345
#define OBJ_EVENT_GFX_RSMVER_F				    346
#define OBJ_EVENT_GFX_SAILOR				    347
#define OBJ_EVENT_GFX_RANGER_F				    348
//PLAYERS
#define OBJ_EVENT_GFX_SUDO_BASH				    349
#define OBJ_EVENT_GFX_DEMONHEADGE				350
#define OBJ_EVENT_GFX_PREZLEEK				    351
#define OBJ_EVENT_GFX_LUKIENLIGHT				352
#define OBJ_EVENT_GFX_HYPER_STAN				353
//UNIQUE NPCS
#define OBJ_EVENT_GFX_HANS				        354
#define OBJ_EVENT_GFX_HAIRDRESSER				355
#define OBJ_EVENT_GFX_COOK				        356
#define OBJ_EVENT_GFX_COUNT_DRAYNOR				357
#define OBJ_EVENT_GFX_GNOME_CHILD				358
#define OBJ_EVENT_GFX_BARAEK				    359
#define OBJ_EVENT_GFX_DIANGO				    360
#define OBJ_EVENT_GFX_HAIG_HALEN				361
#define OBJ_EVENT_GFX_KATRINE				    362
#define OBJ_EVENT_GFX_PROF_NORMAL_TREE		    363
#define OBJ_EVENT_GFX_STRAVEN				    364
#define OBJ_EVENT_GFX_EXPLORER_JACK				365
#define OBJ_EVENT_GFX_FORTUNATO				    366
#define OBJ_EVENT_GFX_SARADOMIN				    367
#define OBJ_EVENT_GFX_ZAMORAK				    368
#define OBJ_EVENT_GFX_GUTHIX				    369
#define OBJ_EVENT_GFX_AVA				        370
#define OBJ_EVENT_GFX_RELDO				        371
#define OBJ_EVENT_GFX_MAX				        372
#define OBJ_EVENT_GFX_SIR_OWEN				    373
#define OBJ_EVENT_GFX_OZAN				        374
#define OBJ_EVENT_GFX_XENIA				        375
#define OBJ_EVENT_GFX_RAPTOR				    376
#define OBJ_EVENT_GFX_ARIANE				    377
#define OBJ_EVENT_GFX_ZANIK				        378
#define OBJ_EVENT_GFX_ZANIK_HAM				    379
//ITEMS
#define OBJ_EVENT_GFX_BONE_PILE				    380
#define OBJ_EVENT_GFX_ITEM_POUCH				381
#define OBJ_EVENT_GFX_PHOENIX_EGG				382
#define OBJ_EVENT_GFX_SHIP_1				    383
//MONSTERS
#define OBJ_EVENT_GFX_DUCK_SWIM				    384
#define OBJ_EVENT_GFX_DUCK_WALK				    385
#define OBJ_EVENT_GFX_BASILISK				    386
#define OBJ_EVENT_GFX_COW				        387
#define OBJ_EVENT_GFX_COW_DAIRY				    388
#define OBJ_EVENT_GFX_CHICKEN				    389
#define OBJ_EVENT_GFX_EVIL_CHICKEN				390
#define OBJ_EVENT_GFX_IMP				        391
#define OBJ_EVENT_GFX_IMP_SNOW				    392
#define OBJ_EVENT_GFX_KALPHITE_KING				393
#define OBJ_EVENT_GFX_KALPHITE_QUEEN		    394
#define OBJ_EVENT_GFX_KALPHITE_WORKER		    395
#define OBJ_EVENT_GFX_GWD_GENERAL_GRAADOR	    396
#define OBJ_EVENT_GFX_ABYSSAL_SIRE				397
#define OBJ_EVENT_GFX_VORAGO				    398
#define OBJ_EVENT_GFX_PIGLET				    399
#define OBJ_EVENT_GFX_PIGZILLA				    400
#define OBJ_EVENT_GFX_YAK				        401
#define OBJ_EVENT_GFX_PENGUIN_ROCK				402
#define OBJ_EVENT_GFX_QUEEN_BLACK_DRAGON	    403
#define OBJ_EVENT_GFX_ELVARG				    404
#define OBJ_EVENT_GFX_KING_BLACK_DRAGON		    405
#define OBJ_EVENT_GFX_RAT				        406
#define OBJ_EVENT_GFX_RUNE_GUARDIAN				407
#define OBJ_EVENT_GFX_SHEEP				        408
#define OBJ_EVENT_GFX_SARALING				    409
#define OBJ_EVENT_GFX_SARAOWL				    410
#define OBJ_EVENT_GFX_GUTHRAPTOR				411
#define OBJ_EVENT_GFX_SKELETAL_OX_M				412
#define OBJ_EVENT_GFX_SKELETAL_OX_F				413
#define OBJ_EVENT_GFX_TERRORBIRD_1				414
#define OBJ_EVENT_GFX_TERRORBIRD_2				415
#define OBJ_EVENT_GFX_TZTOK_JAD				    416
#define OBJ_EVENT_GFX_MOLE_GIANT				417
#define OBJ_EVENT_GFX_MOLE_BABY				    418
#define OBJ_EVENT_GFX_CAMEL				        419
#define OBJ_EVENT_GFX_FROGEEL				    420
#define OBJ_EVENT_GFX_SCORPION				    421
#define OBJ_EVENT_GFX_SLIME				        422
#define OBJ_EVENT_GFX_RAVEN				        423
#define OBJ_EVENT_GFX_SEAGULL				    424
#define OBJ_EVENT_GFX_STRYKEWYRM_SANDY		    425
#define OBJ_EVENT_GFX_UNICORN_WHITE				426
#define OBJ_EVENT_GFX_UNICORN_BLACK				427
//GYMLEADERS
#define OBJ_EVENT_GFX_GYMLEADER_DUKE_HORACIO    428
#define OBJ_EVENT_GFX_GYMLEADER_SIR_AMIK_VARZE  429
#define OBJ_EVENT_GFX_GYMLEADER_PRINCE_ALI	    430
#define OBJ_EVENT_GFX_GYMLEADER_KING_ROALD	    431
#define OBJ_EVENT_GFX_GYMLEADER_TOKHAARHOK	    432
#define OBJ_EVENT_GFX_GYMLEADER_GUNTHOR		    433
#define OBJ_EVENT_GFX_GYMLEADER_WISE_OLD_MAN    434
#define OBJ_EVENT_GFX_GYMLEADER_VANNAKA		    435
//CHAMPIONS
#define OBJ_EVENT_GFX_BOATY				        436
#define OBJ_EVENT_GFX_SUOMI				        437
#define OBJ_EVENT_GFX_ZEZIMA				    438
//ORES
#define OBJ_EVENT_GFX_COPPER_ORE				 439
#define OBJ_EVENT_GFX_TIN_ORE				 	 440
#define OBJ_EVENT_GFX_IRON_ORE					 441
#define OBJ_EVENT_GFX_COAL_ORE				 	 442
#define OBJ_EVENT_GFX_MITHRIL_ORE				 443
#define OBJ_EVENT_GFX_ADAMANT_ORE				 444
#define OBJ_EVENT_GFX_RUNE_ORE				 	 445
#define OBJ_EVENT_GFX_ORIKALKUM_ORE				 446
#define OBJ_EVENT_GFX_ELEMENTAL_ORE				 447
#define OBJ_EVENT_GFX_BANE_ORE				 	 448
//OTHER
#define OBJ_EVENT_GFX_ABYSSAL_DEMON		        449
#define OBJ_EVENT_GFX_CHAOS_ELEMENTAL		    450
#define OBJ_EVENT_GFX_MINER				        451
#define OBJ_EVENT_GFX_SMITH				        452
#define OBJ_EVENT_GFX_DOG_SLEEP				    453
#define OBJ_EVENT_GFX_JUNA			            454
#define OBJ_EVENT_GFX_ABYSS_PORTAL				455
#define OBJ_EVENT_GFX_CHAIR				        456
#define OBJ_EVENT_GFX_STRYKEWYRM_FREEZY		    457
#define OBJ_EVENT_GFX_STRYKEWYRM_LEAFY		    458

#define OBJ_EVENT_GFX_CAT_BLACK		            459
#define OBJ_EVENT_GFX_CAT_WHITE		            460
#define OBJ_EVENT_GFX_CAT_BROWN		            461
#define OBJ_EVENT_GFX_CAT_HELL		            462
#define OBJ_EVENT_GFX_CAT_BLACKWHITE		    463
#define OBJ_EVENT_GFX_CAT_CLOCKWORK		        464
#define OBJ_EVENT_GFX_CAT_BROWNWHITE	    	465
#define OBJ_EVENT_GFX_CAT_PURPLE	        	466
#define OBJ_EVENT_GFX_ARCHAEOLOGIST	        	467
#define OBJ_EVENT_GFX_DIVINER		            468
#define OBJ_EVENT_GFX_DURIAL321		            469
#define OBJ_EVENT_GFX_SARADOMIN_OWL	        	470
#define OBJ_EVENT_GFX_ZAMORAK_HAWK	        	471
#define OBJ_EVENT_GFX_GUTHIX_RAPTOR		        472
#define OBJ_EVENT_GFX_DOG_STRAY	            	473
#define OBJ_EVENT_GFX_DOG_LABRADOR	        	474
#define OBJ_EVENT_GFX_DOG_GUARD		            475
#define OBJ_EVENT_GFX_DOG_CORGI		            476
#define OBJ_EVENT_GFX_DOG_DALMATIAN	        	477
#define OBJ_EVENT_GFX_PKER_RUSHER				478
#define OBJ_EVENT_GFX_RUNE_ARMOUR				479
#define OBJ_EVENT_GFX_HAM_BABE				    480

#define OBJ_EVENT_GFX_SMUGGLER				    481

#define OBJ_EVENT_GFX_RAC_BATS				    482
#define OBJ_EVENT_GFX_RAC_DRAGON				483
#define OBJ_EVENT_GFX_RAC_ELEJ				    484
#define OBJ_EVENT_GFX_RAC_JACKIE				485
#define OBJ_EVENT_GFX_RAC_BONBUN				486
#define OBJ_EVENT_GFX_RAC_DEWYDD		        487
#define OBJ_EVENT_GFX_RAC_ELIZABETH		        488
#define OBJ_EVENT_GFX_RAC_ENKO		            489
#define OBJ_EVENT_GFX_RAC_FAYDENE		        490
#define OBJ_EVENT_GFX_RAC_FLORIN		        491
#define OBJ_EVENT_GFX_RAC_ISOHEL		        492
#define OBJ_EVENT_GFX_RAC_JAXYYS		        493
#define OBJ_EVENT_GFX_RAC_MOGGIE		        494
#define OBJ_EVENT_GFX_RAC_NELLE		            495
#define OBJ_EVENT_GFX_RAC_PARRISH		        496
#define OBJ_EVENT_GFX_RAC_TIFA		            497
#define OBJ_EVENT_GFX_RAC_WHISPER		        498
#define OBJ_EVENT_GFX_RAC_ALEXANDRA		        499
#define OBJ_EVENT_GFX_RAC_BLKWITCH		        500
#define OBJ_EVENT_GFX_RAC_CHARM		            501
#define OBJ_EVENT_GFX_RAC_CRESBOT		        502
#define OBJ_EVENT_GFX_RAC_SNAILY		        503
#define OBJ_EVENT_GFX_RAC_KITTY		            504
#define OBJ_EVENT_GFX_RAC_POPBUBBLE		        505
#define OBJ_EVENT_GFX_CORP_BEAST		        506
#define OBJ_EVENT_GFX_CORP_CORE		            507
#define OBJ_EVENT_GFX_HILL_GIANT		        508
#define OBJ_EVENT_GFX_MOSS_GIANT		        509
#define OBJ_EVENT_GFX_FIRE_GIANT		        510
#define OBJ_EVENT_GFX_SKOTIZO		            511
#define OBJ_EVENT_GFX_DRAGON_RED		        512
#define OBJ_EVENT_GFX_DRAGON_BLACK		        513
#define OBJ_EVENT_GFX_DRAGON_BLUE		        514
#define OBJ_EVENT_GFX_DRAGON_GREEN		        515
#define OBJ_EVENT_GFX_DRAGON_ARMOUR			    516
#define OBJ_EVENT_GFX_DUNGEONEERING_1			517
#define OBJ_EVENT_GFX_DUNGEONEERING_2			518
#define OBJ_EVENT_GFX_DUNGEONEERING_3			519
#define OBJ_EVENT_GFX_DUNGEONEERING_4			520
#define OBJ_EVENT_GFX_DUNGEONEERING_5			521
#define OBJ_EVENT_GFX_DUNGEONEERING_6			522
#define OBJ_EVENT_GFX_DUNGEONEERING_7			523
#define OBJ_EVENT_GFX_DUNGEONEERING_8			524
#define OBJ_EVENT_GFX_DUNGEONEERING_9			525
#define OBJ_EVENT_GFX_HAZELMERE_1			    526
#define OBJ_EVENT_GFX_HAZELMERE_2		    	527
#define OBJ_EVENT_GFX_MYSTIC_BLUE			    528
#define OBJ_EVENT_GFX_MYSTIC_LIGHT			    529
#define OBJ_EVENT_GFX_NECROMANCER		    	530
#define OBJ_EVENT_GFX_RUNECRAFTER_GREEN			531
#define OBJ_EVENT_GFX_RUNECRAFTER_YELLOW	    532
#define OBJ_EVENT_GFX_WIZARD_ZAMORAK			533
#define OBJ_EVENT_GFX_THOK_ANGRY		    	534
#define OBJ_EVENT_GFX_THOK_HAPPY		    	535
#define OBJ_EVENT_GFX_KREEARRA			        536
#define OBJ_EVENT_GFX_STRYKEWYRM_WILDY			537
#define OBJ_EVENT_GFX_HANANNIE			        538
#define OBJ_EVENT_GFX_VORKATH			        539
#define OBJ_EVENT_GFX_BEHEMOTH			        540
#define OBJ_EVENT_GFX_ELVARG_FLY				541
#define OBJ_EVENT_GFX_BALANCE_ELEMENTAL         542
#define OBJ_EVENT_GFX_DUNGEONEER_1              543
#define OBJ_EVENT_GFX_EDDIMU                    544
#define OBJ_EVENT_GFX_GORAJO_1                  545
#define OBJ_EVENT_GFX_GORAJO_2                  546
#define OBJ_EVENT_GFX_FORGOTTEN_MAGE            547
#define OBJ_EVENT_GFX_FORGOTTEN_RANGER          548
#define OBJ_EVENT_GFX_GUARD_ARDY                549
#define OBJ_EVENT_GFX_KNIGHT_ARDY               550
#define OBJ_EVENT_GFX_MONKEY                    551
#define OBJ_EVENT_GFX_PENGUIN                   552
#define OBJ_EVENT_GFX_PENGUIN_BARREL            553
#define OBJ_EVENT_GFX_PENGUIN_BOX               554
#define OBJ_EVENT_GFX_PENGUIN_BUSH              555
#define OBJ_EVENT_GFX_PENGUIN_CACTUS            556
#define OBJ_EVENT_GFX_PENGUIN_TOADSTOOL         557
#define OBJ_EVENT_GFX_ROMEO                     558
#define OBJ_EVENT_GFX_SWAMPLETICS               559
#define OBJ_EVENT_GFX_LESSER_DEMON              560
#define OBJ_EVENT_GFX_DELRITH                   561
#define OBJ_EVENT_GFX_PIRATE_SHIP               562
#define OBJ_EVENT_GFX_TZHAAR_CHAMPION           563
#define OBJ_EVENT_GFX_TZ_KIH                    564
#define OBJ_EVENT_GFX_HAR_AKEN                  565
#define OBJ_EVENT_GFX_HAR_AKEN_TENTACLE         566
#define OBJ_EVENT_GFX_KET_DILL                  567
#define OBJ_EVENT_GFX_JITTERBUG                 568
#define OBJ_EVENT_GFX_PIKKUPSTIX                569
#define OBJ_EVENT_GFX_SEREN_SPIRIT              570

#define NUM_OBJ_EVENT_GFX                       (OBJ_EVENT_GFX_SEREN_SPIRIT + 1)
// NOTE: By default, the max value for NUM_OBJ_EVENT_GFX is 239.
//
// Object event graphics ids are 1 byte in size (max value of 255), and the dynamic
// graphics ids that start after NUM_OBJ_EVENT_GFX reach this limit. No graphics id
// uses the value 239 itself, so removing the "+ 1" in OBJ_EVENT_GFX_VARS would
// allow increasing NUM_OBJ_EVENT_GFX to 240. There are also a handful of unused
// object graphics that can be removed. If more graphics are needed, anything that
// stores graphics ids will need to be increased in size. See wiki entry below:
// https://github.com/pret/pokeemerald/wiki/Feature-Branches#overworld-expansion



// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0) // 480
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF) // 495

#define SHADOW_SIZE_S    0
#define SHADOW_SIZE_M    1
#define SHADOW_SIZE_L    2
#define SHADOW_SIZE_NONE 3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255 // Exclusive to FRLG

// Special object event local ids
#define OBJ_EVENT_ID_PLAYER 0xFF
#define OBJ_EVENT_ID_FOLLOWER 0xFE
#define OBJ_EVENT_ID_CAMERA 0x7F

// Object event local ids referenced in C files
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_FARAWAY_ISLAND_MEW 1
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9
#define LOCALID_BATTLE_TOWER_LOBBY_REPORTER 5
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3
#define LOCALID_OLDALE_MART_CLERK 1
#define LOCALID_LAVARIDGE_MART_CLERK 1
#define LOCALID_FALLARBOR_MART_CLERK 1
#define LOCALID_VERDANTURF_MART_CLERK 1
#define LOCALID_PETALBURG_MART_CLERK 1
#define LOCALID_SLATEPORT_MART_CLERK 1
#define LOCALID_MAUVILLE_MART_CLERK 1
#define LOCALID_RUSTBORO_MART_CLERK 1
#define LOCALID_FORTREE_MART_CLERK 1
#define LOCALID_MOSSDEEP_MART_CLERK 1
#define LOCALID_SOOTOPOLIS_MART_CLERK 1
#define LOCALID_BATTLE_FRONTIER_MART_CLERK 1
#define LOCALID_SLATEPORT_ENERGY_GURU 25

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
