#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Poké Balls
/*
#define ITEM_POUCH 1 // Regular
#define ITEM_POUCH_BRONZE 2 // Great
#define ITEM_POUCH_IRON 3 // Ultra
#define ITEM_POUCH_DRAGON 4 // Master
#define ITEM_POUCH 5 //Premier
#define ITEM_BLESSED_POUCH 6 // Heal
#define ITEM_LEATHER_POUCH 7 // Net
#define ITEM_POUCH_ELEMENTAL 8 // Nest
#define ITEM_CATALYTIC_POUCH 9 // Dive
#define ITEM_POUCH_CRYSTAL 10 // Dusk
#define ITEM_POUCH_ADAMANT 11 // Timer
#define ITEM_POUCH_MITHRIL 12 // Quick
#define ITEM_POUCH_AUGMENTED 13 // Repeat
#define ITEM_EMBROIDERED_POUCH 14 // Luxury
#define ITEM_POUCH_BARROWS 15 // Level
#define ITEM_SPIDERSILK_POUCH 16 // Lure
#define ITEM_POUCH_ANCIENT 17 // Moon
#define ITEM_ROYAL_POUCH 18 // Friend
#define ITEM_POUCH_MYSTIC 19 // Love
#define ITEM_POUCH_BANE 20 // Fast
#define ITEM_POUCH_GRANITE 21 // Heavy
#define ITEM_IMPHIDE_POUCH 22 // Dream
#define ITEM_GEM_POUCH 23 // Safari
#define ITEM_POUCH_SPLITBARK 24 // Sport
#define ITEM_POUCH_BLACK 25 // Park
#define ITEM_FISHBOWL_POUCH 26 // Beast
#define ITEM_CHERISH_BALL 27

#define ITEM_POUCH_STEEL ITEM_POUCH_BRONZE
#define ITEM_POUCH_RUNE ITEM_POUCH_IRON
*/

#define ITEM_POUCH              1   //  Premier     //  Pouch
#define ITEM_POUCH_BRONZE       2   //  Regular     //  Pouch
#define ITEM_POUCH_IRON         3   //  Lure        //  Lure Pouch
#define ITEM_POUCH_STEEL        4   //  Great       //  Great Pouch
#define ITEM_POUCH_MITHRIL      5   //  Quick       //  Quick Pouch
#define ITEM_POUCH_ADAMANT      6   //  Timer       //  Timer Pouch
#define ITEM_POUCH_RUNE         7   //  Ultra       //  Ultra Pouch
#define ITEM_POUCH_DRAGON       8   //  Master      //  Master Pouch
#define ITEM_POUCH_CRYSTAL      9   //              //  Shiny Pouch
#define ITEM_POUCH_BLACK        10  //  Dusk        //  Dark Pouch
#define ITEM_POUCH_WHITE        11  //              //  Light Pouch
#define ITEM_POUCH_ELEMENTAL    12  //              //  Elemental Pouch
#define ITEM_POUCH_CATALYTIC    13  //              //  Catalytic Pouch
#define ITEM_POUCH_BANE         14  //              //  Bane Pouch
#define ITEM_POUCH_AUGMENTED    15  //  Repeat      //  Repeat Pouch
#define ITEM_POUCH_ANCIENT      16  //  Luxury      //  Luxury Pouch
#define ITEM_POUCH_BARROWS      17  //  Level       //  Level Pouch
#define ITEM_POUCH_GRANITE      18  //  Heavy       //  Heavy Pouch
#define ITEM_POUCH_SPLITBARK    19  //              //  Status Pouch
#define ITEM_POUCH_MYSTIC       20  //  Heal        //  Heal Pouch
#define ITEM_POUCH_CUPHOLDER_1  21
#define ITEM_POUCH_CUPHOLDER_2  22
#define ITEM_POUCH_CUPHOLDER_3  23
#define ITEM_POUCH_CUPHOLDER_4  24
#define ITEM_POUCH_CUPHOLDER_5  25
#define ITEM_POUCH_CUPHOLDER_6  26
#define ITEM_POUCH_CUPHOLDER_7  27

// Note: If moving ball IDs around, updating FIRST_BALL/LAST_BALL is not sufficient
//       Several places expect the ball IDs to be first and contiguous (e.g. MON_DATA_POKEBALL)
//       If adding new balls, it's easiest to insert them after the last ball and increment the below IDs (and removing ITEM_034 for example)
#define FIRST_BALL ITEM_POUCH
#define LAST_BALL  ITEM_POUCH_MYSTIC

#define VANILLA_ITEM_START              ITEM_POUCH_CUPHOLDER_7       
// Medicine
#define ITEM_POTION                     (VANILLA_ITEM_START + 1 )
#define ITEM_SUPER_POTION               (VANILLA_ITEM_START + 2 )
#define ITEM_HYPER_POTION               (VANILLA_ITEM_START + 3 )
#define ITEM_MAX_POTION                 (VANILLA_ITEM_START + 4 )
#define ITEM_FULL_RESTORE               (VANILLA_ITEM_START + 5 )
#define ITEM_REVIVE                     (VANILLA_ITEM_START + 6 )
#define ITEM_MAX_REVIVE                 (VANILLA_ITEM_START + 7 )
#define ITEM_FRESH_WATER                (VANILLA_ITEM_START + 8 )
#define ITEM_SODA_POP                   (VANILLA_ITEM_START + 9 )
#define ITEM_LEMONADE                   (VANILLA_ITEM_START + 10 )
#define ITEM_MOOMOO_MILK                (VANILLA_ITEM_START + 11 )
#define ITEM_ENERGY_POWDER              (VANILLA_ITEM_START + 12 )
#define ITEM_ENERGYPOWDER               ITEM_ENERGY_POWDER // Pre-Gen VI name
#define ITEM_ENERGY_ROOT                (VANILLA_ITEM_START + 13 )
#define ITEM_HEAL_POWDER                (VANILLA_ITEM_START + 14 )
#define ITEM_REVIVAL_HERB               (VANILLA_ITEM_START + 15 )
#define ITEM_ANTIDOTE                   (VANILLA_ITEM_START + 16 )
#define ITEM_PARALYZE_HEAL              (VANILLA_ITEM_START + 17 )
#define ITEM_PARLYZ_HEAL                ITEM_PARALYZE_HEAL // Pre-Gen VI name
#define ITEM_BURN_HEAL                  (VANILLA_ITEM_START + 18 )
#define ITEM_ICE_HEAL                   (VANILLA_ITEM_START + 19 )
#define ITEM_AWAKENING                  (VANILLA_ITEM_START + 20 )
#define ITEM_FULL_HEAL                  (VANILLA_ITEM_START + 21 )
#define ITEM_ETHER                      (VANILLA_ITEM_START + 22 )
#define ITEM_MAX_ETHER                  (VANILLA_ITEM_START + 23 )
#define ITEM_ELIXIR                     (VANILLA_ITEM_START + 24 )
#define ITEM_ELIXER                     ITEM_ELIXIR // Pre-Gen III name
#define ITEM_MAX_ELIXIR                 (VANILLA_ITEM_START + 25 )
#define ITEM_MAX_ELIXER                 ITEM_MAX_ELIXIR // Pre-Gen III name
#define ITEM_BERRY_JUICE                (VANILLA_ITEM_START + 26 )
#define ITEM_SACRED_ASH                 (VANILLA_ITEM_START + 27 )
#define ITEM_SWEET_HEART                (VANILLA_ITEM_START + 28 )
#define ITEM_MAX_HONEY                  (VANILLA_ITEM_START + 29 )
// Regional Specialties
#define ITEM_PEWTER_CRUNCHIES           (VANILLA_ITEM_START + 30 )
#define ITEM_RAGE_CANDY_BAR             (VANILLA_ITEM_START + 31 )
#define ITEM_RAGECANDYBAR ITEM_RAGE_CANDY_BAR // Pre-Gen VI name
#define ITEM_LAVA_COOKIE                (VANILLA_ITEM_START + 32 )
#define ITEM_OLD_GATEAU                 (VANILLA_ITEM_START + 33 )
#define ITEM_CASTELIACONE               (VANILLA_ITEM_START + 34 )
#define ITEM_LUMIOSE_GALETTE            (VANILLA_ITEM_START + 35 )
#define ITEM_SHALOUR_SABLE              (VANILLA_ITEM_START + 36 )
#define ITEM_BIG_MALASADA               (VANILLA_ITEM_START + 37 )
// Vitamins
#define ITEM_HP_UP                      (VANILLA_ITEM_START + 38 )
#define ITEM_PROTEIN                    (VANILLA_ITEM_START + 39 )
#define ITEM_IRON                       (VANILLA_ITEM_START + 40 )
#define ITEM_CALCIUM                    (VANILLA_ITEM_START + 41 )
#define ITEM_ZINC                       (VANILLA_ITEM_START + 42 )
#define ITEM_CARBOS                     (VANILLA_ITEM_START + 43 )
#define ITEM_PP_UP                      (VANILLA_ITEM_START + 44 )
#define ITEM_PP_MAX                     (VANILLA_ITEM_START + 45 )
// EV Feathers
#define ITEM_HEALTH_FEATHER             (VANILLA_ITEM_START + 46 )
#define ITEM_HEALTH_WING                ITEM_HEALTH_FEATHER // Pre-Gen VIII name
#define ITEM_MUSCLE_FEATHER             (VANILLA_ITEM_START + 47 )
#define ITEM_MUSCLE_WING                ITEM_MUSCLE_FEATHER // Pre-Gen VIII name
#define ITEM_RESIST_FEATHER             (VANILLA_ITEM_START + 48 )
#define ITEM_RESIST_WING                ITEM_RESIST_FEATHER // Pre-Gen VIII name
#define ITEM_GENIUS_FEATHER             (VANILLA_ITEM_START + 49 )
#define ITEM_GENIUS_WING                ITEM_GENIUS_FEATHER // Pre-Gen VIII name
#define ITEM_CLEVER_FEATHER             (VANILLA_ITEM_START + 50 )
#define ITEM_CLEVER_WING                ITEM_CLEVER_FEATHER // Pre-Gen VIII name
#define ITEM_SWIFT_FEATHER              (VANILLA_ITEM_START + 51 )
#define ITEM_SWIFT_WING                 ITEM_SWIFT_FEATHER // Pre-Gen VIII name
// Mints
#define ITEM_LONELY_MINT                (VANILLA_ITEM_START + 52 )
#define ITEM_ADAMANT_MINT               (VANILLA_ITEM_START + 53 )
#define ITEM_NAUGHTY_MINT               (VANILLA_ITEM_START + 54 )
#define ITEM_BRAVE_MINT                 (VANILLA_ITEM_START + 55 )
#define ITEM_BOLD_MINT                  (VANILLA_ITEM_START + 56 )
#define ITEM_IMPISH_MINT                (VANILLA_ITEM_START + 57 )
#define ITEM_LAX_MINT                   (VANILLA_ITEM_START + 58 )
#define ITEM_RELAXED_MINT               (VANILLA_ITEM_START + 59 )
#define ITEM_MODEST_MINT                (VANILLA_ITEM_START + 60 )
#define ITEM_MILD_MINT                  (VANILLA_ITEM_START + 61 )
#define ITEM_RASH_MINT                  (VANILLA_ITEM_START + 62 )
#define ITEM_QUIET_MINT                 (VANILLA_ITEM_START + 63 )
#define ITEM_CALM_MINT                  (VANILLA_ITEM_START + 64 )
#define ITEM_GENTLE_MINT                (VANILLA_ITEM_START + 65 )
#define ITEM_CAREFUL_MINT               (VANILLA_ITEM_START + 66 )
#define ITEM_SASSY_MINT                 (VANILLA_ITEM_START + 67 )
#define ITEM_TIMID_MINT                 (VANILLA_ITEM_START + 68 )
#define ITEM_HASTY_MINT                 (VANILLA_ITEM_START + 69 )
#define ITEM_JOLLY_MINT                 (VANILLA_ITEM_START + 70 )
#define ITEM_NAIVE_MINT                 (VANILLA_ITEM_START + 71 )
#define ITEM_SERIOUS_MINT               (VANILLA_ITEM_START + 72 )
// Candy  
#define ITEM_RARE_CANDY                 (VANILLA_ITEM_START + 73 )
#define ITEM_EXP_CANDY_XS               (VANILLA_ITEM_START + 74 )
#define ITEM_EXP_CANDY_S                (VANILLA_ITEM_START + 75 )
#define ITEM_EXP_CANDY_M                (VANILLA_ITEM_START + 76 )
#define ITEM_EXP_CANDY_L                (VANILLA_ITEM_START + 77 )
#define ITEM_EXP_CANDY_XL               (VANILLA_ITEM_START + 78 )
#define ITEM_DYNAMAX_CANDY              (VANILLA_ITEM_START + 79 )
// Medicinal  
#define ITEM_BLUE_FLUTE                 (VANILLA_ITEM_START + 80 )
#define ITEM_YELLOW_FLUTE               (VANILLA_ITEM_START + 81 )
#define ITEM_RED_FLUTE                  (VANILLA_ITEM_START + 82 )
// Encounter-modifying Flutes
#define ITEM_BLACK_FLUTE                (VANILLA_ITEM_START + 83 )
#define ITEM_WHITE_FLUTE                (VANILLA_ITEM_START + 84 )
// Encounter Modifiers 
#define ITEM_REPEL                      (VANILLA_ITEM_START + 85 )
#define ITEM_SUPER_REPEL                (VANILLA_ITEM_START + 86 )
#define ITEM_MAX_REPEL                  (VANILLA_ITEM_START + 87 )
#define ITEM_LURE                       (VANILLA_ITEM_START + 88 )
#define ITEM_SUPER_LURE                 (VANILLA_ITEM_START + 89 )
#define ITEM_MAX_LURE                   (VANILLA_ITEM_START + 90 )

#define ITEM_ESCAPE_ROPE                (VANILLA_ITEM_START + 91 )
// X Items 
#define ITEM_X_ATTACK                   (VANILLA_ITEM_START + 92 )
#define ITEM_X_DEFENSE                  (VANILLA_ITEM_START + 93 )
#define ITEM_X_DEFEND                   ITEM_X_DEFENSE // Pre-Gen VI name  
#define ITEM_X_SP_ATK                   (VANILLA_ITEM_START + 94 )
#define ITEM_X_SPECIAL                  ITEM_X_SP_ATK // Pre-Gen VI name  
#define ITEM_X_SP_DEF                   (VANILLA_ITEM_START + 95 )
#define ITEM_X_SPEED                    (VANILLA_ITEM_START + 96 )
#define ITEM_X_ACCURACY                 (VANILLA_ITEM_START + 97 )
#define ITEM_DIRE_HIT                   (VANILLA_ITEM_START + 98 )
#define ITEM_GUARD_SPEC                 (VANILLA_ITEM_START + 99 )
// Escape Items 
#define ITEM_POKE_DOLL                  (VANILLA_ITEM_START + 100 )
#define ITEM_FLUFFY_TAIL                (VANILLA_ITEM_START + 101 )
#define ITEM_POKE_TOY                   (VANILLA_ITEM_START + 102 )
  
#define ITEM_MAX_MUSHROOMS              (VANILLA_ITEM_START + 103 )

//	Treasures						
#define	ITEM_BOTTLE_CAP				    (VANILLA_ITEM_START + 104 )
#define	ITEM_GOLD_BOTTLE_CAP		    (VANILLA_ITEM_START + 105 )
#define	ITEM_NUGGET				        (VANILLA_ITEM_START + 106 )
#define	ITEM_BIG_NUGGET				    (VANILLA_ITEM_START + 107 )
#define	ITEM_TINY_MUSHROOM				(VANILLA_ITEM_START + 108 )
#define	ITEM_TINYMUSHROOM	            ITEM_TINY_MUSHROOM	//	Pre-Gen	VI	name			
#define	ITEM_BIG_MUSHROOM				(VANILLA_ITEM_START + 109 )
#define	ITEM_BALM_MUSHROOM				(VANILLA_ITEM_START + 110 )
#define	ITEM_BALMMUSHROOM	            ITEM_BALM_MUSHROOM	//	Pre-Gen	VI	name			
#define	ITEM_PEARL				        (VANILLA_ITEM_START + 111 )
#define	ITEM_BIG_PEARL				    (VANILLA_ITEM_START + 112 )
#define	ITEM_PEARL_STRING				(VANILLA_ITEM_START + 113 )
#define	ITEM_STARDUST				    (VANILLA_ITEM_START + 114 )
#define	ITEM_STAR_PIECE				    (VANILLA_ITEM_START + 115 )
#define	ITEM_COMET_SHARD				(VANILLA_ITEM_START + 116 )
#define	ITEM_SHOAL_SALT				    (VANILLA_ITEM_START + 117 )
#define	ITEM_SHOAL_SHELL				(VANILLA_ITEM_START + 118 )
#define	ITEM_RED_SHARD				    (VANILLA_ITEM_START + 119 )
#define	ITEM_BLUE_SHARD				    (VANILLA_ITEM_START + 120 )
#define	ITEM_YELLOW_SHARD				(VANILLA_ITEM_START + 121 )
#define	ITEM_GREEN_SHARD				(VANILLA_ITEM_START + 122 )
#define	ITEM_HEART_SCALE				(VANILLA_ITEM_START + 123 )
#define	ITEM_HONEY				        (VANILLA_ITEM_START + 124 )
#define	ITEM_RARE_BONE				    (VANILLA_ITEM_START + 125 )
#define	ITEM_ODD_KEYSTONE				(VANILLA_ITEM_START + 126 )
#define	ITEM_PRETTY_FEATHER				(VANILLA_ITEM_START + 127 )
#define	ITEM_PRETTY_WING	            ITEM_PRETTY_FEATHER	//	Pre-Gen	VIII	name			
#define	ITEM_RELIC_COPPER				(VANILLA_ITEM_START + 128 )
#define	ITEM_RELIC_SILVER				(VANILLA_ITEM_START + 129 )
#define	ITEM_RELIC_GOLD				    (VANILLA_ITEM_START + 130 )
#define	ITEM_RELIC_VASE				    (VANILLA_ITEM_START + 131 )
#define	ITEM_RELIC_BAND				    (VANILLA_ITEM_START + 132 )
#define	ITEM_RELIC_STATUE				(VANILLA_ITEM_START + 133 )
#define	ITEM_RELIC_CROWN				(VANILLA_ITEM_START + 134 )
#define	ITEM_STRANGE_SOUVENIR		    (VANILLA_ITEM_START + 135 )
							
//	Fossils						
#define	ITEM_HELIX_FOSSIL				(VANILLA_ITEM_START + 136 )
#define	ITEM_DOME_FOSSIL				(VANILLA_ITEM_START + 137 )
#define	ITEM_OLD_AMBER				    (VANILLA_ITEM_START + 138 )
#define	ITEM_ROOT_FOSSIL				(VANILLA_ITEM_START + 139 )
#define	ITEM_CLAW_FOSSIL				(VANILLA_ITEM_START + 140 )
#define	ITEM_ARMOR_FOSSIL				(VANILLA_ITEM_START + 141 )
#define	ITEM_SKULL_FOSSIL				(VANILLA_ITEM_START + 142 )
#define	ITEM_COVER_FOSSIL				(VANILLA_ITEM_START + 143 )
#define	ITEM_PLUME_FOSSIL				(VANILLA_ITEM_START + 144 )
#define	ITEM_JAW_FOSSIL				    (VANILLA_ITEM_START + 145 )
#define	ITEM_SAIL_FOSSIL				(VANILLA_ITEM_START + 146 )
#define	ITEM_FOSSILIZED_BIRD		    (VANILLA_ITEM_START + 147 )
#define	ITEM_FOSSILIZED_FISH		    (VANILLA_ITEM_START + 148 )
#define	ITEM_FOSSILIZED_DRAKE		    (VANILLA_ITEM_START + 149 )
#define	ITEM_FOSSILIZED_DINO		    (VANILLA_ITEM_START + 150 )
							
//	Mulch						
#define	ITEM_GROWTH_MULCH				(VANILLA_ITEM_START + 151 )
#define	ITEM_DAMP_MULCH				    (VANILLA_ITEM_START + 152 )
#define	ITEM_STABLE_MULCH				(VANILLA_ITEM_START + 153 )
#define	ITEM_GOOEY_MULCH				(VANILLA_ITEM_START + 154 )
#define	ITEM_RICH_MULCH				    (VANILLA_ITEM_START + 155 )
#define	ITEM_SURPRISE_MULCH				(VANILLA_ITEM_START + 156 )
#define	ITEM_BOOST_MULCH				(VANILLA_ITEM_START + 157 )
#define	ITEM_AMAZE_MULCH				(VANILLA_ITEM_START + 158 )
							
//	Apricorns						
#define	ITEM_RED_APRICORN				(VANILLA_ITEM_START + 159 )
#define	ITEM_BLUE_APRICORN				(VANILLA_ITEM_START + 160 )
#define	ITEM_BLU_APRICORN	            ITEM_BLUE_APRICORN	//	Pre-Gen	VI	name			
#define	ITEM_YELLOW_APRICORN		    (VANILLA_ITEM_START + 161 )
#define	ITEM_YLW_APRICORN	            ITEM_YELLOW_APRICORN	//	Pre-Gen	VI	name			
#define	ITEM_GREEN_APRICORN				(VANILLA_ITEM_START + 162 )
#define	ITEM_GRN_APRICORN	            ITEM_GREEN_APRICORN	//	Pre-Gen	VI	name			
#define	ITEM_PINK_APRICORN				(VANILLA_ITEM_START + 163 )
#define	ITEM_PNK_APRICORN	            ITEM_PINK_APRICORN	//	Pre-Gen	VI	name			
#define	ITEM_WHITE_APRICORN				(VANILLA_ITEM_START + 164 )
#define	ITEM_WHT_APRICORN	            ITEM_WHITE_APRICORN	//	Pre-Gen	VI	name			
#define	ITEM_BLACK_APRICORN				(VANILLA_ITEM_START + 165 )
#define	ITEM_BLK_APRICORN	            ITEM_BLACK_APRICORN	//	Pre-Gen	VI	name			
							
#define	ITEM_WISHING_PIECE				(VANILLA_ITEM_START + 166 )
#define	ITEM_GALARICA_TWIG				(VANILLA_ITEM_START + 167 )
#define	ITEM_ARMORITE_ORE				(VANILLA_ITEM_START + 168 )
#define	ITEM_DYNITE_ORE				    (VANILLA_ITEM_START + 169 )
							
//	Mail						
#define	ITEM_ORANGE_MAIL				(VANILLA_ITEM_START + 170 )
#define	ITEM_HARBOR_MAIL				(VANILLA_ITEM_START + 171 )
#define	ITEM_GLITTER_MAIL				(VANILLA_ITEM_START + 172 )
#define	ITEM_MECH_MAIL				    (VANILLA_ITEM_START + 173 )
#define	ITEM_WOOD_MAIL				    (VANILLA_ITEM_START + 174 )
#define	ITEM_WAVE_MAIL				    (VANILLA_ITEM_START + 175 )
#define	ITEM_BEAD_MAIL				    (VANILLA_ITEM_START + 176 )
#define	ITEM_SHADOW_MAIL				(VANILLA_ITEM_START + 177 )
#define	ITEM_TROPIC_MAIL				(VANILLA_ITEM_START + 178 )
#define	ITEM_DREAM_MAIL				    (VANILLA_ITEM_START + 179 )
#define	ITEM_FAB_MAIL				    (VANILLA_ITEM_START + 180 )
#define	ITEM_RETRO_MAIL				    (VANILLA_ITEM_START + 181 )
							
#define	FIRST_MAIL_INDEX	            ITEM_ORANGE_MAIL					
							
//	Evolution	Items					
#define	ITEM_FIRE_STONE				    (VANILLA_ITEM_START + 182 )
#define	ITEM_WATER_STONE				(VANILLA_ITEM_START + 183 )
#define	ITEM_THUNDER_STONE				(VANILLA_ITEM_START + 184 )
#define	ITEM_THUNDERSTONE	            ITEM_THUNDER_STONE	//	Pre-Gen	VI	name			
#define	ITEM_LEAF_STONE				    (VANILLA_ITEM_START + 185 )
#define	ITEM_ICE_STONE				    (VANILLA_ITEM_START + 186 )
#define	ITEM_SUN_STONE				    (VANILLA_ITEM_START + 187 )
#define	ITEM_MOON_STONE				    (VANILLA_ITEM_START + 188 )
#define	ITEM_SHINY_STONE				(VANILLA_ITEM_START + 189 )
#define	ITEM_DUSK_STONE				    (VANILLA_ITEM_START + 190 )
#define	ITEM_DAWN_STONE				    (VANILLA_ITEM_START + 191 )
#define	ITEM_SWEET_APPLE				(VANILLA_ITEM_START + 192 )
#define	ITEM_TART_APPLE				    (VANILLA_ITEM_START + 193 )
#define	ITEM_CRACKED_POT				(VANILLA_ITEM_START + 194 )
#define	ITEM_CHIPPED_POT				(VANILLA_ITEM_START + 195 )
#define	ITEM_GALARICA_CUFF				(VANILLA_ITEM_START + 196 )
#define	ITEM_GALARICA_WREATH	        (VANILLA_ITEM_START + 197 )
#define	ITEM_DRAGON_SCALE				(VANILLA_ITEM_START + 198 )
#define	ITEM_UPGRADE				    (VANILLA_ITEM_START + 199 )
#define	ITEM_UP_GRADE	                ITEM_UPGRADE	//	Pre-Gen	VIII	name			
#define	ITEM_PROTECTOR				    (VANILLA_ITEM_START + 200 )
#define	ITEM_ELECTIRIZER				(VANILLA_ITEM_START + 201 )
#define	ITEM_MAGMARIZER				    (VANILLA_ITEM_START + 202 )
#define	ITEM_DUBIOUS_DISC				(VANILLA_ITEM_START + 203 )
#define	ITEM_REAPER_CLOTH				(VANILLA_ITEM_START + 204 )
#define	ITEM_PRISM_SCALE				(VANILLA_ITEM_START + 205 )
#define	ITEM_WHIPPED_DREAM				(VANILLA_ITEM_START + 206 )
#define	ITEM_SACHET				        (VANILLA_ITEM_START + 207 )
#define	ITEM_OVAL_STONE				    (VANILLA_ITEM_START + 208 )
#define	ITEM_STRAWBERRY_SWEET		    (VANILLA_ITEM_START + 209 )
#define	ITEM_LOVE_SWEET				    (VANILLA_ITEM_START + 210 )
#define	ITEM_BERRY_SWEET				(VANILLA_ITEM_START + 211 )
#define	ITEM_CLOVER_SWEET				(VANILLA_ITEM_START + 212 )
#define	ITEM_FLOWER_SWEET				(VANILLA_ITEM_START + 213 )
#define	ITEM_STAR_SWEET				    (VANILLA_ITEM_START + 214 )
#define	ITEM_RIBBON_SWEET				(VANILLA_ITEM_START + 215 )
							
#define	ITEM_EVERSTONE				(VANILLA_ITEM_START + 216 )
							
//	Nectars						
#define	ITEM_RED_NECTAR				(VANILLA_ITEM_START + 217 )
#define	ITEM_YELLOW_NECTAR				(VANILLA_ITEM_START + 218 )
#define	ITEM_PINK_NECTAR				(VANILLA_ITEM_START + 219 )
#define	ITEM_PURPLE_NECTAR				(VANILLA_ITEM_START + 220 )
							
//	Plates						
#define	ITEM_FLAME_PLATE				(VANILLA_ITEM_START + 221 )
#define	ITEM_SPLASH_PLATE				(VANILLA_ITEM_START + 222 )
#define	ITEM_ZAP_PLATE				(VANILLA_ITEM_START + 223 )
#define	ITEM_MEADOW_PLATE				(VANILLA_ITEM_START + 224 )
#define	ITEM_ICICLE_PLATE				(VANILLA_ITEM_START + 225 )
#define	ITEM_FIST_PLATE				(VANILLA_ITEM_START + 226 )
#define	ITEM_TOXIC_PLATE				(VANILLA_ITEM_START + 227 )
#define	ITEM_EARTH_PLATE				(VANILLA_ITEM_START + 228 )
#define	ITEM_SKY_PLATE				(VANILLA_ITEM_START + 229 )
#define	ITEM_MIND_PLATE				(VANILLA_ITEM_START + 230 )
#define	ITEM_INSECT_PLATE				(VANILLA_ITEM_START + 231 )
#define	ITEM_STONE_PLATE				(VANILLA_ITEM_START + 232 )
#define	ITEM_SPOOKY_PLATE				(VANILLA_ITEM_START + 233 )
#define	ITEM_DRACO_PLATE				(VANILLA_ITEM_START + 234 )
#define	ITEM_DREAD_PLATE				(VANILLA_ITEM_START + 235 )
#define	ITEM_IRON_PLATE				(VANILLA_ITEM_START + 236 )
#define	ITEM_PIXIE_PLATE				(VANILLA_ITEM_START + 237 )
							
//	Drives						
#define	ITEM_DOUSE_DRIVE				(VANILLA_ITEM_START + 238 )
#define	ITEM_SHOCK_DRIVE				(VANILLA_ITEM_START + 239 )
#define	ITEM_BURN_DRIVE				(VANILLA_ITEM_START + 240 )
#define	ITEM_CHILL_DRIVE				(VANILLA_ITEM_START + 241 )
							
//	Memories						
#define	ITEM_FIRE_MEMORY				(VANILLA_ITEM_START + 242 )
#define	ITEM_WATER_MEMORY				(VANILLA_ITEM_START + 243 )
#define	ITEM_ELECTRIC_MEMORY				(VANILLA_ITEM_START + 244 )
#define	ITEM_GRASS_MEMORY				(VANILLA_ITEM_START + 245 )
#define	ITEM_ICE_MEMORY				(VANILLA_ITEM_START + 246 )
#define	ITEM_FIGHTING_MEMORY				(VANILLA_ITEM_START + 247 )
#define	ITEM_POISON_MEMORY				(VANILLA_ITEM_START + 248 )
#define	ITEM_GROUND_MEMORY				(VANILLA_ITEM_START + 249 )
#define	ITEM_FLYING_MEMORY				(VANILLA_ITEM_START + 250 )
#define	ITEM_PSYCHIC_MEMORY				(VANILLA_ITEM_START + 251 )
#define	ITEM_BUG_MEMORY				(VANILLA_ITEM_START + 252 )
#define	ITEM_ROCK_MEMORY				(VANILLA_ITEM_START + 253 )
#define	ITEM_GHOST_MEMORY				(VANILLA_ITEM_START + 254 )
#define	ITEM_DRAGON_MEMORY				(VANILLA_ITEM_START + 255 )
#define	ITEM_DARK_MEMORY				(VANILLA_ITEM_START + 256 )
#define	ITEM_STEEL_MEMORY				(VANILLA_ITEM_START + 257 )
#define	ITEM_FAIRY_MEMORY				(VANILLA_ITEM_START + 258 )
							
#define	ITEM_RUSTED_SWORD				(VANILLA_ITEM_START + 259 )
#define	ITEM_RUSTED_SHIELD				(VANILLA_ITEM_START + 260 )
							
//	Colored	Orbs					
#define	ITEM_RED_ORB				(VANILLA_ITEM_START + 261 )
#define	ITEM_BLUE_ORB				(VANILLA_ITEM_START + 262 )
							
//	Mega	Stones					
#define	ITEM_VENUSAURITE				(VANILLA_ITEM_START + 263 )
#define	ITEM_CHARIZARDITE_X				(VANILLA_ITEM_START + 264 )
#define	ITEM_CHARIZARDITE_Y				(VANILLA_ITEM_START + 265 )
#define	ITEM_BLASTOISINITE				(VANILLA_ITEM_START + 266 )
#define	ITEM_BEEDRILLITE				(VANILLA_ITEM_START + 267 )
#define	ITEM_PIDGEOTITE				(VANILLA_ITEM_START + 268 )
#define	ITEM_ALAKAZITE				(VANILLA_ITEM_START + 269 )
#define	ITEM_SLOWBRONITE				(VANILLA_ITEM_START + 270 )
#define	ITEM_GENGARITE				(VANILLA_ITEM_START + 271 )
#define	ITEM_KANGASKHANITE				(VANILLA_ITEM_START + 272 )
#define	ITEM_PINSIRITE				(VANILLA_ITEM_START + 273 )
#define	ITEM_GYARADOSITE				(VANILLA_ITEM_START + 274 )
#define	ITEM_AERODACTYLITE				(VANILLA_ITEM_START + 275 )
#define	ITEM_MEWTWONITE_X				(VANILLA_ITEM_START + 276 )
#define	ITEM_MEWTWONITE_Y				(VANILLA_ITEM_START + 277 )
#define	ITEM_AMPHAROSITE				(VANILLA_ITEM_START + 278 )
#define	ITEM_STEELIXITE				(VANILLA_ITEM_START + 279 )
#define	ITEM_SCIZORITE				(VANILLA_ITEM_START + 280 )
#define	ITEM_HERACRONITE				(VANILLA_ITEM_START + 281 )
#define	ITEM_HOUNDOOMINITE				(VANILLA_ITEM_START + 282 )
#define	ITEM_TYRANITARITE				(VANILLA_ITEM_START + 283 )
#define	ITEM_SCEPTILITE				(VANILLA_ITEM_START + 284 )
#define	ITEM_BLAZIKENITE				(VANILLA_ITEM_START + 285 )
#define	ITEM_SWAMPERTITE				(VANILLA_ITEM_START + 286 )
#define	ITEM_GARDEVOIRITE				(VANILLA_ITEM_START + 287 )
#define	ITEM_SABLENITE				(VANILLA_ITEM_START + 288 )
#define	ITEM_MAWILITE				(VANILLA_ITEM_START + 289 )
#define	ITEM_AGGRONITE				(VANILLA_ITEM_START + 290 )
#define	ITEM_MEDICHAMITE				(VANILLA_ITEM_START + 291 )
#define	ITEM_MANECTITE				(VANILLA_ITEM_START + 292 )
#define	ITEM_SHARPEDONITE				(VANILLA_ITEM_START + 293 )
#define	ITEM_CAMERUPTITE				(VANILLA_ITEM_START + 294 )
#define	ITEM_ALTARIANITE				(VANILLA_ITEM_START + 295 )
#define	ITEM_BANETTITE				(VANILLA_ITEM_START + 296 )
#define	ITEM_ABSOLITE				(VANILLA_ITEM_START + 297 )
#define	ITEM_GLALITITE				(VANILLA_ITEM_START + 298 )
#define	ITEM_SALAMENCITE				(VANILLA_ITEM_START + 299 )
#define	ITEM_METAGROSSITE				(VANILLA_ITEM_START + 300 )
#define	ITEM_LATIASITE				(VANILLA_ITEM_START + 301 )
#define	ITEM_LATIOSITE				(VANILLA_ITEM_START + 302 )
#define	ITEM_LOPUNNITE				(VANILLA_ITEM_START + 303 )
#define	ITEM_GARCHOMPITE				(VANILLA_ITEM_START + 304 )
#define	ITEM_LUCARIONITE				(VANILLA_ITEM_START + 305 )
#define	ITEM_ABOMASITE				(VANILLA_ITEM_START + 306 )
#define	ITEM_GALLADITE				(VANILLA_ITEM_START + 307 )
#define	ITEM_AUDINITE				(VANILLA_ITEM_START + 308 )
#define	ITEM_DIANCITE				(VANILLA_ITEM_START + 309 )
							
//	Gems						
#define	ITEM_NORMAL_GEM				(VANILLA_ITEM_START + 310 )
#define	ITEM_FIRE_GEM				(VANILLA_ITEM_START + 311 )
#define	ITEM_WATER_GEM				(VANILLA_ITEM_START + 312 )
#define	ITEM_ELECTRIC_GEM				(VANILLA_ITEM_START + 313 )
#define	ITEM_GRASS_GEM				(VANILLA_ITEM_START + 314 )
#define	ITEM_ICE_GEM				(VANILLA_ITEM_START + 315 )
#define	ITEM_FIGHTING_GEM				(VANILLA_ITEM_START + 316 )
#define	ITEM_POISON_GEM				(VANILLA_ITEM_START + 317 )
#define	ITEM_GROUND_GEM				(VANILLA_ITEM_START + 318 )
#define	ITEM_FLYING_GEM				(VANILLA_ITEM_START + 319 )
#define	ITEM_PSYCHIC_GEM				(VANILLA_ITEM_START + 320 )
#define	ITEM_BUG_GEM				(VANILLA_ITEM_START + 321 )
#define	ITEM_ROCK_GEM				(VANILLA_ITEM_START + 322 )
#define	ITEM_GHOST_GEM				(VANILLA_ITEM_START + 323 )
#define	ITEM_DRAGON_GEM				(VANILLA_ITEM_START + 324 )
#define	ITEM_DARK_GEM				(VANILLA_ITEM_START + 325 )
#define	ITEM_STEEL_GEM				(VANILLA_ITEM_START + 326 )
#define	ITEM_FAIRY_GEM				(VANILLA_ITEM_START + 327 )
							
//	Z-Crystals						
#define	ITEM_NORMALIUM_Z				(VANILLA_ITEM_START + 328 )
#define	ITEM_FIRIUM_Z				(VANILLA_ITEM_START + 329 )
#define	ITEM_WATERIUM_Z				(VANILLA_ITEM_START + 330 )
#define	ITEM_ELECTRIUM_Z				(VANILLA_ITEM_START + 331 )
#define	ITEM_GRASSIUM_Z				(VANILLA_ITEM_START + 332 )
#define	ITEM_ICIUM_Z				(VANILLA_ITEM_START + 333 )
#define	ITEM_FIGHTINIUM_Z				(VANILLA_ITEM_START + 334 )
#define	ITEM_POISONIUM_Z				(VANILLA_ITEM_START + 335 )
#define	ITEM_GROUNDIUM_Z				(VANILLA_ITEM_START + 336 )
#define	ITEM_FLYINIUM_Z				(VANILLA_ITEM_START + 337 )
#define	ITEM_PSYCHIUM_Z				(VANILLA_ITEM_START + 338 )
#define	ITEM_BUGINIUM_Z				(VANILLA_ITEM_START + 339 )
#define	ITEM_ROCKIUM_Z				(VANILLA_ITEM_START + 340 )
#define	ITEM_GHOSTIUM_Z				(VANILLA_ITEM_START + 341 )
#define	ITEM_DRAGONIUM_Z				(VANILLA_ITEM_START + 342 )
#define	ITEM_DARKINIUM_Z				(VANILLA_ITEM_START + 343 )
#define	ITEM_STEELIUM_Z				(VANILLA_ITEM_START + 344 )
#define	ITEM_FAIRIUM_Z				(VANILLA_ITEM_START + 345 )
#define	ITEM_PIKANIUM_Z				(VANILLA_ITEM_START + 346 )
#define	ITEM_EEVIUM_Z				(VANILLA_ITEM_START + 347 )
#define	ITEM_SNORLIUM_Z				(VANILLA_ITEM_START + 348 )
#define	ITEM_MEWNIUM_Z				(VANILLA_ITEM_START + 349 )
#define	ITEM_DECIDIUM_Z				(VANILLA_ITEM_START + 350 )
#define	ITEM_INCINIUM_Z				(VANILLA_ITEM_START + 351 )
#define	ITEM_PRIMARIUM_Z				(VANILLA_ITEM_START + 352 )
#define	ITEM_LYCANIUM_Z				(VANILLA_ITEM_START + 353 )
#define	ITEM_MIMIKIUM_Z				(VANILLA_ITEM_START + 354 )
#define	ITEM_KOMMONIUM_Z				(VANILLA_ITEM_START + 355 )
#define	ITEM_TAPUNIUM_Z				(VANILLA_ITEM_START + 356 )
#define	ITEM_SOLGANIUM_Z				(VANILLA_ITEM_START + 357 )
#define	ITEM_LUNALIUM_Z				(VANILLA_ITEM_START + 358 )
#define	ITEM_MARSHADIUM_Z				(VANILLA_ITEM_START + 359 )
#define	ITEM_ALORAICHIUM_Z				(VANILLA_ITEM_START + 360 )
#define	ITEM_PIKASHUNIUM_Z				(VANILLA_ITEM_START + 361 )
#define	ITEM_ULTRANECROZIUM_Z				(VANILLA_ITEM_START + 362 )
							
//	Species-specific	Held	Items				
#define	ITEM_LIGHT_BALL				(VANILLA_ITEM_START + 363 )
#define	ITEM_LEEK				(VANILLA_ITEM_START + 364 )
#define	ITEM_STICK	ITEM_LEEK	//	Pre-Gen	VIII	name			
#define	ITEM_THICK_CLUB				(VANILLA_ITEM_START + 365 )
#define	ITEM_LUCKY_PUNCH				(VANILLA_ITEM_START + 366 )
#define	ITEM_METAL_POWDER				(VANILLA_ITEM_START + 367 )
#define	ITEM_QUICK_POWDER				(VANILLA_ITEM_START + 368 )
#define	ITEM_DEEP_SEA_SCALE				(VANILLA_ITEM_START + 369 )
#define	ITEM_DEEPSEASCALE	ITEM_DEEP_SEA_SCALE	//	Pre-Gen	VI	name			
#define	ITEM_DEEP_SEA_TOOTH				(VANILLA_ITEM_START + 370 )
#define	ITEM_DEEPSEATOOTH	ITEM_DEEP_SEA_TOOTH	//	Pre-Gen	VI	name			
#define	ITEM_SOUL_DEW				(VANILLA_ITEM_START + 371 )
#define	ITEM_ADAMANT_ORB				(VANILLA_ITEM_START + 372 )
#define	ITEM_LUSTROUS_ORB				(VANILLA_ITEM_START + 373 )
#define	ITEM_GRISEOUS_ORB				(VANILLA_ITEM_START + 374 )
							
//	Incenses						
#define	ITEM_SEA_INCENSE				(VANILLA_ITEM_START + 375 )
#define	ITEM_LAX_INCENSE				(VANILLA_ITEM_START + 376 )
#define	ITEM_ODD_INCENSE				(VANILLA_ITEM_START + 377 )
#define	ITEM_ROCK_INCENSE				(VANILLA_ITEM_START + 378 )
#define	ITEM_FULL_INCENSE				(VANILLA_ITEM_START + 379 )
#define	ITEM_WAVE_INCENSE				(VANILLA_ITEM_START + 380 )
#define	ITEM_ROSE_INCENSE				(VANILLA_ITEM_START + 381 )
#define	ITEM_LUCK_INCENSE				(VANILLA_ITEM_START + 382 )
#define	ITEM_PURE_INCENSE				(VANILLA_ITEM_START + 383 )
							
//	Contest	Scarves					
#define	ITEM_RED_SCARF				(VANILLA_ITEM_START + 384 )
#define	ITEM_BLUE_SCARF				(VANILLA_ITEM_START + 385 )
#define	ITEM_PINK_SCARF				(VANILLA_ITEM_START + 386 )
#define	ITEM_GREEN_SCARF				(VANILLA_ITEM_START + 387 )
#define	ITEM_YELLOW_SCARF				(VANILLA_ITEM_START + 388 )
							
//	EV	Gain	Modifiers				
#define	ITEM_MACHO_BRACE				(VANILLA_ITEM_START + 389 )
#define	ITEM_POWER_WEIGHT				(VANILLA_ITEM_START + 390 )
#define	ITEM_POWER_BRACER				(VANILLA_ITEM_START + 391 )
#define	ITEM_POWER_BELT				(VANILLA_ITEM_START + 392 )
#define	ITEM_POWER_LENS				(VANILLA_ITEM_START + 393 )
#define	ITEM_POWER_BAND				(VANILLA_ITEM_START + 394 )
#define	ITEM_POWER_ANKLET				(VANILLA_ITEM_START + 395 )
							
//	Type-boosting	Held	Items				
#define	ITEM_SILK_SCARF				(VANILLA_ITEM_START + 396 )
#define	ITEM_CHARCOAL				(VANILLA_ITEM_START + 397 )
#define	ITEM_MYSTIC_WATER				(VANILLA_ITEM_START + 398 )
#define	ITEM_MAGNET				(VANILLA_ITEM_START + 399 )
#define	ITEM_MIRACLE_SEED				(VANILLA_ITEM_START + 400 )
#define	ITEM_NEVER_MELT_ICE				(VANILLA_ITEM_START + 401 )
#define	ITEM_NEVERMELTICE	ITEM_NEVER_MELT_ICE	//	Pre-Gen	VI	name			
#define	ITEM_BLACK_BELT				(VANILLA_ITEM_START + 402 )
#define	ITEM_BLACKBELT	ITEM_BLACK_BELT	//	Gen	II	name			
#define	ITEM_POISON_BARB				(VANILLA_ITEM_START + 403 )
#define	ITEM_SOFT_SAND				(VANILLA_ITEM_START + 404 )
#define	ITEM_SHARP_BEAK				(VANILLA_ITEM_START + 405 )
#define	ITEM_TWISTED_SPOON				(VANILLA_ITEM_START + 406 )
#define	ITEM_TWISTEDSPOON	ITEM_TWISTED_SPOON	//	Pre-Gen	VI	name			
#define	ITEM_SILVER_POWDER				(VANILLA_ITEM_START + 407 )
#define	ITEM_SILVERPOWDER	ITEM_SILVER_POWDER	//	Pre-Gen	VI	name			
#define	ITEM_HARD_STONE				(VANILLA_ITEM_START + 408 )
#define	ITEM_SPELL_TAG				(VANILLA_ITEM_START + 409 )
#define	ITEM_DRAGON_FANG				(VANILLA_ITEM_START + 410 )
#define	ITEM_BLACK_GLASSES				(VANILLA_ITEM_START + 411 )
#define	ITEM_BLACKGLASSES	ITEM_BLACK_GLASSES	//	Pre-Gen	VI	name			
#define	ITEM_METAL_COAT				(VANILLA_ITEM_START + 412 )
							
//	Choice	Items					
#define	ITEM_CHOICE_BAND				(VANILLA_ITEM_START + 413 )
#define	ITEM_CHOICE_SPECS				(VANILLA_ITEM_START + 414 )
#define	ITEM_CHOICE_SCARF				(VANILLA_ITEM_START + 415 )
							
//	Status	Orbs					
#define	ITEM_FLAME_ORB				(VANILLA_ITEM_START + 416 )
#define	ITEM_TOXIC_ORB				(VANILLA_ITEM_START + 417 )
							
//	Weather	Rocks					
#define	ITEM_DAMP_ROCK				(VANILLA_ITEM_START + 418 )
#define	ITEM_HEAT_ROCK				(VANILLA_ITEM_START + 419 )
#define	ITEM_SMOOTH_ROCK				(VANILLA_ITEM_START + 420 )
#define	ITEM_ICY_ROCK				(VANILLA_ITEM_START + 421 )
							
//	Terrain	Seeds					
#define	ITEM_ELECTRIC_SEED				(VANILLA_ITEM_START + 422 )
#define	ITEM_PSYCHIC_SEED				(VANILLA_ITEM_START + 423 )
#define	ITEM_MISTY_SEED				(VANILLA_ITEM_START + 424 )
#define	ITEM_GRASSY_SEED				(VANILLA_ITEM_START + 425 )
							
//	Type-activated	Stat	Modifiers				
#define	ITEM_ABSORB_BULB				(VANILLA_ITEM_START + 426 )
#define	ITEM_CELL_BATTERY				(VANILLA_ITEM_START + 427 )
#define	ITEM_LUMINOUS_MOSS				(VANILLA_ITEM_START + 428 )
#define	ITEM_SNOWBALL				(VANILLA_ITEM_START + 429 )
							
//	Misc.	Held	Items				
#define	ITEM_BRIGHT_POWDER				(VANILLA_ITEM_START + 430 )
#define	ITEM_BRIGHTPOWDER	ITEM_BRIGHT_POWDER	//	Pre-Gen	VI	name			
#define	ITEM_WHITE_HERB				(VANILLA_ITEM_START + 431 )
#define	ITEM_EXP_SHARE				(VANILLA_ITEM_START + 432 )
#define	ITEM_EXP_ALL	ITEM_EXP_SHARE	//	Gen	I	name			
#define	ITEM_QUICK_CLAW				(VANILLA_ITEM_START + 433 )
#define	ITEM_SOOTHE_BELL				(VANILLA_ITEM_START + 434 )
#define	ITEM_MENTAL_HERB				(VANILLA_ITEM_START + 435 )
#define	ITEM_KINGS_ROCK				(VANILLA_ITEM_START + 436 )
#define	ITEM_AMULET_COIN				(VANILLA_ITEM_START + 437 )
#define	ITEM_CLEANSE_TAG				(VANILLA_ITEM_START + 438 )
#define	ITEM_SMOKE_BALL				(VANILLA_ITEM_START + 439 )
#define	ITEM_FOCUS_BAND				(VANILLA_ITEM_START + 440 )
#define	ITEM_LUCKY_EGG				(VANILLA_ITEM_START + 441 )
#define	ITEM_SCOPE_LENS				(VANILLA_ITEM_START + 442 )
#define	ITEM_LEFTOVERS				(VANILLA_ITEM_START + 443 )
#define	ITEM_SHELL_BELL				(VANILLA_ITEM_START + 444 )
#define	ITEM_WIDE_LENS				(VANILLA_ITEM_START + 445 )
#define	ITEM_MUSCLE_BAND				(VANILLA_ITEM_START + 446 )
#define	ITEM_WISE_GLASSES				(VANILLA_ITEM_START + 447 )
#define	ITEM_EXPERT_BELT				(VANILLA_ITEM_START + 448 )
#define	ITEM_LIGHT_CLAY				(VANILLA_ITEM_START + 449 )
#define	ITEM_LIFE_ORB				(VANILLA_ITEM_START + 450 )
#define	ITEM_POWER_HERB				(VANILLA_ITEM_START + 451 )
#define	ITEM_FOCUS_SASH				(VANILLA_ITEM_START + 452 )
#define	ITEM_ZOOM_LENS				(VANILLA_ITEM_START + 453 )
#define	ITEM_METRONOME				(VANILLA_ITEM_START + 454 )
#define	ITEM_IRON_BALL				(VANILLA_ITEM_START + 455 )
#define	ITEM_LAGGING_TAIL				(VANILLA_ITEM_START + 456 )
#define	ITEM_DESTINY_KNOT				(VANILLA_ITEM_START + 457 )
#define	ITEM_BLACK_SLUDGE				(VANILLA_ITEM_START + 458 )
#define	ITEM_GRIP_CLAW				(VANILLA_ITEM_START + 459 )
#define	ITEM_STICKY_BARB				(VANILLA_ITEM_START + 460 )
#define	ITEM_SHED_SHELL				(VANILLA_ITEM_START + 461 )
#define	ITEM_BIG_ROOT				(VANILLA_ITEM_START + 462 )
#define	ITEM_RAZOR_CLAW				(VANILLA_ITEM_START + 463 )
#define	ITEM_RAZOR_FANG				(VANILLA_ITEM_START + 464 )
#define	ITEM_EVIOLITE				(VANILLA_ITEM_START + 465 )
#define	ITEM_FLOAT_STONE				(VANILLA_ITEM_START + 466 )
#define	ITEM_ROCKY_HELMET				(VANILLA_ITEM_START + 467 )
#define	ITEM_AIR_BALLOON				(VANILLA_ITEM_START + 468 )
#define	ITEM_RED_CARD				(VANILLA_ITEM_START + 469 )
#define	ITEM_RING_TARGET				(VANILLA_ITEM_START + 470 )
#define	ITEM_BINDING_BAND				(VANILLA_ITEM_START + 471 )
#define	ITEM_EJECT_BUTTON				(VANILLA_ITEM_START + 472 )
#define	ITEM_WEAKNESS_POLICY				(VANILLA_ITEM_START + 473 )
#define	ITEM_ASSAULT_VEST				(VANILLA_ITEM_START + 474 )
#define	ITEM_SAFETY_GOGGLES				(VANILLA_ITEM_START + 475 )
#define	ITEM_ADRENALINE_ORB				(VANILLA_ITEM_START + 476 )
#define	ITEM_TERRAIN_EXTENDER				(VANILLA_ITEM_START + 477 )
#define	ITEM_PROTECTIVE_PADS				(VANILLA_ITEM_START + 478 )
#define	ITEM_THROAT_SPRAY				(VANILLA_ITEM_START + 479 )
#define	ITEM_EJECT_PACK				(VANILLA_ITEM_START + 480 )
#define	ITEM_HEAVY_DUTY_BOOTS				(VANILLA_ITEM_START + 481 )
#define	ITEM_BLUNDER_POLICY				(VANILLA_ITEM_START + 482 )
#define	ITEM_ROOM_SERVICE				(VANILLA_ITEM_START + 483 )
#define	ITEM_UTILITY_UMBRELLA				(VANILLA_ITEM_START + 484 )
							
							
//	Charms						
#define	ITEM_OVAL_CHARM				(VANILLA_ITEM_START + 485 )
#define	ITEM_SHINY_CHARM				(VANILLA_ITEM_START + 486 )
#define	ITEM_CATCHING_CHARM				(VANILLA_ITEM_START + 487 )
#define	ITEM_EXP_CHARM				(VANILLA_ITEM_START + 488 )
							
//	Form-changing	Key	Items				
#define	ITEM_ROTOM_CATALOG				(VANILLA_ITEM_START + 489 )
#define	ITEM_GRACIDEA				(VANILLA_ITEM_START + 490 )
#define	ITEM_REVEAL_GLASS				(VANILLA_ITEM_START + 491 )
#define	ITEM_DNA_SPLICERS				(VANILLA_ITEM_START + 492 )
#define	ITEM_ZYGARDE_CUBE				(VANILLA_ITEM_START + 493 )
#define	ITEM_PRISON_BOTTLE				(VANILLA_ITEM_START + 494 )
#define	ITEM_N_SOLARIZER				(VANILLA_ITEM_START + 495 )
#define	ITEM_N_LUNARIZER				(VANILLA_ITEM_START + 496 )
#define	ITEM_REINS_OF_UNITY				(VANILLA_ITEM_START + 497 )
							
//	Battle	Mechanic	Key	Items					
#define	ITEM_MEGA_RING				(VANILLA_ITEM_START + 498 )
#define	ITEM_Z_POWER_RING				(VANILLA_ITEM_START + 499 )
#define	ITEM_DYNAMAX_BAND				(VANILLA_ITEM_START + 500 )
							
//	Misc.	Key	Items				
#define	ITEM_BICYCLE				(VANILLA_ITEM_START + 501 )
#define	ITEM_MACH_BIKE				(VANILLA_ITEM_START + 502 )
#define	ITEM_ACRO_BIKE				(VANILLA_ITEM_START + 503 )
#define	ITEM_OLD_ROD				(VANILLA_ITEM_START + 504 )
#define	ITEM_GOOD_ROD				(VANILLA_ITEM_START + 505 )
#define	ITEM_SUPER_ROD				(VANILLA_ITEM_START + 506 )
#define	ITEM_DOWSING_MACHINE				(VANILLA_ITEM_START + 507 )
#define	ITEM_ITEMFINDER	ITEM_DOWSING_MACHINE	//	Pre-Gen	IV	name			
#define	ITEM_DOWSING_MCHN	ITEM_DOWSING_MACHINE	//	Gen	IV-V	name			
#define	ITEM_TOWN_MAP				(VANILLA_ITEM_START + 508 )
#define	ITEM_VS_SEEKER				(VANILLA_ITEM_START + 509 )
#define	ITEM_TM_CASE				(VANILLA_ITEM_START + 510 )
#define	ITEM_BERRY_POUCH				(VANILLA_ITEM_START + 511 )
#define	ITEM_POKEMON_BOX_LINK				(VANILLA_ITEM_START + 512 )
#define	ITEM_POKEMON_BOX	ITEM_POKEMON_BOX_LINK	//	Pre-Gen	VIII	name			
#define	ITEM_COIN_CASE				(VANILLA_ITEM_START + 513 )
#define	ITEM_POWDER_JAR				(VANILLA_ITEM_START + 514 )
#define	ITEM_WAILMER_PAIL				(VANILLA_ITEM_START + 515 )
#define	ITEM_POKE_RADAR				(VANILLA_ITEM_START + 516 )
#define	ITEM_POKEBLOCK_CASE				(VANILLA_ITEM_START + 517 )
#define	ITEM_SOOT_SACK				(VANILLA_ITEM_START + 518 )
#define	ITEM_POKE_FLUTE				(VANILLA_ITEM_START + 519 )
#define	ITEM_FAME_CHECKER				(VANILLA_ITEM_START + 520 )
#define	ITEM_TEACHY_TV				(VANILLA_ITEM_START + 521 )
							
//	Story	Key	Items				
#define	ITEM_SS_TICKET				(VANILLA_ITEM_START + 522 )
#define	ITEM_EON_TICKET				(VANILLA_ITEM_START + 523 )
#define	ITEM_MYSTIC_TICKET				(VANILLA_ITEM_START + 524 )
#define	ITEM_AURORA_TICKET				(VANILLA_ITEM_START + 525 )
#define	ITEM_OLD_SEA_MAP				(VANILLA_ITEM_START + 526 )
#define	ITEM_LETTER				(VANILLA_ITEM_START + 527 )
#define	ITEM_DEVON_PARTS				(VANILLA_ITEM_START + 528 )
#define	ITEM_DEVON_GOODS	            ITEM_DEVON_PARTS	//	Pre-Gen	VI	name			
#define	ITEM_GO_GOGGLES				(VANILLA_ITEM_START + 529 )
#define	ITEM_DEVON_SCOPE				(VANILLA_ITEM_START + 530 )
#define	ITEM_BASEMENT_KEY				(VANILLA_ITEM_START + 531 )
#define	ITEM_SCANNER				(VANILLA_ITEM_START + 532 )
#define	ITEM_STORAGE_KEY				(VANILLA_ITEM_START + 533 )
#define	ITEM_KEY_TO_ROOM_1				(VANILLA_ITEM_START + 534 )
#define	ITEM_RM_1_KEY	ITEM_KEY_TO_ROOM_1	//	Pre-Gen	VI	name			
#define	ITEM_KEY_TO_ROOM_2				(VANILLA_ITEM_START + 535 )
#define	ITEM_RM_2_KEY	ITEM_KEY_TO_ROOM_2	//	Pre-Gen	VI	name			
#define	ITEM_KEY_TO_ROOM_4				(VANILLA_ITEM_START + 536 )
#define	ITEM_RM_4_KEY	ITEM_KEY_TO_ROOM_4	//	Pre-Gen	VI	name			
#define	ITEM_KEY_TO_ROOM_6				(VANILLA_ITEM_START + 537 )
#define	ITEM_RM_6_KEY	ITEM_KEY_TO_ROOM_6	//	Pre-Gen	VI	name			
#define	ITEM_METEORITE				(VANILLA_ITEM_START + 538 )
#define	ITEM_MAGMA_EMBLEM				(VANILLA_ITEM_START + 539 )
#define	ITEM_CONTEST_PASS				(VANILLA_ITEM_START + 540 )
#define	ITEM_PARCEL				(VANILLA_ITEM_START + 541 )
#define	ITEM_OAKS_PARCEL	ITEM_PARCEL	//	Pre-Gen	IV	name			
#define	ITEM_SECRET_KEY				(VANILLA_ITEM_START + 542 )
#define	ITEM_BIKE_VOUCHER				(VANILLA_ITEM_START + 543 )
#define	ITEM_GOLD_TEETH				(VANILLA_ITEM_START + 544 )
#define	ITEM_CARD_KEY				(VANILLA_ITEM_START + 545 )
#define	ITEM_LIFT_KEY				(VANILLA_ITEM_START + 546 )
#define	ITEM_SILPH_SCOPE				(VANILLA_ITEM_START + 547 )
#define	ITEM_TRI_PASS				(VANILLA_ITEM_START + 548 )
#define	ITEM_RAINBOW_PASS				(VANILLA_ITEM_START + 549 )
#define	ITEM_TEA				(VANILLA_ITEM_START + 550 )
#define	ITEM_RUBY				(VANILLA_ITEM_START + 551 )
#define	ITEM_SAPPHIRE				(VANILLA_ITEM_START + 552 )
							
//	GEN	IX	ITEMS				
#define	ITEM_ABILITY_SHIELD				(VANILLA_ITEM_START + 553 )
#define	ITEM_CLEAR_AMULET				(VANILLA_ITEM_START + 554 )
#define	ITEM_PUNCHING_GLOVE				(VANILLA_ITEM_START + 555 )
#define	ITEM_COVERT_CLOAK				(VANILLA_ITEM_START + 556 )
#define	ITEM_LOADED_DICE				(VANILLA_ITEM_START + 557 )
#define	ITEM_AUSPICIOUS_ARMOR				(VANILLA_ITEM_START + 558 )
#define	ITEM_BOOSTER_ENERGY				(VANILLA_ITEM_START + 559 )
#define	ITEM_BIG_BAMBOO_SHOOT				(VANILLA_ITEM_START + 560 )
#define	ITEM_GIMMIGHOUL_COIN				(VANILLA_ITEM_START + 561 )
#define	ITEM_LEADERS_CREST				(VANILLA_ITEM_START + 562 )
#define	ITEM_MALICIOUS_ARMOR				(VANILLA_ITEM_START + 563 )
#define	ITEM_MIRROR_HERB				(VANILLA_ITEM_START + 564 )
#define	ITEM_SCROLL_OF_DARKNESS				(VANILLA_ITEM_START + 565 )
#define	ITEM_SCROLL_OF_WATERS				(VANILLA_ITEM_START + 566 )
#define	ITEM_TERA_ORB				(VANILLA_ITEM_START + 567 )
#define	ITEM_TINY_BAMBOO_SHOOT				(VANILLA_ITEM_START + 568 )
							
#define	ITEM_BUG_TERA_SHARD				(VANILLA_ITEM_START + 569 )
#define	ITEM_DARK_TERA_SHARD				(VANILLA_ITEM_START + 570 )
#define	ITEM_DRAGON_TERA_SHARD				(VANILLA_ITEM_START + 571 )
#define	ITEM_ELECTRIC_TERA_SHARD				(VANILLA_ITEM_START + 572 )
#define	ITEM_FAIRY_TERA_SHARD				(VANILLA_ITEM_START + 573 )
#define	ITEM_FIGHTING_TERA_SHARD				(VANILLA_ITEM_START + 574 )
#define	ITEM_FIRE_TERA_SHARD				(VANILLA_ITEM_START + 575 )
#define	ITEM_FLYING_TERA_SHARD				(VANILLA_ITEM_START + 576 )
#define	ITEM_GHOST_TERA_SHARD				(VANILLA_ITEM_START + 577 )
#define	ITEM_GRASS_TERA_SHARD				(VANILLA_ITEM_START + 578 )
#define	ITEM_GROUND_TERA_SHARD				(VANILLA_ITEM_START + 579 )
#define	ITEM_ICE_TERA_SHARD				(VANILLA_ITEM_START + 580 )
#define	ITEM_NORMAL_TERA_SHARD				(VANILLA_ITEM_START + 581 )
#define	ITEM_POISON_TERA_SHARD				(VANILLA_ITEM_START + 582 )
#define	ITEM_PSYCHIC_TERA_SHARD				(VANILLA_ITEM_START + 583 )
#define	ITEM_ROCK_TERA_SHARD				(VANILLA_ITEM_START + 584 )
#define	ITEM_STEEL_TERA_SHARD				(VANILLA_ITEM_START + 585 )
#define	ITEM_WATER_TERA_SHARD				(VANILLA_ITEM_START + 586 )
							
#define	ITEM_ADAMANT_CRYSTAL				(VANILLA_ITEM_START + 587 )
#define	ITEM_GRISEOUS_CORE				(VANILLA_ITEM_START + 588 )
#define	ITEM_LUSTROUS_GLOBE				(VANILLA_ITEM_START + 589 )
							
#define	ITEM_BLACK_AUGURITE				(VANILLA_ITEM_START + 590 )
#define	ITEM_LINKING_CORD				(VANILLA_ITEM_START + 591 )
#define	ITEM_PEAT_BLOCK				(VANILLA_ITEM_START + 592 )
#define	ITEM_BERSERK_GENE				(VANILLA_ITEM_START + 593 )
							
#define	ITEM_FAIRY_FEATHER				(VANILLA_ITEM_START + 594 )
#define	ITEM_SYRUPY_APPLE				(VANILLA_ITEM_START + 595 )
#define	ITEM_UNREMARKABLE_TEACUP		    (VANILLA_ITEM_START + 596 )
#define	ITEM_MASTERPIECE_TEACUP				(VANILLA_ITEM_START + 597 )
#define	ITEM_CORNERSTONE_MASK				(VANILLA_ITEM_START + 598 )
#define	ITEM_WELLSPRING_MASK				(VANILLA_ITEM_START + 599 )
#define	ITEM_HEARTHFLAME_MASK				(VANILLA_ITEM_START + 600 )
#define	ITEM_HEALTH_MOCHI				    (VANILLA_ITEM_START + 601 )
#define	ITEM_MUSCLE_MOCHI				    (VANILLA_ITEM_START + 602 )
#define	ITEM_RESIST_MOCHI				    (VANILLA_ITEM_START + 603 )
#define	ITEM_GENIUS_MOCHI				    (VANILLA_ITEM_START + 604 )
#define	ITEM_CLEVER_MOCHI				    (VANILLA_ITEM_START + 605 )
#define	ITEM_SWIFT_MOCHI				    (VANILLA_ITEM_START + 606 )
#define	ITEM_FRESH_START_MOCHI				(VANILLA_ITEM_START + 607 )
#define	ITEM_GLIMMERING_CHARM				(VANILLA_ITEM_START + 608 )
#define ITEM_814                            (VANILLA_ITEM_START + 609 ) // TWV0YWwgQWxsb3k=
#define ITEM_815                            (VANILLA_ITEM_START + 609 ) // U3RlbGxhciBUZXJhIFNoYXJk
// Ability Modifiers
#define ITEM_ABILITY_CAPSULE                (VANILLA_ITEM_START + 610 )
#define ITEM_ABILITY_PATCH                  (VANILLA_ITEM_START + 611 )


#define VANILLA_ITEM_END                    ITEM_ABILITY_PATCH  

#define TM_START                            VANILLA_ITEM_END
// TMs/HMs
#define ITEM_TM01		(TM_START + 1 )
#define ITEM_TM02		(TM_START + 2 )
#define ITEM_TM03		(TM_START + 3 )
#define ITEM_TM04		(TM_START + 4 )
#define ITEM_TM05		(TM_START + 5 )
#define ITEM_TM06		(TM_START + 6 )
#define ITEM_TM07		(TM_START + 7 )
#define ITEM_TM08		(TM_START + 8 )
#define ITEM_TM09		(TM_START + 9 )
#define ITEM_TM10		(TM_START + 10 )
#define ITEM_TM11		(TM_START + 11 )
#define ITEM_TM12		(TM_START + 12 )
#define ITEM_TM13		(TM_START + 13 )
#define ITEM_TM14		(TM_START + 14 )
#define ITEM_TM15		(TM_START + 15 )
#define ITEM_TM16		(TM_START + 16 )
#define ITEM_TM17		(TM_START + 17 )
#define ITEM_TM18		(TM_START + 18 )
#define ITEM_TM19		(TM_START + 19 )
#define ITEM_TM20		(TM_START + 20 )
#define ITEM_TM21		(TM_START + 21 )
#define ITEM_TM22		(TM_START + 22 )
#define ITEM_TM23		(TM_START + 23 )
#define ITEM_TM24		(TM_START + 24 )
#define ITEM_TM25		(TM_START + 25 )
#define ITEM_TM26		(TM_START + 26 )
#define ITEM_TM27		(TM_START + 27 )
#define ITEM_TM28		(TM_START + 28 )
#define ITEM_TM29		(TM_START + 29 )
#define ITEM_TM30		(TM_START + 30 )
#define ITEM_TM31		(TM_START + 31 )
#define ITEM_TM32		(TM_START + 32 )
#define ITEM_TM33		(TM_START + 33 )
#define ITEM_TM34		(TM_START + 34 )
#define ITEM_TM35		(TM_START + 35 )
#define ITEM_TM36		(TM_START + 36 )
#define ITEM_TM37		(TM_START + 37 )
#define ITEM_TM38		(TM_START + 38 )
#define ITEM_TM39		(TM_START + 39 )
#define ITEM_TM40		(TM_START + 40 )
#define ITEM_TM41		(TM_START + 41 )
#define ITEM_TM42		(TM_START + 42 )
#define ITEM_TM43		(TM_START + 43 )
#define ITEM_TM44		(TM_START + 44 )
#define ITEM_TM45		(TM_START + 45 )
#define ITEM_TM46		(TM_START + 46 )
#define ITEM_TM47		(TM_START + 47 )
#define ITEM_TM48		(TM_START + 48 )
#define ITEM_TM49		(TM_START + 49 )
#define ITEM_TM50		(TM_START + 50 )
#define ITEM_TM51		(TM_START + 51 )
#define ITEM_TM52		(TM_START + 52 )
#define ITEM_TM53		(TM_START + 53 )
#define ITEM_TM54		(TM_START + 54 )
#define ITEM_TM55		(TM_START + 55 )
#define ITEM_TM56		(TM_START + 56 )
#define ITEM_TM57		(TM_START + 57 )
#define ITEM_TM58		(TM_START + 58 )
#define ITEM_TM59		(TM_START + 59 )
#define ITEM_TM60		(TM_START + 60 )
#define ITEM_TM61		(TM_START + 61 )
#define ITEM_TM62		(TM_START + 62 )
#define ITEM_TM63		(TM_START + 63 )
#define ITEM_TM64		(TM_START + 64 )
#define ITEM_TM65		(TM_START + 65 )
#define ITEM_TM66		(TM_START + 66 )
#define ITEM_TM67		(TM_START + 67 )
#define ITEM_TM68		(TM_START + 68 )
#define ITEM_TM69		(TM_START + 69 )
#define ITEM_TM70		(TM_START + 70 )
#define ITEM_TM71		(TM_START + 71 )
#define ITEM_TM72		(TM_START + 72 )
#define ITEM_TM73		(TM_START + 73 )
#define ITEM_TM74		(TM_START + 74 )
#define ITEM_TM75		(TM_START + 75 )
#define ITEM_TM76		(TM_START + 76 )
#define ITEM_TM77		(TM_START + 77 )
#define ITEM_TM78		(TM_START + 78 )
#define ITEM_TM79		(TM_START + 79 )
#define ITEM_TM80		(TM_START + 80 )
#define ITEM_TM81		(TM_START + 81 )
#define ITEM_TM82		(TM_START + 82 )
#define ITEM_TM83		(TM_START + 83 )
#define ITEM_TM84		(TM_START + 84 )
#define ITEM_TM85		(TM_START + 85 )
#define ITEM_TM86		(TM_START + 86 )
#define ITEM_TM87		(TM_START + 87 )
#define ITEM_TM88		(TM_START + 88 )
#define ITEM_TM89		(TM_START + 89 )
#define ITEM_TM90		(TM_START + 90 )
#define ITEM_TM91		(TM_START + 91 )
#define ITEM_TM92		(TM_START + 92 )
#define ITEM_TM93		(TM_START + 93 )
#define ITEM_TM94		(TM_START + 94 )
#define ITEM_TM95		(TM_START + 95 )
#define ITEM_TM96		(TM_START + 96 )
#define ITEM_TM97		(TM_START + 97 )
#define ITEM_TM98		(TM_START + 98 )
#define ITEM_TM99		(TM_START + 99 )
#define ITEM_TM100		(TM_START + 100 )
		 
#define ITEM_HM01		(TM_START + 101 )
#define ITEM_HM02		(TM_START + 102 )
#define ITEM_HM03		(TM_START + 103 )
#define ITEM_HM04		(TM_START + 104 )
#define ITEM_HM05		(TM_START + 105 )
#define ITEM_HM06		(TM_START + 106 )
#define ITEM_HM07		(TM_START + 107 )
#define ITEM_HM08		(TM_START + 108 )

#define ITEM_TM01_SUNNY_DAY         ITEM_TM01
#define ITEM_TM02_RAIN_DANCE        ITEM_TM02
#define ITEM_TM03_HAIL              ITEM_TM03
#define ITEM_TM04_SANDSTORM         ITEM_TM04
#define ITEM_TM05_TAILWIND          ITEM_TM05
#define ITEM_TM06_FLAME_CHARGE      ITEM_TM06
#define ITEM_TM07_RAZOR_SHELL       ITEM_TM07
#define ITEM_TM08_SOLAR_BLADE       ITEM_TM08
#define ITEM_TM09_GRASSY_TERRAIN    ITEM_TM09
#define ITEM_TM10_ELECTRIC_TERRAIN  ITEM_TM10
#define ITEM_TM11_PSYCHIC_TERRAIN   ITEM_TM11
#define ITEM_TM12_MISTY_TERRAIN     ITEM_TM12
#define ITEM_TM13_BRINE             ITEM_TM13
#define ITEM_TM14_ENERGY_BALL       ITEM_TM14
#define ITEM_TM15_LAVA_PLUME        ITEM_TM15
#define ITEM_TM16_HURRICANE         ITEM_TM16
#define ITEM_TM17_AERIAL_ACE        ITEM_TM17
#define ITEM_TM18_STEEL_WING        ITEM_TM18
#define ITEM_TM19_VOLT_TACKLE       ITEM_TM19
#define ITEM_TM20_DRAINING_KISS     ITEM_TM20
#define ITEM_TM21_TOXIC             ITEM_TM21
#define ITEM_TM22_SHADOW_BONE       ITEM_TM22
#define ITEM_TM23_BANEFUL_BUNKER    ITEM_TM23
#define ITEM_TM24_U_TURN            ITEM_TM24
#define ITEM_TM25_GUILLOTINE        ITEM_TM25
#define ITEM_TM26_KINGS_SHIELD      ITEM_TM26
#define ITEM_TM27_SACRED_SWORD      ITEM_TM27
#define ITEM_TM28_SWORDS_DANCE      ITEM_TM28
#define ITEM_TM29_SECRET_SWORD      ITEM_TM29
#define ITEM_TM30_RETURN            ITEM_TM30
#define ITEM_TM31_FRUSTRATION       ITEM_TM31
#define ITEM_TM32_FALSE_SWIPE       ITEM_TM32
#define ITEM_TM33_DRAGON_BREATH     ITEM_TM33
#define ITEM_TM34_DRAGON_HAMMER     ITEM_TM34
#define ITEM_TM35_LEECH_LIFE        ITEM_TM35
#define ITEM_TM36_SLACK_OFF         ITEM_TM36
#define ITEM_TM37_THOUSAND_ARROWS   ITEM_TM37
#define ITEM_TM38_ROCK_TOMB         ITEM_TM38
#define ITEM_TM39_REVELATION_DANCE  ITEM_TM39
#define ITEM_TM40_VOLT_SWITCH       ITEM_TM40
#define ITEM_TM41_FLASH_CANNON      ITEM_TM41
#define ITEM_TM42_POLLEN_PUFF       ITEM_TM42
#define ITEM_TM43_PSYCHO_CUT        ITEM_TM43
#define ITEM_TM44_PLAY_ROUGH        ITEM_TM44
#define ITEM_TM45_SPECTRAL_THIEF    ITEM_TM45
#define ITEM_TM46_DRAGON_TAIL       ITEM_TM46
#define ITEM_TM47_LUNAR_DANCE       ITEM_TM47
#define ITEM_TM48_POWER_GEM         ITEM_TM48
#define ITEM_TM49_SNARL             ITEM_TM49
#define ITEM_TM50_POISON_JAB        ITEM_TM50
#define ITEM_TM51_ICICLE_CRASH      ITEM_TM51
#define ITEM_TM52_POWDER            ITEM_TM52
#define ITEM_TM53_ICE_BEAM          ITEM_TM53
#define ITEM_TM54_MUD_BOMB          ITEM_TM54
#define ITEM_TM55_HEX               ITEM_TM55
#define ITEM_TM56_SWITCHEROO        ITEM_TM56
#define ITEM_TM57_PSYSHOCK          ITEM_TM57
#define ITEM_TM58_SLUDGE_WAVE       ITEM_TM58
#define ITEM_TM59_SPIKES            ITEM_TM59
#define ITEM_TM60_BULK_UP           ITEM_TM60
#define ITEM_TM61_PAY_DAY           ITEM_TM61
#define ITEM_TM62_DEFOG             ITEM_TM62
#define ITEM_TM63_TRICK_OR_TREAT    ITEM_TM63
#define ITEM_TM64_REVENGE           ITEM_TM64
#define ITEM_TM65_ICE_HAMMER        ITEM_TM65
#define ITEM_TM66_BRUTAL_SWING      ITEM_TM66

#define ITEM_HM01_CUT ITEM_HM01
#define ITEM_HM02_FLY ITEM_HM02
#define ITEM_HM03_SURF ITEM_HM03
#define ITEM_HM04_STRENGTH ITEM_HM04
#define ITEM_HM05_FLASH ITEM_HM05
#define ITEM_HM06_ROCK_SMASH ITEM_HM06
#define ITEM_HM07_WATERFALL ITEM_HM07
#define ITEM_HM08_DIVE ITEM_HM08

#define TM_END                      ITEM_HM08



#define BERRY_START                 TM_END

// Berries
#if B_CONFUSE_BERRIES_HEAL >= GEN_8
    #define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
    #define CONFUSE_BERRY_HEAL_FRACTION 2
#else
    #define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#if B_CONFUSE_BERRIES_HEAL >= GEN_7
    #define CONFUSE_BERRY_HP_FRACTION 4
#else
    #define CONFUSE_BERRY_HP_FRACTION 2
#endif

#define ITEM_CHERI_BERRY	        (BERRY_START + 1 )
#define ITEM_CHESTO_BERRY	        (BERRY_START + 2 )
#define ITEM_PECHA_BERRY	        (BERRY_START + 3 )
#define ITEM_RAWST_BERRY	        (BERRY_START + 4 )
#define ITEM_ASPEAR_BERRY	        (BERRY_START + 5 )
#define ITEM_LEPPA_BERRY	        (BERRY_START + 6 )
#define ITEM_ORAN_BERRY	            (BERRY_START + 7 )
#define ITEM_PERSIM_BERRY	        (BERRY_START + 8 )
#define ITEM_LUM_BERRY	            (BERRY_START + 9 )
#define ITEM_SITRUS_BERRY	        (BERRY_START + 10 )
#define ITEM_FIGY_BERRY	            (BERRY_START + 11 )
#define ITEM_WIKI_BERRY	            (BERRY_START + 12 )
#define ITEM_MAGO_BERRY	            (BERRY_START + 13 )
#define ITEM_AGUAV_BERRY	        (BERRY_START + 14 )
#define ITEM_IAPAPA_BERRY	        (BERRY_START + 15 )
#define ITEM_RAZZ_BERRY	            (BERRY_START + 16 )
#define ITEM_BLUK_BERRY	            (BERRY_START + 17 )
#define ITEM_NANAB_BERRY	        (BERRY_START + 18 )
#define ITEM_WEPEAR_BERRY	        (BERRY_START + 19 )
#define ITEM_PINAP_BERRY	        (BERRY_START + 20 )
#define ITEM_POMEG_BERRY	        (BERRY_START + 21 )
#define ITEM_KELPSY_BERRY	        (BERRY_START + 22 )
#define ITEM_QUALOT_BERRY	        (BERRY_START + 23 )
#define ITEM_HONDEW_BERRY	        (BERRY_START + 24 )
#define ITEM_GREPA_BERRY	        (BERRY_START + 25 )
#define ITEM_TAMATO_BERRY	        (BERRY_START + 26 )
#define ITEM_CORNN_BERRY	        (BERRY_START + 27 )
#define ITEM_MAGOST_BERRY	        (BERRY_START + 28 )
#define ITEM_RABUTA_BERRY	        (BERRY_START + 29 )
#define ITEM_NOMEL_BERRY	        (BERRY_START + 30 )
#define ITEM_SPELON_BERRY	        (BERRY_START + 31 )
#define ITEM_PAMTRE_BERRY	        (BERRY_START + 32 )
#define ITEM_WATMEL_BERRY	        (BERRY_START + 33 )
#define ITEM_DURIN_BERRY	        (BERRY_START + 34 )
#define ITEM_BELUE_BERRY	        (BERRY_START + 35 )
#define ITEM_CHILAN_BERRY	        (BERRY_START + 36 )
#define ITEM_OCCA_BERRY	            (BERRY_START + 37 )
#define ITEM_PASSHO_BERRY	        (BERRY_START + 38 )
#define ITEM_WACAN_BERRY	        (BERRY_START + 39 )
#define ITEM_RINDO_BERRY	        (BERRY_START + 40 )
#define ITEM_YACHE_BERRY	        (BERRY_START + 41 )
#define ITEM_CHOPLE_BERRY	        (BERRY_START + 42 )
#define ITEM_KEBIA_BERRY	        (BERRY_START + 43 )
#define ITEM_SHUCA_BERRY	        (BERRY_START + 44 )
#define ITEM_COBA_BERRY	            (BERRY_START + 45 )
#define ITEM_PAYAPA_BERRY	        (BERRY_START + 46 )
#define ITEM_TANGA_BERRY	        (BERRY_START + 47 )
#define ITEM_CHARTI_BERRY	        (BERRY_START + 48 )
#define ITEM_KASIB_BERRY	        (BERRY_START + 49 )
#define ITEM_HABAN_BERRY	        (BERRY_START + 50 )
#define ITEM_COLBUR_BERRY	        (BERRY_START + 51 )
#define ITEM_BABIRI_BERRY	        (BERRY_START + 52 )
#define ITEM_ROSELI_BERRY	        (BERRY_START + 53 )
#define ITEM_LIECHI_BERRY	        (BERRY_START + 54 )
#define ITEM_GANLON_BERRY	        (BERRY_START + 55 )
#define ITEM_SALAC_BERRY	        (BERRY_START + 56 )
#define ITEM_PETAYA_BERRY	        (BERRY_START + 57 )
#define ITEM_APICOT_BERRY	        (BERRY_START + 58 )
#define ITEM_LANSAT_BERRY	        (BERRY_START + 59 )
#define ITEM_STARF_BERRY	        (BERRY_START + 60 )
#define ITEM_ENIGMA_BERRY	        (BERRY_START + 61 )
#define ITEM_MICLE_BERRY	        (BERRY_START + 62 )
#define ITEM_CUSTAP_BERRY	        (BERRY_START + 63 )
#define ITEM_JABOCA_BERRY	        (BERRY_START + 64 )
#define ITEM_ROWAP_BERRY	        (BERRY_START + 65 )
#define ITEM_KEE_BERRY	            (BERRY_START + 66 )
#define ITEM_MARANGA_BERRY	        (BERRY_START + 67 )
#define ITEM_ENIGMA_BERRY_E_READER	(BERRY_START + 68 )

#define FIRST_BERRY_INDEX           ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX            ITEM_ENIGMA_BERRY_E_READER

#define BERRY_END                   ITEM_ENIGMA_BERRY_E_READER


#define FINAL_VANILLA_ITEM          BERRY_END

// Start PokeScape
 //Megastones   
#define ITEM_FRAGMENT_OF_JAS		(FINAL_VANILLA_ITEM + 1 )
#define ITEM_MEGASTONE_TZHAAR		(FINAL_VANILLA_ITEM + 2 )
#define ITEM_MEGASTONE_TOKHAAR		(FINAL_VANILLA_ITEM + 3 )
#define ITEM_MEGASTONE_WARRIOR		(FINAL_VANILLA_ITEM + 4 )
#define ITEM_MEGASTONE_SEER		    (FINAL_VANILLA_ITEM + 5 )
#define ITEM_MEGASTONE_ARCHER		(FINAL_VANILLA_ITEM + 6 )
#define ITEM_MEGASTONE_CHAOS		(FINAL_VANILLA_ITEM + 7 )
#define ITEM_MEGASTONE_KALPHITE		(FINAL_VANILLA_ITEM + 8 )
#define ITEM_MEGASTONE_BEAST		(FINAL_VANILLA_ITEM + 9 )

//Evolution Items   
#define ITEM_AIR_RUNE		        (FINAL_VANILLA_ITEM + 10 )
#define ITEM_WATER_RUNE		        (FINAL_VANILLA_ITEM + 11 )
#define ITEM_EARTH_RUNE		        (FINAL_VANILLA_ITEM + 12 )
#define ITEM_FIRE_RUNE		        (FINAL_VANILLA_ITEM + 13 )
#define ITEM_MIND_RUNE		        (FINAL_VANILLA_ITEM + 14 )
#define ITEM_BODY_RUNE		        (FINAL_VANILLA_ITEM + 15 )
#define ITEM_LAW_RUNE		        (FINAL_VANILLA_ITEM + 16 )
#define ITEM_NATURE_RUNE		    (FINAL_VANILLA_ITEM + 17 )
#define ITEM_CHAOS_RUNE		        (FINAL_VANILLA_ITEM + 18 )
#define ITEM_COSMIC_RUNE		    (FINAL_VANILLA_ITEM + 19 )
#define ITEM_BLOOD_RUNE		        (FINAL_VANILLA_ITEM + 20 )
#define ITEM_SOUL_RUNE		        (FINAL_VANILLA_ITEM + 21 )
#define ITEM_DEATH_RUNE		        (FINAL_VANILLA_ITEM + 22 )
#define ITEM_MUD_RUNE		        (FINAL_VANILLA_ITEM + 23 )
#define ITEM_MIST_RUNE		        (FINAL_VANILLA_ITEM + 24 )
#define ITEM_LAVA_RUNE		        (FINAL_VANILLA_ITEM + 25 )
#define ITEM_DUST_RUNE		        (FINAL_VANILLA_ITEM + 26 )
#define ITEM_ASTRAL_RUNE		    (FINAL_VANILLA_ITEM + 27 )
#define ITEM_LIFE_RUNE		        (FINAL_VANILLA_ITEM + 28 )
#define ITEM_SPIRIT_CHARM		    (FINAL_VANILLA_ITEM + 29 )
#define ITEM_LEGENDARY_ITEM		    (FINAL_VANILLA_ITEM + 30 )
#define ITEM_BAD_EGG		        (FINAL_VANILLA_ITEM + 31 )
#define ITEM_SHRIVELLED_DAGANNOTH_CLAW	(FINAL_VANILLA_ITEM + 32 )
#define ITEM_DAGANNOTH_EGG_SHELL	(FINAL_VANILLA_ITEM + 33 )
#define ITEM_DAGANNOTH_SCALE		(FINAL_VANILLA_ITEM + 34 )
#define ITEM_NUMBLING_ROOT		    (FINAL_VANILLA_ITEM + 35 )
#define ITEM_SOCK		            (FINAL_VANILLA_ITEM + 36 )
#define ITEM_TEAR_OF_GUTHIX		    (FINAL_VANILLA_ITEM + 37 )
#define ITEM_VANILLA_MILK		    (FINAL_VANILLA_ITEM + 38 )
#define ITEM_STRAWBERRY_MILK		(FINAL_VANILLA_ITEM + 39 )
#define ITEM_CHOCOLATE_MILK		    (FINAL_VANILLA_ITEM + 40 )

//Medicine   
#define ITEM_BREAD		            (FINAL_VANILLA_ITEM + 41 )
#define ITEM_CAKE		            (FINAL_VANILLA_ITEM + 42 )
#define ITEM_CHOCOLATE_CAKE	        (FINAL_VANILLA_ITEM + 43 )
#define ITEM_CABBAGE		        (FINAL_VANILLA_ITEM + 44 )
#define ITEM_FROGEEL_BURGER		    (FINAL_VANILLA_ITEM + 45 )
#define ITEM_LAMP_ATT		        (FINAL_VANILLA_ITEM + 46 )
#define ITEM_LAMP_DEF		        (FINAL_VANILLA_ITEM + 47 )
#define ITEM_LAMP_HP		        (FINAL_VANILLA_ITEM + 48 )
#define ITEM_LAMP_SPATT		        (FINAL_VANILLA_ITEM + 49 )
#define ITEM_LAMP_SPDEF		        (FINAL_VANILLA_ITEM + 50 )
#define ITEM_LAMP_SPEED		        (FINAL_VANILLA_ITEM + 51 )
#define ITEM_BLUEBERRY_SPECIAL		(FINAL_VANILLA_ITEM + 52 )
#define ITEM_DRUNK_DRAGON		    (FINAL_VANILLA_ITEM + 53 )
#define ITEM_FRUIT_BLAST		    (FINAL_VANILLA_ITEM + 54 )
#define ITEM_PINEAPPLE_PUNCH		(FINAL_VANILLA_ITEM + 55 )
#define ITEM_CHOCOLATE_SUNDAY		(FINAL_VANILLA_ITEM + 56 )
#define ITEM_WIZARDS_BLIZZARD		(FINAL_VANILLA_ITEM + 57 )
#define ITEM_POTION_ATT		        (FINAL_VANILLA_ITEM + 58 )
#define ITEM_POTION_DEF		        (FINAL_VANILLA_ITEM + 59 )
#define ITEM_POTION_ACC		        (FINAL_VANILLA_ITEM + 60 )
#define ITEM_POTION_SPATT		    (FINAL_VANILLA_ITEM + 61 )
#define ITEM_POTION_SPDEF		    (FINAL_VANILLA_ITEM + 62 )
#define ITEM_POTION_SPEED		    (FINAL_VANILLA_ITEM + 63 )
#define ITEM_PRAYER_POTION		    (FINAL_VANILLA_ITEM + 64 )
#define ITEM_SUPER_PRAYER_POTION	(FINAL_VANILLA_ITEM + 65 )
#define ITEM_PURPLE_SWEETS		    (FINAL_VANILLA_ITEM + 66 )
#define ITEM_STAT_BEER		        (FINAL_VANILLA_ITEM + 67 )
#define ITEM_STAT_MOONLIGHT_MEAD	(FINAL_VANILLA_ITEM + 68 )

//Held items   
#define ITEM_PRISMATIC_STAR		    (FINAL_VANILLA_ITEM + 69 )
#define ITEM_RUNE_ESSENCE		    (FINAL_VANILLA_ITEM + 70 )
#define ITEM_RED_SCALE		        (FINAL_VANILLA_ITEM + 71 )
#define ITEM_GREEN_SCALE		    (FINAL_VANILLA_ITEM + 72 )
#define ITEM_BLUE_SCALE		        (FINAL_VANILLA_ITEM + 73 )
#define ITEM_BLACK_SCALE		    (FINAL_VANILLA_ITEM + 74 )
#define ITEM_GODRABBITFOOT		    (FINAL_VANILLA_ITEM + 75 )
#define ITEM_LUCKYRABBITFOOT		(FINAL_VANILLA_ITEM + 76 )
#define ITEM_10TH_SQUAD_SIGIL		(FINAL_VANILLA_ITEM + 77 )
#define ITEM_ABYSSAL_WHIP		    (FINAL_VANILLA_ITEM + 78 )
#define ITEM_AHRIMSTAFF		        (FINAL_VANILLA_ITEM + 79 )
#define ITEM_AKRISAEMACE		    (FINAL_VANILLA_ITEM + 80 )
#define ITEM_ARMA_HELM		        (FINAL_VANILLA_ITEM + 81 )
#define ITEM_BLOODFURY		        (FINAL_VANILLA_ITEM + 82 )
#define ITEM_BLUEBOATER             (FINAL_VANILLA_ITEM + 83 )
#define ITEM_BONECROSSBOW		    (FINAL_VANILLA_ITEM + 84 )
#define ITEM_BRONZEHELMET		    (FINAL_VANILLA_ITEM + 85 )
#define ITEM_DAGONHAIHAT		    (FINAL_VANILLA_ITEM + 86 )
#define ITEM_DFS		            (FINAL_VANILLA_ITEM + 87 )
#define ITEM_DHAROKAXE		        (FINAL_VANILLA_ITEM + 88 )
#define ITEM_DOUBLE_EYEPATCH		(FINAL_VANILLA_ITEM + 89 )
#define ITEM_DRAGON_CLAWS		    (FINAL_VANILLA_ITEM + 90 )
#define ITEM_DRAGON_DAGGER_POISON	(FINAL_VANILLA_ITEM + 91 )
#define ITEM_DRAGON_SCIMITAR		(FINAL_VANILLA_ITEM + 92 )
#define ITEM_DRUID_POUCH		    (FINAL_VANILLA_ITEM + 93 )
#define ITEM_EFFIGY		            (FINAL_VANILLA_ITEM + 94 )
#define ITEM_ELEMENTAL_SHIELD		(FINAL_VANILLA_ITEM + 95 )
#define ITEM_FIGHTER_BOOTS		    (FINAL_VANILLA_ITEM + 96 )
#define ITEM_FIGHTER_TORSO		    (FINAL_VANILLA_ITEM + 97 )
#define ITEM_FIRECAPE		        (FINAL_VANILLA_ITEM + 98 )
#define ITEM_GHOSTSPEAK_AMULET		(FINAL_VANILLA_ITEM + 99 )
#define ITEM_GNOMEGOGGLES		    (FINAL_VANILLA_ITEM + 100 )
#define ITEM_GNOMESCARF		        (FINAL_VANILLA_ITEM + 101 )
#define ITEM_GODSWORD		        (FINAL_VANILLA_ITEM + 102 )
#define ITEM_GRANITE_MAUL		    (FINAL_VANILLA_ITEM + 103 )
#define ITEM_GUTHANSPEAR		    (FINAL_VANILLA_ITEM + 104 )
#define ITEM_HOLY_WRENCH		    (FINAL_VANILLA_ITEM + 105 )
#define ITEM_FANCY_BOOTS		    (FINAL_VANILLA_ITEM + 106 )
#define ITEM_IRONMAN_HELMET		    (FINAL_VANILLA_ITEM + 107 )
#define ITEM_ITEM_GNOMEBALL		    (FINAL_VANILLA_ITEM + 108 )
#define ITEM_KARILCROSSBOW		    (FINAL_VANILLA_ITEM + 109 )
#define ITEM_KERIS		            (FINAL_VANILLA_ITEM + 110 )
#define ITEM_KRAKEN_TENTACLE		(FINAL_VANILLA_ITEM + 111 )
#define ITEM_LINZAHAMMER		    (FINAL_VANILLA_ITEM + 112 )
#define ITEM_ORB_OF_OCULUS		    (FINAL_VANILLA_ITEM + 113 )
#define ITEM_OVERLOAD		        (FINAL_VANILLA_ITEM + 114 )
#define ITEM_RING_OF_LIFE		    (FINAL_VANILLA_ITEM + 115 )
#define ITEM_RING_OF_WEALTH		    (FINAL_VANILLA_ITEM + 116 )
#define ITEM_ROCKCAKE		        (FINAL_VANILLA_ITEM + 117 )
#define ITEM_SARADOMIN_BREW		    (FINAL_VANILLA_ITEM + 118 )
#define ITEM_SICKLE		            (FINAL_VANILLA_ITEM + 119 )
#define ITEM_SNELM		            (FINAL_VANILLA_ITEM + 120 )
#define ITEM_SPIRITSHIELD		    (FINAL_VANILLA_ITEM + 121 )
#define ITEM_SPOTTEDCAPE		    (FINAL_VANILLA_ITEM + 122 )
#define ITEM_STAFF_OF_EARTH		    (FINAL_VANILLA_ITEM + 123 )
#define ITEM_TINDERBOX		        (FINAL_VANILLA_ITEM + 124 )
#define ITEM_TOME_OF_FROST		    (FINAL_VANILLA_ITEM + 125 )
#define ITEM_TORAGHAMMER		    (FINAL_VANILLA_ITEM + 126 )
#define ITEM_VERACFLAIL		        (FINAL_VANILLA_ITEM + 127 )
#define ITEM_WATERSKIN		        (FINAL_VANILLA_ITEM + 128 )
#define ITEM_WIZARDS_HAT		    (FINAL_VANILLA_ITEM + 129 )
#define ITEM_WOOLBALL		        (FINAL_VANILLA_ITEM + 130 )
#define ITEM_PHOENIX_NECKLACE		(FINAL_VANILLA_ITEM + 131 )
#define ITEM_MITHRIL_SCIMITAR		(FINAL_VANILLA_ITEM + 132 )
#define ITEM_SNOW_GLOBE		        (FINAL_VANILLA_ITEM + 133 )

//Key Items
// Start qol_field_moves
#define ITEM_CUT_TOOL		        (FINAL_VANILLA_ITEM + 134 )
#define ITEM_FLY_TOOL		        (FINAL_VANILLA_ITEM + 135 )
#define ITEM_SURF_TOOL		        (FINAL_VANILLA_ITEM + 136 )
#define ITEM_STRENGTH_TOOL		    (FINAL_VANILLA_ITEM + 137 )
#define ITEM_FLASH_TOOL		        (FINAL_VANILLA_ITEM + 138 )
#define ITEM_ROCKSMASH_TOOL		    (FINAL_VANILLA_ITEM + 139 )
#define ITEM_WATERFALL_TOOL		    (FINAL_VANILLA_ITEM + 140 )
#define ITEM_DIVE_TOOL		        (FINAL_VANILLA_ITEM + 141 )
#define ITEM_TELEPORT_TOOL		    (FINAL_VANILLA_ITEM + 142 )
#define ITEM_SWEETSCENT_TOOL		(FINAL_VANILLA_ITEM + 143 )
// End qol_field_moves

#define ITEM_SMALL_NET		        (FINAL_VANILLA_ITEM + 144 )
#define ITEM_BIG_NET		        (FINAL_VANILLA_ITEM + 145 )
#define ITEM_DRAGON_NET		        (FINAL_VANILLA_ITEM + 146 )
#define ITEM_TERRORBIRD_POUCH		(FINAL_VANILLA_ITEM + 147 )
#define ITEM_YAK_POUCH		        (FINAL_VANILLA_ITEM + 148 )
#define ITEM_MAP		            (FINAL_VANILLA_ITEM + 149 )
//#define ITEM_FREE		            (FINAL_VANILLA_ITEM + 150 )
#define ITEM_STAKE		            (FINAL_VANILLA_ITEM + 151 )
#define ITEM_RESEARCHNOTES		    (FINAL_VANILLA_ITEM + 152 )
#define ITEM_DRAGONKIN_NOTES		(FINAL_VANILLA_ITEM + 153 )
#define ITEM_CLIMBINGBOOTS		    (FINAL_VANILLA_ITEM + 154 ) //Rockclimb
#define ITEM_LOVELETTER		        (FINAL_VANILLA_ITEM + 155 )
#define ITEM_TALISMAN_AIR		    (FINAL_VANILLA_ITEM + 156 )
#define ITEM_TALISMAN_CHAOS		    (FINAL_VANILLA_ITEM + 157 )
#define ITEM_TALISMAN_COSMIC		(FINAL_VANILLA_ITEM + 158 )
#define ITEM_TALISMAN_EARTH		    (FINAL_VANILLA_ITEM + 159 )
#define ITEM_TALISMAN_FIRE		    (FINAL_VANILLA_ITEM + 160 )
#define ITEM_TALISMAN_LAW		    (FINAL_VANILLA_ITEM + 161 )
#define ITEM_TALISMAN_MIND		    (FINAL_VANILLA_ITEM + 162 )
#define ITEM_TALISMAN_NATURE		(FINAL_VANILLA_ITEM + 163 )
#define ITEM_TALISMAN_SOUL		    (FINAL_VANILLA_ITEM + 164 )
#define ITEM_TALISMAN_WATER		    (FINAL_VANILLA_ITEM + 165 )

//Pickaxe   
#define ITEM_BRONZEPICKAXE		    (FINAL_VANILLA_ITEM + 166 )
#define ITEM_IRONPICKAXE		    (FINAL_VANILLA_ITEM + 167 )
#define ITEM_STEELPICKAXE		    (FINAL_VANILLA_ITEM + 168 )
#define ITEM_BLACKPICKAXE		    (FINAL_VANILLA_ITEM + 169 )
#define ITEM_MITHRILPICKAXE		    (FINAL_VANILLA_ITEM + 170 )
#define ITEM_ADAMANTPICKAXE		    (FINAL_VANILLA_ITEM + 171 )
#define ITEM_RUNEPICKAXE		    (FINAL_VANILLA_ITEM + 172 )
#define ITEM_DRAGON_PICKAXE         (FINAL_VANILLA_ITEM + 173 )

//Special interaction key items		
#define ITEM_XERIC		            (FINAL_VANILLA_ITEM + 174 )
#define ITEM_ROTTEN_POTATO		    (FINAL_VANILLA_ITEM + 175 )
#define ITEM_SLAYER_GEM		        (FINAL_VANILLA_ITEM + 176 )
#define ITEM_PULSE_CORE		        (FINAL_VANILLA_ITEM + 177 )

//Crafting items   
#define ITEM_COPPER_ORE		        (FINAL_VANILLA_ITEM + 178 )
#define ITEM_TIN_ORE		        (FINAL_VANILLA_ITEM + 179 )
#define ITEM_IRON_ORE		        (FINAL_VANILLA_ITEM + 180 )
#define ITEM_COAL_ORE		        (FINAL_VANILLA_ITEM + 181 )
#define ITEM_MITHRIL_ORE		    (FINAL_VANILLA_ITEM + 182 )
#define ITEM_ADAMANT_ORE		    (FINAL_VANILLA_ITEM + 183 )
#define ITEM_RUNE_ORE		        (FINAL_VANILLA_ITEM + 184 )
#define ITEM_ORIKALKUM_ORE		    (FINAL_VANILLA_ITEM + 185 )
#define ITEM_BANE_ORE		        (FINAL_VANILLA_ITEM + 186 )
#define ITEM_ELEMENTAL_ORE		    (FINAL_VANILLA_ITEM + 187 )
#define ITEM_GRANITE		        (FINAL_VANILLA_ITEM + 188 )
#define ITEM_AUGMENTOR		        (FINAL_VANILLA_ITEM + 189 )
#define ITEM_BARROWS_ITEM		    (FINAL_VANILLA_ITEM + 190 )
#define ITEM_BLACK_MUSHROOM		    (FINAL_VANILLA_ITEM + 191 )
#define ITEM_CRYSTAL_SHARD		    (FINAL_VANILLA_ITEM + 192 )
#define ITEM_HELLFIRE_METAL		    (FINAL_VANILLA_ITEM + 193 )
#define ITEM_MYSTIC_CLOTH		    (FINAL_VANILLA_ITEM + 194 )
#define ITEM_SPLITBARK		        (FINAL_VANILLA_ITEM + 195 )

//Cooking Items   
#define ITEM_EGG		            (FINAL_VANILLA_ITEM + 196 )
#define ITEM_EMPTY_BUCKET		    (FINAL_VANILLA_ITEM + 197 )
#define ITEM_WATER_BUCKET		    (FINAL_VANILLA_ITEM + 198 )
#define ITEM_MILK_BUCKET		    (FINAL_VANILLA_ITEM + 199 )
#define ITEM_WHEAT		            (FINAL_VANILLA_ITEM + 200 )
#define ITEM_EMPTY_POT		        (FINAL_VANILLA_ITEM + 201 )
#define ITEM_FLOUR_POT		        (FINAL_VANILLA_ITEM + 202 )

//Treasure Items   
#define ITEM_FLAX		            (FINAL_VANILLA_ITEM + 203 )
#define ITEM_SPIRIT_SHARD		    (FINAL_VANILLA_ITEM + 204 )
#define ITEM_MINT_CAKE		        (FINAL_VANILLA_ITEM + 205 )
#define ITEM_HWEEN_MASK		        (FINAL_VANILLA_ITEM + 206 )
#define ITEM_SANTA_HAT		        (FINAL_VANILLA_ITEM + 207 )
#define ITEM_PARTY_HAT		        (FINAL_VANILLA_ITEM + 208 )

//Farming Items   
#define ITEM_FARMING_CABBAGE		(FINAL_VANILLA_ITEM + 209 )
#define ITEM_APPLE		            (FINAL_VANILLA_ITEM + 210 )
#define ITEM_BANANA		            (FINAL_VANILLA_ITEM + 211 )
#define ITEM_CADAVABERRY		    (FINAL_VANILLA_ITEM + 212 )
#define ITEM_COCONUT		        (FINAL_VANILLA_ITEM + 213 )
#define ITEM_CORN		            (FINAL_VANILLA_ITEM + 214 )
#define ITEM_GARLIC		            (FINAL_VANILLA_ITEM + 215 )
#define ITEM_GRAPES		            (FINAL_VANILLA_ITEM + 216 )
#define ITEM_JANGERBERRY		    (FINAL_VANILLA_ITEM + 217 )
#define ITEM_LEMON		            (FINAL_VANILLA_ITEM + 218 )
#define ITEM_ONION		            (FINAL_VANILLA_ITEM + 219 )
#define ITEM_ORANGE		            (FINAL_VANILLA_ITEM + 220 )
#define ITEM_PINEAPPLE		        (FINAL_VANILLA_ITEM + 221 )
#define ITEM_POISONIVYBERRY		    (FINAL_VANILLA_ITEM + 222 )
#define ITEM_POTATO		            (FINAL_VANILLA_ITEM + 223 )
#define ITEM_REDBERRY		        (FINAL_VANILLA_ITEM + 224 )
#define ITEM_STRAWBERRY		        (FINAL_VANILLA_ITEM + 225 )
#define ITEM_TOMATO		            (FINAL_VANILLA_ITEM + 226 )
#define ITEM_TURNIP		            (FINAL_VANILLA_ITEM + 227 )
#define ITEM_WATERMELON		        (FINAL_VANILLA_ITEM + 228 )
#define ITEM_WHITEBERRY		        (FINAL_VANILLA_ITEM + 229 )

//Quest Items   
#define ITEM_SUPER_LARGE_EGG		(FINAL_VANILLA_ITEM + 230 )
#define ITEM_TOP_QUALITY_MILK		(FINAL_VANILLA_ITEM + 231 )
#define ITEM_EXTRA_FINE_FLOUR		(FINAL_VANILLA_ITEM + 232 )
#define ITEM_SPECIAL_CAKE		    (FINAL_VANILLA_ITEM + 233 )
#define ITEM_ANCIENT_SHARD		    (FINAL_VANILLA_ITEM + 234 )
#define ITEM_DARK_TOTEM_BASE		(FINAL_VANILLA_ITEM + 235 )
#define ITEM_DARK_TOTEM_MID		    (FINAL_VANILLA_ITEM + 236 )
#define ITEM_DARK_TOTEM_TOP		    (FINAL_VANILLA_ITEM + 237 )
#define ITEM_DARK_TOTEM		        (FINAL_VANILLA_ITEM + 238 )
#define ITEM_FISH_FOOD		        (FINAL_VANILLA_ITEM + 239 )
#define ITEM_FISH_FOOD_POISONED		(FINAL_VANILLA_ITEM + 240 )
#define ITEM_OIL_CAN		        (FINAL_VANILLA_ITEM + 241 )
#define ITEM_PRESSURE_GAUGE		    (FINAL_VANILLA_ITEM + 242 )
#define ITEM_RUBBER_TUBE		    (FINAL_VANILLA_ITEM + 243 )
#define ITEM_MAGICAL_CAGE		    (FINAL_VANILLA_ITEM + 244 )
#define ITEM_SCURRIUS_CHEESE		(FINAL_VANILLA_ITEM + 245 )
#define ITEM_TALISMAN_MYSTERY		(FINAL_VANILLA_ITEM + 246 )
#define ITEM_CRANDOR_MAP_FULL		(FINAL_VANILLA_ITEM + 247 )
#define ITEM_CRANDOR_MAP_PIECE1		(FINAL_VANILLA_ITEM + 248 )
#define ITEM_CRANDOR_MAP_PIECE2		(FINAL_VANILLA_ITEM + 249 )
#define ITEM_CRANDOR_MAP_PIECE3		(FINAL_VANILLA_ITEM + 250 ) 

//Dungeoneering Items   
#define ITEM_DG_BALL_OF_WOOL		(FINAL_VANILLA_ITEM + 251 )
#define ITEM_DG_ROPE		        (FINAL_VANILLA_ITEM + 252 )
#define ITEM_WHISTLE                (FINAL_VANILLA_ITEM + 253 )
#define ITEM_ROPE                   (FINAL_VANILLA_ITEM + 254 )
#define ITEM_REPEL_TEA_1            (FINAL_VANILLA_ITEM + 255 )
#define ITEM_REPEL_TEA_2            (FINAL_VANILLA_ITEM + 256 )
#define ITEM_REPEL_TEA_3            (FINAL_VANILLA_ITEM + 257 )
#define ITEM_RING_OF_KINSHIP		(FINAL_VANILLA_ITEM + 258 )
#define ITEM_TALISMAN_BODY		    (FINAL_VANILLA_ITEM + 259 )

#define ITEM_KEBAB_SANDWICH		    (FINAL_VANILLA_ITEM + 260 )
#define ITEM_BAGUETTE_SANDWICH	    (FINAL_VANILLA_ITEM + 261 )
#define ITEM_DONUT_SANDWICH	        (FINAL_VANILLA_ITEM + 262 )
#define ITEM_BREAD_ROLL_SANDWICH    (FINAL_VANILLA_ITEM + 263 )
#define ITEM_MEAT_PIE_SANDWICH	    (FINAL_VANILLA_ITEM + 264 )
#define ITEM_SQUARE_SANDWICH	    (FINAL_VANILLA_ITEM + 265 )
#define ITEM_TRIANGLE_SANDWICH	    (FINAL_VANILLA_ITEM + 266 )

#define ITEM_BOOK_OF_GUTHIX	        (FINAL_VANILLA_ITEM + 267 )
#define ITEM_BOOK_OF_SARADOMIN	    (FINAL_VANILLA_ITEM + 268 )
#define ITEM_BOOK_OF_ZAMORAK	    (FINAL_VANILLA_ITEM + 269 )
#define ITEM_BOOK_OF_TUMEKEN	    (FINAL_VANILLA_ITEM + 270 )
#define ITEM_BOOK_OF_SEREN	        (FINAL_VANILLA_ITEM + 271 )
#define ITEM_BOOK_OF_ZAROS	        (FINAL_VANILLA_ITEM + 272 )
#define ITEM_BOOK_OF_BANDOS	        (FINAL_VANILLA_ITEM + 273 )
#define ITEM_BOOK_OF_ARMADYL	    (FINAL_VANILLA_ITEM + 274 )

#define ITEM_CHOCOLATE_BAR_SANDWICH (FINAL_VANILLA_ITEM + 275 )
#define ITEM_PAPAYA                 (FINAL_VANILLA_ITEM + 276 )
#define ITEM_DWELLBERRY             (FINAL_VANILLA_ITEM + 277 )
#define ITEM_COFFEEBEAN             (FINAL_VANILLA_ITEM + 278 )
#define ITEM_POISON_IVY             (FINAL_VANILLA_ITEM + 279 )
#define ITEM_BLUEBERRY              (FINAL_VANILLA_ITEM + 280 )
#define ITEM_CHEESE                 (FINAL_VANILLA_ITEM + 281 )
#define ITEM_GLOOP_SOUP             (FINAL_VANILLA_ITEM + 282 )
#define ITEM_FINGERS                (FINAL_VANILLA_ITEM + 283 )
#define ITEM_BAT_SHISH              (FINAL_VANILLA_ITEM + 284 )
#define ITEM_FROGBURGER             (FINAL_VANILLA_ITEM + 285 )
#define ITEM_EEL_SUSHI              (FINAL_VANILLA_ITEM + 286 )
#define ITEM_OUTFIT_BOX             (FINAL_VANILLA_ITEM + 287 )

#define ITEMS_COUNT 1103
#define ITEM_FIELD_ARROW ITEMS_COUNT

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId)(((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId)((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define NUM_TECHNICAL_MACHINES 100
#define NUM_HIDDEN_MACHINES 8

#define MAX_BAG_ITEM_CAPACITY  99
#define MAX_PC_ITEM_CAPACITY   999
#define MAX_BERRY_CAPACITY     999

#define BAG_ITEM_CAPACITY_DIGITS 2
#define BERRY_CAPACITY_DIGITS 3
#define MAX_ITEM_DIGITS BERRY_CAPACITY_DIGITS

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item parameters for EXP Candies
#define EXP_100   1
#define EXP_800   2
#define EXP_3000  3
#define EXP_10000 4
#define EXP_30000 5

// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL             0
#define ITEM_USE_PARTY_MENU       1
#define ITEM_USE_FIELD            2
#define ITEM_USE_PBLOCK_CASE      3
#define ITEM_USE_BAG_MENU         4 // No exit callback, stays in bag menu
#define ITEM_USE_PARTY_MENU_MOVES 5

// Item battle script IDs (need to be non-zero)
#define EFFECT_ITEM_RESTORE_HP              1
#define EFFECT_ITEM_CURE_STATUS             2
#define EFFECT_ITEM_HEAL_AND_CURE_STATUS    3
#define EFFECT_ITEM_INCREASE_STAT           4
#define EFFECT_ITEM_SET_MIST                5
#define EFFECT_ITEM_SET_FOCUS_ENERGY        6
#define EFFECT_ITEM_ESCAPE                  7
#define EFFECT_ITEM_THROW_BALL              8
#define EFFECT_ITEM_REVIVE                  9
#define EFFECT_ITEM_RESTORE_PP              10
#define EFFECT_ITEM_INCREASE_ALL_STATS      11
#define EFFECT_ITEM_HEAL_AND_INCREASE_STAT  12
#define EFFECT_ITEM_HEAL_AND_INCREASE_STAT_TO_MAX  13




// Enigma Berry dummy constant
#define EFFECT_ITEM_ENIGMA_BERRY_EREADER    1

#endif  // GUARD_CONSTANTS_ITEMS_H
