#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY      (0 | (0 << 8))
#define MAP_SLATEPORT_CITY      (1 | (0 << 8))
#define MAP_MAUVILLE_CITY       (2 | (0 << 8))
#define MAP_RUSTBORO_CITY       (3 | (0 << 8))
#define MAP_FORTREE_CITY        (4 | (0 << 8))
#define MAP_LILYCOVE_CITY       (5 | (0 << 8))
#define MAP_MOSSDEEP_CITY       (6 | (0 << 8))
#define MAP_SOOTOPOLIS_CITY     (7 | (0 << 8))
#define MAP_EVER_GRANDE_CITY    (8 | (0 << 8))
#define MAP_LITTLEROOT_TOWN     (9 | (0 << 8))
#define MAP_OLDALE_TOWN         (10 | (0 << 8))
#define MAP_DEWFORD_TOWN        (11 | (0 << 8))
#define MAP_LAVARIDGE_TOWN      (12 | (0 << 8))
#define MAP_FALLARBOR_TOWN      (13 | (0 << 8))
#define MAP_VERDANTURF_TOWN     (14 | (0 << 8))
#define MAP_PACIFIDLOG_TOWN     (15 | (0 << 8))
#define MAP_ROUTE101            (16 | (0 << 8))
#define MAP_ROUTE102            (17 | (0 << 8))
#define MAP_ROUTE103            (18 | (0 << 8))
#define MAP_ROUTE104            (19 | (0 << 8))
#define MAP_ROUTE105            (20 | (0 << 8))
#define MAP_ROUTE106            (21 | (0 << 8))
#define MAP_ROUTE107            (22 | (0 << 8))
#define MAP_ROUTE108            (23 | (0 << 8))
#define MAP_ROUTE109            (24 | (0 << 8))
#define MAP_ROUTE110            (25 | (0 << 8))
#define MAP_ROUTE111            (26 | (0 << 8))
#define MAP_ROUTE112            (27 | (0 << 8))
#define MAP_ROUTE113            (28 | (0 << 8))
#define MAP_ROUTE114            (29 | (0 << 8))
#define MAP_ROUTE115            (30 | (0 << 8))
#define MAP_ROUTE116            (31 | (0 << 8))
#define MAP_ROUTE117            (32 | (0 << 8))
#define MAP_ROUTE118            (33 | (0 << 8))
#define MAP_ROUTE119            (34 | (0 << 8))
#define MAP_ROUTE120            (35 | (0 << 8))
#define MAP_ROUTE121            (36 | (0 << 8))
#define MAP_ROUTE122            (37 | (0 << 8))
#define MAP_ROUTE123            (38 | (0 << 8))
#define MAP_ROUTE124            (39 | (0 << 8))
#define MAP_ROUTE125            (40 | (0 << 8))
#define MAP_ROUTE126            (41 | (0 << 8))
#define MAP_ROUTE127            (42 | (0 << 8))
#define MAP_ROUTE128            (43 | (0 << 8))
#define MAP_ROUTE129            (44 | (0 << 8))
#define MAP_ROUTE130            (45 | (0 << 8))
#define MAP_ROUTE131            (46 | (0 << 8))
#define MAP_ROUTE132            (47 | (0 << 8))
#define MAP_ROUTE133            (48 | (0 << 8))
#define MAP_ROUTE134            (49 | (0 << 8))
#define MAP_UNDERWATER_ROUTE124 (50 | (0 << 8))
#define MAP_UNDERWATER_ROUTE126 (51 | (0 << 8))
#define MAP_UNDERWATER_ROUTE127 (52 | (0 << 8))
#define MAP_UNDERWATER_ROUTE128 (53 | (0 << 8))
#define MAP_UNDERWATER_ROUTE129 (54 | (0 << 8))
#define MAP_UNDERWATER_ROUTE105 (55 | (0 << 8))
#define MAP_UNDERWATER_ROUTE125 (56 | (0 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (1 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (2 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (2 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (2 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (3 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (3 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (3 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (3 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (3 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (3 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (4 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (5 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (5 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (5 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (6 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (6 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (6 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (6 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (6 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (7 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (8 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (8 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (8 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (8 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (8 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (8 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (8 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (9 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (9 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (9 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (9 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (9 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (9 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (9 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (9 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (10 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (10 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (10 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (10 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (10 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (10 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (10 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (10 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (11 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (11 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (11 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (11 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (11 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (11 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (12 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (12 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (12 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (12 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (12 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (12 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (13 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (13 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (13 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (13 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (13 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (13 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (13 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (13 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (13 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (14 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (14 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (14 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (14 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (14 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (14 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (14 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (14 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (14 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (15 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (16 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (17 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (17 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (18 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (18 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (19 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (19 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (20 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (20 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (20 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (21 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (22 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (23 << 8))

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (24 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (24 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (24 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (24 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (24 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (24 << 8))
#define MAP_DESERT_RUINS                             (6 | (24 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (24 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (24 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (24 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (24 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (24 << 8))
#define MAP_MT_CHIMNEY                               (12 | (24 << 8))
#define MAP_JAGGED_PASS                              (13 | (24 << 8))
#define MAP_FIERY_PATH                               (14 | (24 << 8))
#define MAP_MT_PYRE_1F                               (15 | (24 << 8))
#define MAP_MT_PYRE_2F                               (16 | (24 << 8))
#define MAP_MT_PYRE_3F                               (17 | (24 << 8))
#define MAP_MT_PYRE_4F                               (18 | (24 << 8))
#define MAP_MT_PYRE_5F                               (19 | (24 << 8))
#define MAP_MT_PYRE_6F                               (20 | (24 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (24 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (24 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (24 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (24 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (24 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (24 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (24 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (24 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (24 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (24 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (24 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (24 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (24 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (24 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (24 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (24 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (24 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (24 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (24 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (24 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (24 << 8))
#define MAP_ISLAND_CAVE                              (67 | (24 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (24 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (24 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (24 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (24 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (24 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (24 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (24 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (24 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (24 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (24 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (24 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (24 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (24 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (24 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (24 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (24 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (24 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (24 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (24 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (24 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (24 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (24 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (24 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (24 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (24 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (24 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (24 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (24 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (24 << 8))
#define MAP_ALTERING_CAVE                            (106 | (24 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (24 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (25 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (25 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (25 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (25 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (25 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (25 << 8))
#define MAP_TRADE_CENTER             (25 | (25 << 8))
#define MAP_RECORD_CORNER            (26 | (25 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (25 << 8))
#define MAP_CONTEST_HALL             (28 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (25 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (25 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (25 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (25 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (25 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (25 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (25 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (25 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (25 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (25 << 8))
#define MAP_UNION_ROOM               (60 | (25 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (26 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (26 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (26 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (26 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (26 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (26 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (26 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (26 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (26 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (26 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (26 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (26 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (26 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (26 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (26 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (26 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (26 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (26 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (26 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (26 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (26 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (26 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (26 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (26 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (26 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (26 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (26 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (26 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (26 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (26 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (26 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (26 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (26 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (26 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (26 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (26 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (26 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (27 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (27 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (28 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (29 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (29 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (29 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (30 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (31 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (32 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (32 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (32 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (33 << 8))
#define MAP_POKESCAPE_BATTLE_TOWER_BATTLE_ROOM     (1 | (33 << 8))

// gMapGroup_PokescapeOutdoorF2P
#define MAP_TUTORIAL_ISLAND             (0 | (34 << 8))
#define MAP_LUMBRIDGE                   (1 | (34 << 8))
#define MAP_DRAYNOR                     (2 | (34 << 8))
#define MAP_PORT_SARIM                  (3 | (34 << 8))
#define MAP_RIMMINGTON                  (4 | (34 << 8))
#define MAP_FALADOR                     (5 | (34 << 8))
#define MAP_VARROCK                     (6 | (34 << 8))
#define MAP_VARROCK_NORTH               (7 | (34 << 8))
#define MAP_BARBARIAN_VILLAGE           (8 | (34 << 8))
#define MAP_GOBLIN_VILLAGE              (9 | (34 << 8))
#define MAP_DWARVEN_MINES               (10 | (34 << 8))
#define MAP_EDGEVILLE                   (11 | (34 << 8))
#define MAP_AL_KHARID                   (12 | (34 << 8))
#define MAP_MUSA_POINT                  (13 | (34 << 8))
#define MAP_TAVERLEY                    (14 | (34 << 8))
#define MAP_LUMBRIDGE_SWAMP             (15 | (34 << 8))
#define MAP_MILL_LANE_MILL              (16 | (34 << 8))
#define MAP_DRAYNOR_MANOR               (17 | (34 << 8))
#define MAP_MUDSKIPPER_POINT            (18 | (34 << 8))
#define MAP_WIZARDS_TOWER               (19 | (34 << 8))
#define MAP_WILDERNESS_VOLCANO_LOBBY    (20 | (34 << 8))
#define MAP_GRAND_EXCHANGE              (21 | (34 << 8))
#define MAP_VARROCK_GRAND_EXCHANGE_PATH (22 | (34 << 8))

// gMapGroup_PokescapeRoutes
#define MAP_ROUTE1  (0 | (35 << 8))
#define MAP_ROUTE2  (1 | (35 << 8))
#define MAP_ROUTE3  (2 | (35 << 8))
#define MAP_ROUTE4  (3 | (35 << 8))
#define MAP_ROUTE5  (4 | (35 << 8))
#define MAP_ROUTE6  (5 | (35 << 8))
#define MAP_ROUTE7  (6 | (35 << 8))
#define MAP_ROUTE8  (7 | (35 << 8))
#define MAP_ROUTE9  (8 | (35 << 8))
#define MAP_ROUTE10 (9 | (35 << 8))
#define MAP_ROUTE11 (10 | (35 << 8))
#define MAP_ROUTE12 (11 | (35 << 8))
#define MAP_ROUTE13 (12 | (35 << 8))
#define MAP_ROUTE14 (13 | (35 << 8))
#define MAP_ROUTE15 (14 | (35 << 8))
#define MAP_ROUTE16 (15 | (35 << 8))
#define MAP_ROUTE17 (16 | (35 << 8))
#define MAP_ROUTE18 (17 | (35 << 8))
#define MAP_ROUTE19 (18 | (35 << 8))
#define MAP_ROUTE20 (19 | (35 << 8))
#define MAP_ROUTE21 (20 | (35 << 8))
#define MAP_ROUTE22 (21 | (35 << 8))
#define MAP_ROUTE23 (22 | (35 << 8))
#define MAP_ROUTE24 (23 | (35 << 8))
#define MAP_ROUTE25 (24 | (35 << 8))
#define MAP_ROUTE26 (25 | (35 << 8))
#define MAP_ROUTE27 (26 | (35 << 8))
#define MAP_ROUTE28 (27 | (35 << 8))
#define MAP_ROUTE29 (28 | (35 << 8))
#define MAP_ROUTE30 (29 | (35 << 8))
#define MAP_ROUTE31 (30 | (35 << 8))
#define MAP_ROUTE32 (31 | (35 << 8))
#define MAP_ROUTE33 (32 | (35 << 8))
#define MAP_ROUTE34 (33 | (35 << 8))
#define MAP_ROUTE35 (34 | (35 << 8))
#define MAP_ROUTE36 (35 | (35 << 8))
#define MAP_ROUTE37 (36 | (35 << 8))
#define MAP_ROUTE38 (37 | (35 << 8))
#define MAP_ROUTE39 (38 | (35 << 8))
#define MAP_ROUTE40 (39 | (35 << 8))
#define MAP_ROUTE41 (40 | (35 << 8))
#define MAP_ROUTE42 (41 | (35 << 8))
#define MAP_ROUTE43 (42 | (35 << 8))
#define MAP_ROUTE44 (43 | (35 << 8))
#define MAP_ROUTE45 (44 | (35 << 8))
#define MAP_ROUTE46 (45 | (35 << 8))
#define MAP_ROUTE47 (46 | (35 << 8))

// gMapGroup_PokescapeDungeons
#define MAP_TUTORIAL_ISLAND_CAVE        (0 | (36 << 8))
#define MAP_LUMBRIDGE_FOREST            (1 | (36 << 8))
#define MAP_UNDERWATER_LUMBRIDGE        (2 | (36 << 8))
#define MAP_AL_KHARID_MINES_B1F         (3 | (36 << 8))
#define MAP_AL_KHARID_MINES_B2F         (4 | (36 << 8))
#define MAP_KALPHITE_CAVES_B1F          (5 | (36 << 8))
#define MAP_KALPHITE_CAVES_B2F          (6 | (36 << 8))
#define MAP_KALPHITE_CAVES_B3F          (7 | (36 << 8))
#define MAP_KALPHITE_CAVES_B4F          (8 | (36 << 8))
#define MAP_GIANT_MOLE_CAVE             (9 | (36 << 8))
#define MAP_DWARVEN_MINE_B1F            (10 | (36 << 8))
#define MAP_KING_BLACK_DRAGON_LAIR      (11 | (36 << 8))
#define MAP_KING_BLACK_DRAGON_B1F       (12 | (36 << 8))
#define MAP_KING_BLACK_DRAGON_B2F       (13 | (36 << 8))
#define MAP_QUEEN_BLACK_DRAGON_LAIR     (14 | (36 << 8))
#define MAP_LUMBRIDGE_SWAMP_CAVES       (15 | (36 << 8))
#define MAP_LUMBRIDGE_SWAMP_CAVES_JUNA  (16 | (36 << 8))
#define MAP_DWARVEN_MINE_B2F            (17 | (36 << 8))
#define MAP_VORAGO_CAVERN               (18 | (36 << 8))
#define MAP_CHAOS_TUNNELS_B1F           (19 | (36 << 8))
#define MAP_ABYSSAL_REALM_1             (20 | (36 << 8))
#define MAP_ABYSSAL_REALM_2             (21 | (36 << 8))
#define MAP_KARAMJA_VOLCANO_B1F         (22 | (36 << 8))
#define MAP_KARAMJA_VOLCANO_B2F         (23 | (36 << 8))
#define MAP_KARAMJA_VOLCANO_B3F         (24 | (36 << 8))
#define MAP_ASGARNIAN_DUNGEON_B1F       (25 | (36 << 8))
#define MAP_ASGARNIAN_DUNGEON_B2F       (26 | (36 << 8))
#define MAP_ASGARNIAN_DUNGEON_B3F       (27 | (36 << 8))
#define MAP_WILDERNESS_FOREST           (28 | (36 << 8))
#define MAP_CALLISTO_LAIR               (29 | (36 << 8))
#define MAP_AIR_ALTAR                   (30 | (36 << 8))
#define MAP_MIND_ALTAR                  (31 | (36 << 8))
#define MAP_WATER_ALTAR                 (32 | (36 << 8))
#define MAP_FIRE_ALTAR                  (33 | (36 << 8))
#define MAP_EARTH_ALTAR                 (34 | (36 << 8))
#define MAP_BODY_ALTAR                  (35 | (36 << 8))
#define MAP_SHANTAY_PASS                (36 | (36 << 8))
#define MAP_LUMBRIDGE_SWAMP_CAVES_WGS_1 (37 | (36 << 8))
#define MAP_LUMBRIDGE_SWAMP_CAVES_WGS_2 (38 | (36 << 8))
#define MAP_LUMBRIDGE_SWAMP_CAVES_WGS_3 (39 | (36 << 8))
#define MAP_LUMBRIDGE_SWAMP_CAVES_WGS_4 (40 | (36 << 8))

// gMapGroup_PokescapeIndoorTutorialIsland
#define MAP_TUTORIAL_ISLAND_LAB_UP   (0 | (37 << 8))
#define MAP_TUTORIAL_ISLAND_LAB_DOWN (1 | (37 << 8))
#define MAP_TUTORIAL_ISLAND_SHOP     (2 | (37 << 8))
#define MAP_TUTORIAL_ISLAND_CHURCH   (3 | (37 << 8))

// gMapGroup_PokescapeIndoorLumbridge
#define MAP_LUMBRIDGE_HOUSE_BOBS_AXES1 (0 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_BOBS_AXES2 (1 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_1          (2 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_2          (3 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_RODDECK1   (4 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_RODDECK2   (5 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_STARTER1   (6 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_STARTER2   (7 | (38 << 8))
#define MAP_LUMBRIDGE_GENERAL_STORE    (8 | (38 << 8))
#define MAP_LUMBRIDGE_GENERAL_STORE2   (9 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_3          (10 | (38 << 8))
#define MAP_LUMBRIDGE_BANK             (11 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_4          (12 | (38 << 8))
#define MAP_LUMBRIDGE_CASTLE_1         (13 | (38 << 8))
#define MAP_LUMBRIDGE_CASTLE_2         (14 | (38 << 8))
#define MAP_LUMBRIDGE_CASTLE_3         (15 | (38 << 8))
#define MAP_LUMBRIDGE_CASTLE_4         (16 | (38 << 8))
#define MAP_POTTERINGTON_FARM_INTERIOR (17 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_3_2F       (18 | (38 << 8))
#define MAP_LUMBRIDGE_CHURCH           (19 | (38 << 8))
#define MAP_LUMBRIDGE_CASTLE_BASEMENT  (20 | (38 << 8))

// gMapGroup_PokescapeIndoorDraynor
#define MAP_DRAYNOR_HOUSE_MORGAN_1F (0 | (39 << 8))
#define MAP_DRAYNOR_HOUSE_MORGAN_2F (1 | (39 << 8))
#define MAP_DRAYNOR_HOUSE_WO_M_1F   (2 | (39 << 8))
#define MAP_DRAYNOR_HOUSE_WO_M_2F   (3 | (39 << 8))
#define MAP_DRAYNOR_BANK            (4 | (39 << 8))
#define MAP_DRAYNOR_SEWERS_1        (5 | (39 << 8))
#define MAP_DRAYNOR_SEWERS_2        (6 | (39 << 8))
#define MAP_DRAYNOR_SEWERS_3        (7 | (39 << 8))
#define MAP_DRAYNOR_SEWERS_4        (8 | (39 << 8))
#define MAP_DRAYNOR_HOUSE_AGGIE     (9 | (39 << 8))

// gMapGroup_PokescapeIndoorPortSarim
#define MAP_PORT_SARIM_PUB_1F           (0 | (40 << 8))
#define MAP_PORT_SARIM_PUB_2F           (1 | (40 << 8))
#define MAP_PORT_SARIM_BETTYS_EMPORIUM  (2 | (40 << 8))
#define MAP_PORT_SARIM_GENERAL_STORE_1F (3 | (40 << 8))
#define MAP_PORT_SARIM_GENERAL_STORE_2F (4 | (40 << 8))
#define MAP_PORT_SARIM_FISHING_STORE    (5 | (40 << 8))
#define MAP_PORT_SARIM_JEWELRY_STORE    (6 | (40 << 8))
#define MAP_PORT_SARIM_JEWELRY_STORE_2F (7 | (40 << 8))
#define MAP_PORT_SARIM_BRIANS_BAZAAR_1F (8 | (40 << 8))
#define MAP_PORT_SARIM_BRIANS_BAZAAR_2F (9 | (40 << 8))
#define MAP_PORT_SARIM_BANK             (10 | (40 << 8))
#define MAP_PORT_SARIM_CHURCH           (11 | (40 << 8))

// gMapGroup_PokescapeIndoorRimmington
#define MAP_RIMMINGTON_HOUSE_1F         (0 | (41 << 8))
#define MAP_RIMMINGTON_HOUSE_2F         (1 | (41 << 8))
#define MAP_RIMMINGTON_HETTYS_HOUSE     (2 | (41 << 8))
#define MAP_RIMMINGTON_CRAFTING_HOUSE   (3 | (41 << 8))
#define MAP_RIMMINGTON_FLETCHING_HOUSE  (4 | (41 << 8))
#define MAP_RIMMINGTON_GENERAL_STORE_1F (5 | (41 << 8))
#define MAP_RIMMINGTON_GENERAL_STORE_2F (6 | (41 << 8))
#define MAP_RIMMINGTON_LAB              (7 | (41 << 8))
#define MAP_RIMMINGTON_BANK             (8 | (41 << 8))
#define MAP_ROUTE8_MAKEOVER_MAGE        (9 | (41 << 8))
#define MAP_ROUTE8_CRAFTING_GUILD       (10 | (41 << 8))

// gMapGroup_PokescapeIndoorFalador
#define MAP_FALADOR_HAIRDRESSERS     (0 | (42 << 8))
#define MAP_FALADOR_HAIRDRESSERS_2F  (1 | (42 << 8))
#define MAP_FALADOR_CASTLEYARD       (2 | (42 << 8))
#define MAP_FALADOR_BANK_WEST_1F     (3 | (42 << 8))
#define MAP_FALADOR_GEM_SHOP         (4 | (42 << 8))
#define MAP_FALADOR_PUB_1F           (5 | (42 << 8))
#define MAP_FALADOR_PUB_2F           (6 | (42 << 8))
#define MAP_FALADOR_BANK_EAST        (7 | (42 << 8))
#define MAP_FALADOR_GENERAL_STORE_1F (8 | (42 << 8))
#define MAP_FALADOR_GENERAL_STORE_2F (9 | (42 << 8))
#define MAP_FALADOR_WORKSHOP         (10 | (42 << 8))
#define MAP_FALADOR_WORKSHOP_2F      (11 | (42 << 8))
#define MAP_FALADOR_HOUSE1_1F        (12 | (42 << 8))
#define MAP_FALADOR_HOUSE1_2F        (13 | (42 << 8))
#define MAP_FALADOR_CASTLE_1F        (14 | (42 << 8))
#define MAP_FALADOR_CASTLE_2F        (15 | (42 << 8))
#define MAP_FALADOR_CASTLE_3F        (16 | (42 << 8))
#define MAP_FALADOR_MACE_STORE       (17 | (42 << 8))

// gMapGroup_PokescapeIndoorVarrock
#define MAP_VARROCK_THESSALIA_SHOP    (0 | (43 << 8))
#define MAP_VARROCK_THESSALIA_SHOP_UP (1 | (43 << 8))
#define MAP_VARROCK_LOWE_SHOP         (2 | (43 << 8))
#define MAP_VARROCK_LOWE_SHOP_UP      (3 | (43 << 8))
#define MAP_VARROCK_HOUSE_1           (4 | (43 << 8))
#define MAP_VARROCK_HOUSE_1_UP        (5 | (43 << 8))
#define MAP_VARROCK_HOUSE_2           (6 | (43 << 8))
#define MAP_VARROCK_HOUSE_3           (7 | (43 << 8))
#define MAP_VARROCK_HOUSE_4           (8 | (43 << 8))
#define MAP_VARROCK_BANK_EAST         (9 | (43 << 8))
#define MAP_VARROCK_BANK_EAST_UP      (10 | (43 << 8))
#define MAP_VARROCK_WEAPON_SHOP       (11 | (43 << 8))
#define MAP_VARROCK_WEAPON_SHOP_UP    (12 | (43 << 8))
#define MAP_VARROCK_BANK_WEST         (13 | (43 << 8))
#define MAP_VARROCK_BANK_WEST_B1F     (14 | (43 << 8))
#define MAP_VARROCK_PUB_1F            (15 | (43 << 8))
#define MAP_VARROCK_PUB_2F            (16 | (43 << 8))
#define MAP_VARROCK_SEWERS_1F         (17 | (43 << 8))
#define MAP_VARROCK_SEWERS_2F         (18 | (43 << 8))
#define MAP_VARROCK_PALACE_1F         (19 | (43 << 8))
#define MAP_VARROCK_PALACE_2F         (20 | (43 << 8))
#define MAP_VARROCK_MUSEUM            (21 | (43 << 8))
#define MAP_VARROCK_GERTRUDE_HOUSE    (22 | (43 << 8))
#define MAP_VARROCK_GENERAL_STORE     (23 | (43 << 8))
#define MAP_VARROCK_AUBURY_STORE      (24 | (43 << 8))
#define MAP_GRAND_EXCHANGE_INDOOR     (25 | (43 << 8))

// gMapGroup_PokescapeIndoorBarbarianVillage
#define MAP_BARBARIAN_VILLAGE_GYM_HALL (0 | (44 << 8))
#define MAP_BARBARIAN_VILLAGE_HOUSE_1  (1 | (44 << 8))
#define MAP_BARBARIAN_VILLAGE_HOUSE_2  (2 | (44 << 8))

// gMapGroup_PokescapeIndoorAlkharid
#define MAP_ALKHARID_GYM_1F_R1      (0 | (45 << 8))
#define MAP_ALKHARID_GYM_1F_R2      (1 | (45 << 8))
#define MAP_ALKHARID_GYM_1F_R3      (2 | (45 << 8))
#define MAP_AL_KHARID_HOUSE_1       (3 | (45 << 8))
#define MAP_AL_KHARID_BANK          (4 | (45 << 8))
#define MAP_STARTER_HOUSE_AL_KHARID (5 | (45 << 8))
#define MAP_ALKHARID_GYM_2F_R1      (6 | (45 << 8))

// gMapGroup46
#define MAP_DUNGEONEERING_1     (0 | (46 << 8))
#define MAP_DUNGEONEERING_2     (1 | (46 << 8))
#define MAP_DUNGEONEERING_3     (2 | (46 << 8))
#define MAP_DUNGEONEERING_4     (3 | (46 << 8))
#define MAP_DUNGEONEERING_5     (4 | (46 << 8))
#define MAP_DUNGEONEERING_6     (5 | (46 << 8))
#define MAP_DUNGEONEERING_7     (6 | (46 << 8))
#define MAP_DUNGEONEERING_8     (7 | (46 << 8))
#define MAP_DUNGEONEERING_9     (8 | (46 << 8))
#define MAP_DUNGEONEERING_10    (9 | (46 << 8))
#define MAP_DUNGEONEERING_11    (10 | (46 << 8))
#define MAP_DUNGEONEERING_12    (11 | (46 << 8))
#define MAP_DUNGEONEERING_13    (12 | (46 << 8))
#define MAP_DUNGEONEERING_14    (13 | (46 << 8))
#define MAP_DUNGEONEERING_15    (14 | (46 << 8))
#define MAP_DUNGEONEERING_16    (15 | (46 << 8))
#define MAP_DUNGEONEERING_LOBBY (16 | (46 << 8))

// gMapGroup47

// gMapGroup_PokescapeOutdoorMembers
#define MAP_YANILLE       (0 | (48 << 8))
#define MAP_ARDOUGNE      (1 | (48 << 8))
#define MAP_ROUTE50       (2 | (48 << 8))
#define MAP_ROUTE51       (3 | (48 << 8))
#define MAP_ROUTE52       (4 | (48 << 8))
#define MAP_ROUTE53       (5 | (48 << 8))
#define MAP_ROUTE54       (6 | (48 << 8))
#define MAP_PORT_KHAZARD  (7 | (48 << 8))
#define MAP_RELLEKKA      (8 | (48 << 8))
#define MAP_ROUTE70       (9 | (48 << 8))
#define MAP_ROUTE55       (10 | (48 << 8))
#define MAP_ROUTE56       (11 | (48 << 8))
#define MAP_BRIMHAVEN     (12 | (48 << 8))
#define MAP_SEERS_VILLAGE (13 | (48 << 8))
#define MAP_ROUTE57       (14 | (48 << 8))
#define MAP_CAMELOT       (15 | (48 << 8))
#define MAP_ROUTE58       (16 | (48 << 8))
#define MAP_CATHERBY      (17 | (48 << 8))
#define MAP_ROUTE59       (18 | (48 << 8))
#define MAP_NEITIZNOT     (19 | (48 << 8))
#define MAP_JATIZSO       (20 | (48 << 8))
#define MAP_ROUTE169      (21 | (48 << 8))
#define MAP_ROUTE170      (22 | (48 << 8))
#define MAP_ROUTE171      (23 | (48 << 8))
#define MAP_ROUTE172      (24 | (48 << 8))

// gMapGroup_PokescapeIndoorTzhaar
#define MAP_TZHAAR_1F          (0 | (49 << 8))
#define MAP_TZHAAR_FIGHT_CAVES (1 | (49 << 8))
#define MAP_TZHAAR_CAVES_1     (2 | (49 << 8))

// gMapGroup_PokescapeIndoorVarious
#define MAP_ROUTE1_HOUSE_FRED                   (0 | (50 << 8))
#define MAP_ROUTE1_HOUSE_1                      (1 | (50 << 8))
#define MAP_MILL_LANE_MILL_1                    (2 | (50 << 8))
#define MAP_MILL_LANE_MILL_2                    (3 | (50 << 8))
#define MAP_MILL_LANE_MILL_3                    (4 | (50 << 8))
#define MAP_WIZARDS_TOWER_B1F                   (5 | (50 << 8))
#define MAP_WIZARDS_TOWER_1F                    (6 | (50 << 8))
#define MAP_WIZARDS_TOWER_2F                    (7 | (50 << 8))
#define MAP_WIZARDS_TOWER_3F                    (8 | (50 << 8))
#define MAP_WIZARDS_TOWER_ATTIC                 (9 | (50 << 8))
#define MAP_WIZARDS_TOWER_DINING_HALL           (10 | (50 << 8))
#define MAP_DRAYNOR_MANOR_1F                    (11 | (50 << 8))
#define MAP_DRAYNOR_MANOR_2F                    (12 | (50 << 8))
#define MAP_DRAYNOR_MANOR_3F                    (13 | (50 << 8))
#define MAP_DRAYNOR_MANOR_B1F                   (14 | (50 << 8))
#define MAP_DRAYNOR_MANOR_CRYPT                 (15 | (50 << 8))
#define MAP_JOLLY_BOAR_PUB_1F                   (16 | (50 << 8))
#define MAP_JOLLY_BOAR_PUB_2F                   (17 | (50 << 8))
#define MAP_YANILLE_PUB_1F                      (18 | (50 << 8))
#define MAP_YANILLE_PUB_2F                      (19 | (50 << 8))
#define MAP_POISON_ARROW_PUB_1F                 (20 | (50 << 8))
#define MAP_FLYING_HORSE_PUB_1F                 (21 | (50 << 8))
#define MAP_FLYING_HORSE_PUB_2F                 (22 | (50 << 8))
#define MAP_HAM_HIDEOUT_B1F                     (23 | (50 << 8))
#define MAP_HAM_HIDEOUT_B2F                     (24 | (50 << 8))
#define MAP_MODERATOR_LOBBY                     (25 | (50 << 8))
#define MAP_POISON_WASTE_SEWERS_1F              (26 | (50 << 8))
#define MAP_SINKHOLE_1                          (27 | (50 << 8))
#define MAP_MAZCAB_OTOT                         (28 | (50 << 8))
#define MAP_LUMBRIDGE_SWAMP_HOUSE_FATHER_URHNEY (29 | (50 << 8))
#define MAP_LUMBRIDGE_SWAMP_SHACK               (30 | (50 << 8))
#define MAP_SINKHOLE_2                          (31 | (50 << 8))
#define MAP_SINKHOLE_3                          (32 | (50 << 8))
#define MAP_SINKHOLE_4                          (33 | (50 << 8))
#define MAP_POH_1                               (34 | (50 << 8))
#define MAP_POH_1_INSIDE                        (35 | (50 << 8))
#define MAP_RIMMINGTON_MINES                    (36 | (50 << 8))
#define MAP_RIMMINGTON_MINES_B2F                (37 | (50 << 8))
#define MAP_RIMMINGTON_MINES_B3F                (38 | (50 << 8))
#define MAP_RIMMINGTON_MINES_B1F                (39 | (50 << 8))
#define MAP_GOBLIN_VILLAGE_HOUSE_1              (40 | (50 << 8))
#define MAP_GOBLIN_VILLAGE_HOUSE_2              (41 | (50 << 8))
#define MAP_DORICS_HUT                          (42 | (50 << 8))
#define MAP_GOBLIN_VILLAGE_HOUSE_3              (43 | (50 << 8))
#define MAP_MINIGAME_1                          (44 | (50 << 8))
#define MAP_MINIGAME_2                          (45 | (50 << 8))
#define MAP_WILDERNESS_VOLCANO_CHAMPION_ROOM    (46 | (50 << 8))
#define MAP_POLYPORE_DUNGEON                    (47 | (50 << 8))
#define MAP_STARTER_HOUSE_VARROCK               (48 | (50 << 8))
#define MAP_STARTER_HOUSE_FALADOR               (49 | (50 << 8))
#define MAP_STARTER_HOUSE_YANILLE               (50 | (50 << 8))
#define MAP_BARB_STRONGHOLD_B1F                 (51 | (50 << 8))
#define MAP_BARB_STRONGHOLD_B2F                 (52 | (50 << 8))
#define MAP_BARB_STRONGHOLD_B3F                 (53 | (50 << 8))
#define MAP_BARB_STRONGHOLD_B4F                 (54 | (50 << 8))
#define MAP_BARROWS                             (55 | (50 << 8))
#define MAP_JATIZSO_HOUSE_1                     (56 | (50 << 8))
#define MAP_JATIZSO_HOUSE_2                     (57 | (50 << 8))
#define MAP_JATIZSO_HOUSE_3                     (58 | (50 << 8))
#define MAP_JATIZSO_CAVE                        (59 | (50 << 8))
#define MAP_STARTER_HOUSE_RELLEKKA              (60 | (50 << 8))
#define MAP_JATIZSO_HOUSE_4                     (61 | (50 << 8))
#define MAP_JATIZSO_HOUSE_5                     (62 | (50 << 8))
#define MAP_JATIZSO_BANK                        (63 | (50 << 8))
#define MAP_CORPOREAL_BEAST_LAIR                (64 | (50 << 8))
#define MAP_KOUREND_CATACOMBS_1                 (65 | (50 << 8))
#define MAP_MUSA_POINT_PUB_1F                   (66 | (50 << 8))
#define MAP_MUSA_POINT_BANANA_SHOP              (67 | (50 << 8))
#define MAP_MUSA_POINT_GENERAL_STORE            (68 | (50 << 8))
#define MAP_KOUREND_CATACOMBS_2                 (69 | (50 << 8))
#define MAP_KOUREND_CATACOMBS_3                 (70 | (50 << 8))
#define MAP_KOUREND_CATACOMBS_4                 (71 | (50 << 8))
#define MAP_KOUREND_CATACOMBS_5                 (72 | (50 << 8))
#define MAP_KOUREND_CATACOMBS_6                 (73 | (50 << 8))
#define MAP_KOUREND_CATACOMBS_7                 (74 | (50 << 8))
#define MAP_GWD_1                               (75 | (50 << 8))
#define MAP_GWD_2                               (76 | (50 << 8))
#define MAP_GWD_3                               (77 | (50 << 8))
#define MAP_HIDDEN_GROTTOS                      (78 | (50 << 8))

#define MAP_GROUPS_COUNT 51

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
