#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define	MAPSEC_TUTORIAL_ISLAND	        0x00
#define	MAPSEC_LUMBRIDGE	            0x01
#define	MAPSEC_DRAYNOR	                0x02
#define	MAPSEC_PORT_SARIM	            0x03
#define	MAPSEC_RIMMINGTON	            0x04
#define	MAPSEC_TAVERLEY					0x05
#define	MAPSEC_FALADOR	                0x06
#define	MAPSEC_BARBARIAN_VILLAGE		0x07
#define	MAPSEC_VARROCK	         		0x08       
#define	MAPSEC_EDGEVILLE				0x09
#define	MAPSEC_ALKHARID					0x0A
#define	MAPSEC_MUSA_POINT				0x0B
#define	MAPSEC_GOBLIN_VILLAGE	       	0x0C 
#define	MAPSEC_DWARVEN_MINES	        0x0D
#define	MAPSEC_LUMBRIDGE_SWAMP	        0x0E
#define	MAPSEC_MILL_LANE_MILL	        0x0F
#define	MAPSEC_DRAYNOR_MANOR	        0x10
#define	MAPSEC_MUDSKIPPER_POINT	        0x11
#define	MAPSEC_WIZARDS_TOWER	        0x12
#define	MAPSEC_ROUTE_1	                0x13
#define	MAPSEC_ROUTE_2	                0x14
#define	MAPSEC_ROUTE_3	                0x15
#define	MAPSEC_ROUTE_4	                0x16
#define	MAPSEC_ROUTE_5	                0x17
#define	MAPSEC_ROUTE_6	                0x18
#define	MAPSEC_ROUTE_7	                0x19
#define	MAPSEC_ROUTE_8	                0x1A
#define	MAPSEC_ROUTE_9	                0x1B
#define	MAPSEC_ROUTE_10	                0x1C
#define	MAPSEC_ROUTE_11	                0x1D
#define	MAPSEC_ROUTE_12	                0x1E
#define	MAPSEC_ROUTE_13	                0x1F
#define	MAPSEC_ROUTE_14	                0x20
#define	MAPSEC_ROUTE_15	                0x21
#define	MAPSEC_ROUTE_16	                0x22
#define	MAPSEC_ROUTE_17	                0x23
#define	MAPSEC_ROUTE_18	                0x24
#define	MAPSEC_ROUTE_19	                0x25
#define	MAPSEC_ROUTE_20	                0x26
#define	MAPSEC_ROUTE_21	                0x27
#define	MAPSEC_ROUTE_22	                0x28
#define	MAPSEC_ROUTE_23	                0x29
#define	MAPSEC_ROUTE_24	                0x2A
#define	MAPSEC_ROUTE_25	                0x2B
#define	MAPSEC_ROUTE_26	                0x2C
#define	MAPSEC_ROUTE_27	                0x2D
#define	MAPSEC_ROUTE_28	                0x2E
#define	MAPSEC_ROUTE_29	                0x2F
#define	MAPSEC_ROUTE_30	                0x30
#define	MAPSEC_ROUTE_31	                0x31
#define	MAPSEC_ROUTE_32	                0x32
#define	MAPSEC_ROUTE_33	                0x33
#define	MAPSEC_ROUTE_34	                0x34
#define	MAPSEC_ROUTE_35	                0x35
#define	MAPSEC_ROUTE_36	                0x36
#define	MAPSEC_ROUTE_37	                0x37
#define	MAPSEC_ROUTE_38	                0x38
#define	MAPSEC_ROUTE_39	                0x39
#define	MAPSEC_ROUTE_40	                0x3A
#define	MAPSEC_ROUTE_41	                0x3B
#define	MAPSEC_ROUTE_42	                0x3C
#define	MAPSEC_ROUTE_43	                0x3D
#define	MAPSEC_LUMBRIDGE_FOREST		    0x3E
#define	MAPSEC_KARAMJA_VOLCANO		    0x3F
#define	MAPSEC_ASGARNIAN_DUNGEON		0x40
#define	MAPSEC_DUNGEON_SINKHOLE	        0x41
#define	MAPSEC_RIMMINGTON_MINES	        0x42
#define	MAPSEC_ABYSS	                0x43
#define	MAPSEC_GRAND_EXCHANGE			0x44
#define	MAPSEC_MISTHALIN	            0x45
#define	MAPSEC_KHARIDIAN_DESERT	        0x46
#define	MAPSEC_ASGARNIA	                0x47
#define	MAPSEC_FELDIP_HILLS	            0x48
#define	MAPSEC_FREMENNIK_PROVINCE	    0x49
#define	MAPSEC_KANDARIN	                0x4A
#define	MAPSEC_KARAMJA	                0x4B
#define	MAPSEC_MORYTANIA	            0x4C
#define	MAPSEC_WILDERNESS	            0x4D
//vanilla
#define	MAPSEC_LITTLEROOT_TOWN	        0x4E
#define	MAPSEC_OLDALE_TOWN	            0x4F
#define	MAPSEC_DEWFORD_TOWN	            0x50
#define	MAPSEC_LAVARIDGE_TOWN	        0x51
#define	MAPSEC_FALLARBOR_TOWN	        0x52
#define	MAPSEC_VERDANTURF_TOWN	        0x53
#define	MAPSEC_PACIFIDLOG_TOWN	        0x54
#define	MAPSEC_PETALBURG_CITY	        0x55
#define	MAPSEC_SLATEPORT_CITY	        0x56
#define	MAPSEC_MAUVILLE_CITY	        0x57
#define	MAPSEC_RUSTBORO_CITY	        0x58
#define	MAPSEC_FORTREE_CITY	            0x59
#define	MAPSEC_LILYCOVE_CITY	        0x5A
#define	MAPSEC_MOSSDEEP_CITY	        0x5B
#define	MAPSEC_SOOTOPOLIS_CITY	        0x5C
#define	MAPSEC_EVER_GRANDE_CITY	        0x5D
#define	MAPSEC_ROUTE_101	            0x5E
#define	MAPSEC_ROUTE_102	            0x5F
#define	MAPSEC_ROUTE_103	            0x60
#define	MAPSEC_ROUTE_104	            0x61
#define	MAPSEC_ROUTE_105	            0x62
#define	MAPSEC_ROUTE_106	            0x63
#define	MAPSEC_ROUTE_107	            0x64
#define	MAPSEC_ROUTE_108	            0x65
#define	MAPSEC_ROUTE_109	            0x66
#define	MAPSEC_ROUTE_110	            0x67
#define	MAPSEC_ROUTE_111	            0x68
#define	MAPSEC_ROUTE_112	            0x69
#define	MAPSEC_ROUTE_113	            0x6A
#define	MAPSEC_ROUTE_114	            0x6B
#define	MAPSEC_ROUTE_115	            0x6C
#define	MAPSEC_ROUTE_116	            0x6D
#define	MAPSEC_ROUTE_117	            0x6E
#define	MAPSEC_ROUTE_118	            0x6F
#define	MAPSEC_ROUTE_119	            0x70
#define	MAPSEC_ROUTE_120	            0x71
#define	MAPSEC_ROUTE_121	            0x72
#define	MAPSEC_ROUTE_122	            0x73
#define	MAPSEC_ROUTE_123	            0x74
#define	MAPSEC_ROUTE_124	            0x75
#define	MAPSEC_ROUTE_125	            0x76
#define	MAPSEC_ROUTE_126	            0x77
#define	MAPSEC_ROUTE_127	            0x78
#define	MAPSEC_ROUTE_128	            0x79
#define	MAPSEC_ROUTE_129	            0x7A
#define	MAPSEC_ROUTE_130	            0x7B
#define	MAPSEC_ROUTE_131	            0x7C
#define	MAPSEC_ROUTE_132	            0x7D
#define	MAPSEC_ROUTE_133	            0x7E
#define	MAPSEC_ROUTE_134	            0x7F
#define	MAPSEC_UNDERWATER_124	        0x80
#define	MAPSEC_UNDERWATER_126	        0x81
#define	MAPSEC_UNDERWATER_127	        0x82
#define	MAPSEC_UNDERWATER_128	        0x83
#define	MAPSEC_UNDERWATER_SOOTOPOLIS	0x84
#define	MAPSEC_GRANITE_CAVE	            0x85
#define	MAPSEC_MT_CHIMNEY	            0x86
#define	MAPSEC_SAFARI_ZONE	            0x87
#define	MAPSEC_BATTLE_FRONTIER	        0x88
#define	MAPSEC_PETALBURG_WOODS	        0x89
#define	MAPSEC_RUSTURF_TUNNEL	        0x8A
#define	MAPSEC_ABANDONED_SHIP	        0x8B
#define	MAPSEC_NEW_MAUVILLE	            0x8C
#define	MAPSEC_METEOR_FALLS	            0x8D
#define	MAPSEC_METEOR_FALLS2	        0x8E
#define	MAPSEC_MT_PYRE	                0x8F
#define	MAPSEC_AQUA_HIDEOUT_OLD	        0x90
#define	MAPSEC_SHOAL_CAVE	            0x91
#define	MAPSEC_SEAFLOOR_CAVERN	        0x92
#define	MAPSEC_UNDERWATER_SEAFLOOR_CAVERN 0x93
#define	MAPSEC_VICTORY_ROAD	            0x94
#define	MAPSEC_MIRAGE_ISLAND	        0x95
#define	MAPSEC_CAVE_OF_ORIGIN	        0x96
#define	MAPSEC_SOUTHERN_ISLAND	        0x97
#define	MAPSEC_FIERY_PATH	            0x98
#define	MAPSEC_FIERY_PATH2	            0x99
#define	MAPSEC_JAGGED_PASS	            0x9A
#define	MAPSEC_JAGGED_PASS2	            0x9B
#define	MAPSEC_SEALED_CHAMBER	        0x9C
#define	MAPSEC_UNDERWATER_SEALED_CHAMBER 0x9D
#define	MAPSEC_SCORCHED_SLAB	        0x9E
#define	MAPSEC_ISLAND_CAVE	            0x9F
#define	MAPSEC_DESERT_RUINS	            0xA0
#define	MAPSEC_ANCIENT_TOMB	            0xA1
#define	MAPSEC_INSIDE_OF_TRUCK	        0xA2
#define	MAPSEC_SKY_PILLAR	            0xA3
#define	MAPSEC_SECRET_BASE	            0xA4
#define	MAPSEC_DYNAMIC	                0xA5
#define	MAPSEC_PALLET_TOWN	            0xA6
#define	MAPSEC_SPECIAL_AREA	            0xA7
#define	MAPSEC_AQUA_HIDEOUT	            0xA8
#define	MAPSEC_MAGMA_HIDEOUT	        0xA9
#define	MAPSEC_MIRAGE_TOWER	            0xAA
#define	MAPSEC_BIRTH_ISLAND	            0xAB
#define	MAPSEC_FARAWAY_ISLAND	        0xAC
#define	MAPSEC_ARTISAN_CAVE	            0xAD
#define	MAPSEC_MARINE_CAVE	            0xAE
#define	MAPSEC_UNDERWATER_MARINE_CAVE	0xAF
#define	MAPSEC_TERRA_CAVE	            0xB0
#define	MAPSEC_UNDERWATER_105	        0xB1
#define	MAPSEC_UNDERWATER_125	        0xB2
#define	MAPSEC_UNDERWATER_129	        0xB3
#define	MAPSEC_DESERT_UNDERPASS	        0xB4
#define	MAPSEC_ALTERING_CAVE	        0xB5
#define	MAPSEC_NAVEL_ROCK	            0xB6
#define	MAPSEC_TRAINER_HILL	            0xB7		
//
#define	MAPSEC_CRANDOR            		0xB8	
#define	MAPSEC_ICE_MOUNTAIN            	0xB9
#define	MAPSEC_GROTTO            	    0xBA
#define	MAPSEC_MOR_UL_REK            	0xBB
#define	MAPSEC_LUMBRIDGE_SWAMP_CAVES   	0xBC
#define	MAPSEC_BAY_OF_SARIM   	        0xBD
#define	MAPSEC_MUDSKIPPER_SOUND	        0xBE
#define	MAPSEC_DAEMONHEIM	            0xBF	

#define MAPSEC_NONE                     0xFB
#define MAPSEC_ENDMAPSEC                0xFC

#define METLOC_SPECIAL_EGG              0xFD
#define METLOC_IN_GAME_TRADE            0xFE
#define METLOC_FATEFUL_ENCOUNTER        0xFF

#define KANTO_MAPSEC_START  MAPSEC_PALLET_TOWN
#define KANTO_MAPSEC_END    MAPSEC_SPECIAL_AREA
#define KANTO_MAPSEC_COUNT (KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

#endif //GUARD_REGIONMAPSEC_H