#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(SUNNY_DAY) \
    F(RAIN_DANCE) \
    F(HAIL) \
    F(SANDSTORM) \
    F(TAILWIND) \
    F(FLAME_CHARGE) \
    F(RAZOR_SHELL) \
    F(SOLAR_BLADE) \
    F(GRASSY_TERRAIN) \
    F(ELECTRIC_TERRAIN) \
    F(PSYCHIC_TERRAIN) \
    F(MISTY_TERRAIN) \
    F(BRINE) \
    F(ENERGY_BALL) \
    F(LAVA_PLUME) \
    F(HURRICANE) \
    F(AERIAL_ACE) \
    F(STEEL_WING) \
    F(VOLT_TACKLE) \
    F(DRAINING_KISS) \
    F(TOXIC) \
    F(SHADOW_BONE) \
    F(BANEFUL_BUNKER) \
    F(U_TURN) \
    F(GUILLOTINE) \
    F(KINGS_SHIELD) \
    F(SACRED_SWORD) \
    F(SWORDS_DANCE) \
    F(SECRET_SWORD) \
    F(RETURN) \
    F(FRUSTRATION) \
    F(FALSE_SWIPE) \
    F(DRAGON_BREATH) \
    F(DRAGON_HAMMER) \
    F(LEECH_LIFE) \
    F(SLACK_OFF) \
    F(THOUSAND_ARROWS) \
    F(ROCK_TOMB) \
    F(REVELATION_DANCE) \
    F(VOLT_SWITCH) \
    F(FLASH_CANNON) \
    F(POLLEN_PUFF) \
    F(PSYCHO_CUT) \
    F(PLAY_ROUGH) \
    F(SPECTRAL_THIEF) \
    F(DRAGON_TAIL) \
    F(LUNAR_DANCE) \
    F(POWER_GEM) \
    F(SNARL) \
    F(POISON_JAB) \
    F(ICICLE_CRASH) \
    F(POWDER) \
    F(ICE_BEAM) \
    F(MUD_BOMB) \
    F(HEX) \
    F(SWITCHEROO) \
    F(PSYSHOCK) \
    F(SLUDGE_WAVE) \
    F(SPIKES) \
    F(BULK_UP) \
    F(PAY_DAY) \
    F(DEFOG) \
    F(TRICK_OR_TREAT) \
    F(REVENGE) \
    F(ICE_HAMMER) \
    F(BRUTAL_SWING)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
