Tzhaar_Caves_2_MapScripts::
	.byte 0


TZHAAR_CAVES_2_NPC_1::
	faceplayer
	msgbox TZHAAR_CAVES_2_NPC_1_Text_0
	closemessage
	release
	end


TZHAAR_CAVES_2_NPC_2::
	faceplayer
	msgbox TZHAAR_CAVES_2_NPC_2_Text_0
	closemessage
	release
	end


TZHAAR_CAVES_2_NPC_1_Text_0:
	.string "Ah, trusted and most capable JalYt,\n"
	.string "this is the city of Mor Ul Rek.\p"
	.string "It has grand central inferno, our\n"
	.string "birthing pool.\p"
	.string "It currently closed, but one day you go\n"
	.string "see for yourself!$"

TZHAAR_CAVES_2_NPC_2_Text_0:
	.string "It only took thousands of purple\n"
	.string "sweets and hundreds of hours of\l"
	.string "perfect tick manipulation, but finally..\p"
	.string "The first level 3 with a firecape!\p"
	.string "What do you mean xzact did it first?!$"
