Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed {PLAYER}'s Bank Account.$"

gText_StorageSystemOpened::
	.string "MONSTER Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s Bank Account.$"

gText_AccessedLanettesPC::
	.string "Accessed LANETTE's PC.$"
