name: 🧠 Battle AI bugs 🐛
description: File a bug report related to battle AI.
labels: ["bug", "status: unconfirmed", "category: battle-ai"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all required fields with as many details as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the issue you are experiencing.
        Attach images/videos if possible.
      placeholder: |
        Please enter a description of the issue. Here you can also attach log screenshots, gifs or a video
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of pokeemerald-expansion are you using as a base?
      options:
        - 1.7.4 (Latest release)
        - master (default when pulling, unreleased bugfixes)
        - upcoming (Edge)
        - 1.7.3
        - 1.7.2
        - 1.7.1
        - 1.7.0
        - 1.6.2
        - 1.6.1
        - 1.6.0
        - pre-1.6.0
    validations:
      required: true
  - type: input
    id: upcomingversion
    attributes:
      label: Upcoming/master Version
      description: If you're using the upcoming or master branches directly, please specify what was the commit hash you pulled from.
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Discord contact info
      description: Provide your Discord tag here so we can contact you in case we need more details. Be sure to join our server ([here](https://discord.gg/6CzjAG6GZk)).
      placeholder: ex. Lunos#4026
    validations:
      required: false
