Yanille_Pub_1F_MapScripts::
	.byte 0


NPC_YANILLE_PUB_1F_1::
	lock
	faceplayer
	namebox NPC_YANILLE_PUB_1F_1_Text_0
	msgbox NPC_YANILLE_PUB_1F_1_Text_1
	closemessage
	hidenamebox
	release
	end


NPC_YANILLE_PUB_1F_2::
	lock
	faceplayer
	namebox NPC_YANILLE_PUB_1F_2_Text_0
	msgbox NPC_YANILLE_PUB_1F_2_Text_1
	closemessage
	hidenamebox
	release
	end


NPC_YANILLE_PUB_1F_3::
	lock
	faceplayer
	namebox NPC_YANILLE_PUB_1F_3_Text_0
	msgbox NPC_YANILLE_PUB_1F_3_Text_1
	closemessage
	hidenamebox
	release
	end


NPC_YANILLE_PUB_1F_4::
	lock
	faceplayer
	namebox NPC_YANILLE_PUB_1F_1_Text_0
	msgbox NPC_YANILLE_PUB_1F_1_Text_1
	closemessage
	hidenamebox
	release
	end


NPC_YANILLE_PUB_1F_5::
	lock
	faceplayer
	namebox NPC_YANILLE_PUB_1F_5_Text_0
	msgbox NPC_YANILLE_PUB_1F_5_Text_1
	closemessage
	hidenamebox
	release
	end


NPC_YANILLE_PUB_1F_6::
	lock
	faceplayer
	namebox NPC_YANILLE_PUB_1F_1_Text_0
	msgbox NPC_YANILLE_PUB_1F_1_Text_1
	closemessage
	hidenamebox
	release
	end


NPC_YANILLE_PUB_1F_1_Text_0:
	.string "Cupholder$"

NPC_YANILLE_PUB_1F_1_Text_1:
	.string "I am a Cupholder.$"

NPC_YANILLE_PUB_1F_2_Text_0:
	.string "Bartender$"

NPC_YANILLE_PUB_1F_2_Text_1:
	.string "I'm afraid we're all out of alcohol at\n"
	.string "the moment.\p"
	.string "Someone should tell the Guard Captain\n"
	.string "he needs to drink less!$"

NPC_YANILLE_PUB_1F_3_Text_0:
	.string "Vathrelk$"

NPC_YANILLE_PUB_1F_3_Text_1:
	.string "I'm on Alfred Grimhand's Barcrawl.\p"
	.string "I've just had some Fire Brandy, but my\n"
	.string "visions still a little blurry!$"

NPC_YANILLE_PUB_1F_5_Text_0:
	.string "Guard Captain$"

NPC_YANILLE_PUB_1F_5_Text_1:
	.string "Go 'way! This pint'sh nearly finished!\n"
	.string "Unlessh you got more that ish....?$"
