name: CI

on:
  push:
    branches:
      - master
      - upcoming
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      COMPARE: 0
      UNUSED_ERROR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y build-essential libgtk-3-dev pkg-config libpng-dev libelf-dev golang
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: ROM
        env:
          COMPARE: 0
        run: |
          make -j${nproc} -O all

      - name: Test
        env:
          TEST: 1
        run: |
          make -j${nproc} -O pokescape-test.elf
          make -j${nproc} check
