name: CI

on:
  push:
    branches:
      - master
      - upcoming
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      COMPARE: 0
      UNUSED_ERROR: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Checkout poryscript
        uses: actions/checkout@v3
        with:
          path: poryscript
          repository: huderlem/poryscript

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y build-essential libpng-dev libelf-dev golang
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install poryscript
        run: |
          go build
          ./install.sh ../
        working-directory: poryscript

      - name: Hack poryscript configs
        run: |
          cp tools/poryscript/*.json .

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} -O all

